// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type CreateUseCaseRequest struct {
	// The integration ID
	IntegrationID        string                      `pathParam:"style=simple,explode=false,name=integrationId"`
	CreateUseCaseRequest shared.CreateUseCaseRequest `request:"mediaType=application/json"`
}

func (c *CreateUseCaseRequest) GetIntegrationID() string {
	if c == nil {
		return ""
	}
	return c.IntegrationID
}

func (c *CreateUseCaseRequest) GetCreateUseCaseRequest() shared.CreateUseCaseRequest {
	if c == nil {
		return shared.CreateUseCaseRequest{}
	}
	return c.CreateUseCaseRequest
}

func (c *CreateUseCaseRequest) GetCreateUseCaseRequestInbound() *shared.CreateInboundUseCaseRequest {
	return c.GetCreateUseCaseRequest().CreateInboundUseCaseRequest
}

func (c *CreateUseCaseRequest) GetCreateUseCaseRequestOutbound() *shared.CreateOutboundUseCaseRequest {
	return c.GetCreateUseCaseRequest().CreateOutboundUseCaseRequest
}

type CreateUseCaseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Use case created successfully
	UseCase *shared.UseCase
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (c *CreateUseCaseResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateUseCaseResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateUseCaseResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateUseCaseResponse) GetUseCase() *shared.UseCase {
	if c == nil {
		return nil
	}
	return c.UseCase
}

func (c *CreateUseCaseResponse) GetUseCaseInbound() *shared.Schemas {
	if v := c.GetUseCase(); v != nil {
		return v.Schemas
	}
	return nil
}

func (c *CreateUseCaseResponse) GetUseCaseOutbound() *shared.OutboundUseCaseSchemas {
	if v := c.GetUseCase(); v != nil {
		return v.OutboundUseCaseSchemas
	}
	return nil
}

func (c *CreateUseCaseResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if c == nil {
		return nil
	}
	return c.ErrorResponseBase
}
