// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type CreateIntegrationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Integration created successfully
	Integration *shared.Integration
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (c *CreateIntegrationResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateIntegrationResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateIntegrationResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateIntegrationResponse) GetIntegration() *shared.Integration {
	if c == nil {
		return nil
	}
	return c.Integration
}

func (c *CreateIntegrationResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if c == nil {
		return nil
	}
	return c.ErrorResponseBase
}
