// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type DeleteIntegrationV2Request struct {
	// The integration ID
	IntegrationID string `pathParam:"style=simple,explode=false,name=integrationId"`
}

func (d *DeleteIntegrationV2Request) GetIntegrationID() string {
	if d == nil {
		return ""
	}
	return d.IntegrationID
}

// DeleteIntegrationV2ResponseBody - Integration deleted successfully
type DeleteIntegrationV2ResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (d *DeleteIntegrationV2ResponseBody) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

type DeleteIntegrationV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Integration deleted successfully
	Object *DeleteIntegrationV2ResponseBody
	// Unauthorized request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (d *DeleteIntegrationV2Response) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteIntegrationV2Response) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteIntegrationV2Response) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteIntegrationV2Response) GetObject() *DeleteIntegrationV2ResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DeleteIntegrationV2Response) GetErrorResponseBase() *shared.ErrorResponseBase {
	if d == nil {
		return nil
	}
	return d.ErrorResponseBase
}
