// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type DeleteIntegrationRequest struct {
	// The integration ID
	IntegrationID string `pathParam:"style=simple,explode=false,name=integrationId"`
}

func (o *DeleteIntegrationRequest) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}

// DeleteIntegrationResponseBody - Integration deleted successfully
type DeleteIntegrationResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *DeleteIntegrationResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type DeleteIntegrationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Integration deleted successfully
	Object *DeleteIntegrationResponseBody
	// Unauthorized request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (o *DeleteIntegrationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteIntegrationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteIntegrationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteIntegrationResponse) GetObject() *DeleteIntegrationResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeleteIntegrationResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if o == nil {
		return nil
	}
	return o.ErrorResponseBase
}
