// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type DeleteIntegrationAppMappingRequest struct {
	// The integration ID (used for authorization, must match the mapping)
	IntegrationID                      string                                    `pathParam:"style=simple,explode=false,name=integrationId"`
	DeleteIntegrationAppMappingRequest shared.DeleteIntegrationAppMappingRequest `request:"mediaType=application/json"`
}

func (d *DeleteIntegrationAppMappingRequest) GetIntegrationID() string {
	if d == nil {
		return ""
	}
	return d.IntegrationID
}

func (d *DeleteIntegrationAppMappingRequest) GetDeleteIntegrationAppMappingRequest() shared.DeleteIntegrationAppMappingRequest {
	if d == nil {
		return shared.DeleteIntegrationAppMappingRequest{}
	}
	return d.DeleteIntegrationAppMappingRequest
}

// DeleteIntegrationAppMappingResponseBody - App mapping deleted successfully
type DeleteIntegrationAppMappingResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (d *DeleteIntegrationAppMappingResponseBody) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

type DeleteIntegrationAppMappingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// App mapping deleted successfully
	Object *DeleteIntegrationAppMappingResponseBody
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (d *DeleteIntegrationAppMappingResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteIntegrationAppMappingResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteIntegrationAppMappingResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteIntegrationAppMappingResponse) GetObject() *DeleteIntegrationAppMappingResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DeleteIntegrationAppMappingResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if d == nil {
		return nil
	}
	return d.ErrorResponseBase
}
