// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type GenerateTypesPreviewRequest struct {
	IntegrationID string `pathParam:"style=simple,explode=false,name=integrationId"`
}

func (g *GenerateTypesPreviewRequest) GetIntegrationID() string {
	if g == nil {
		return ""
	}
	return g.IntegrationID
}

type GenerateTypesPreviewResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Scaffolded type preview
	GenerateTypesPreviewResponse *shared.GenerateTypesPreviewResponse
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (g *GenerateTypesPreviewResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GenerateTypesPreviewResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GenerateTypesPreviewResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GenerateTypesPreviewResponse) GetGenerateTypesPreviewResponse() *shared.GenerateTypesPreviewResponse {
	if g == nil {
		return nil
	}
	return g.GenerateTypesPreviewResponse
}

func (g *GenerateTypesPreviewResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if g == nil {
		return nil
	}
	return g.ErrorResponseBase
}
