// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type GenerateTypesRequest struct {
	IntegrationID        string                      `pathParam:"style=simple,explode=false,name=integrationId"`
	GenerateTypesRequest shared.GenerateTypesRequest `request:"mediaType=application/json"`
}

func (g *GenerateTypesRequest) GetIntegrationID() string {
	if g == nil {
		return ""
	}
	return g.IntegrationID
}

func (g *GenerateTypesRequest) GetGenerateTypesRequest() shared.GenerateTypesRequest {
	if g == nil {
		return shared.GenerateTypesRequest{}
	}
	return g.GenerateTypesRequest
}

type GenerateTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Generated package
	GenerateTypesResponse *shared.GenerateTypesResponse
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (g *GenerateTypesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GenerateTypesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GenerateTypesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GenerateTypesResponse) GetGenerateTypesResponse() *shared.GenerateTypesResponse {
	if g == nil {
		return nil
	}
	return g.GenerateTypesResponse
}

func (g *GenerateTypesResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if g == nil {
		return nil
	}
	return g.ErrorResponseBase
}
