// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type GetAssociatedMonitoringEventsRequest struct {
	// The integration ID
	IntegrationID string `pathParam:"style=simple,explode=false,name=integrationId"`
	// The event ID to get associated events for
	EventID string `pathParam:"style=simple,explode=false,name=eventId"`
}

func (g *GetAssociatedMonitoringEventsRequest) GetIntegrationID() string {
	if g == nil {
		return ""
	}
	return g.IntegrationID
}

func (g *GetAssociatedMonitoringEventsRequest) GetEventID() string {
	if g == nil {
		return ""
	}
	return g.EventID
}

// GetAssociatedMonitoringEventsResponseBody - Associated monitoring events for the given event_id
type GetAssociatedMonitoringEventsResponseBody struct {
	// All monitoring events sharing this event_id, ordered by created_at ASC
	MonitoringEvents []shared.MonitoringEventV2 `json:"monitoring_events,omitempty"`
	// The original inbound event payload from erp_incoming_events, if available
	InboundEvent map[string]any `json:"inbound_event,omitempty"`
}

func (g *GetAssociatedMonitoringEventsResponseBody) GetMonitoringEvents() []shared.MonitoringEventV2 {
	if g == nil {
		return nil
	}
	return g.MonitoringEvents
}

func (g *GetAssociatedMonitoringEventsResponseBody) GetInboundEvent() map[string]any {
	if g == nil {
		return nil
	}
	return g.InboundEvent
}

type GetAssociatedMonitoringEventsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Associated monitoring events for the given event_id
	Object *GetAssociatedMonitoringEventsResponseBody
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (g *GetAssociatedMonitoringEventsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAssociatedMonitoringEventsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAssociatedMonitoringEventsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAssociatedMonitoringEventsResponse) GetObject() *GetAssociatedMonitoringEventsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetAssociatedMonitoringEventsResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if g == nil {
		return nil
	}
	return g.ErrorResponseBase
}
