// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type GetIntegrationV2Request struct {
	// The integration ID
	IntegrationID string `pathParam:"style=simple,explode=false,name=integrationId"`
}

func (g *GetIntegrationV2Request) GetIntegrationID() string {
	if g == nil {
		return ""
	}
	return g.IntegrationID
}

type GetIntegrationV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully retrieved integration with use cases
	IntegrationWithUseCases *shared.IntegrationWithUseCases
	// Unauthorized request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (g *GetIntegrationV2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetIntegrationV2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetIntegrationV2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetIntegrationV2Response) GetIntegrationWithUseCases() *shared.IntegrationWithUseCases {
	if g == nil {
		return nil
	}
	return g.IntegrationWithUseCases
}

func (g *GetIntegrationV2Response) GetErrorResponseBase() *shared.ErrorResponseBase {
	if g == nil {
		return nil
	}
	return g.ErrorResponseBase
}
