// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
	"time"
)

type GetMonitoringTimeSeriesV2Request struct {
	// The integration ID
	IntegrationID                    string                                  `pathParam:"style=simple,explode=false,name=integrationId"`
	GetMonitoringTimeSeriesV2Request shared.GetMonitoringTimeSeriesV2Request `request:"mediaType=application/json"`
}

func (g *GetMonitoringTimeSeriesV2Request) GetIntegrationID() string {
	if g == nil {
		return ""
	}
	return g.IntegrationID
}

func (g *GetMonitoringTimeSeriesV2Request) GetGetMonitoringTimeSeriesV2Request() shared.GetMonitoringTimeSeriesV2Request {
	if g == nil {
		return shared.GetMonitoringTimeSeriesV2Request{}
	}
	return g.GetMonitoringTimeSeriesV2Request
}

// #region class-body-getmonitoringtimeseriesv2request
// #endregion class-body-getmonitoringtimeseriesv2request

// GetMonitoringTimeSeriesV2Interval - The bucket interval
type GetMonitoringTimeSeriesV2Interval string

const (
	GetMonitoringTimeSeriesV2IntervalFivem   GetMonitoringTimeSeriesV2Interval = "5m"
	GetMonitoringTimeSeriesV2IntervalTenm    GetMonitoringTimeSeriesV2Interval = "10m"
	GetMonitoringTimeSeriesV2IntervalThirtym GetMonitoringTimeSeriesV2Interval = "30m"
	GetMonitoringTimeSeriesV2IntervalOneh    GetMonitoringTimeSeriesV2Interval = "1h"
	GetMonitoringTimeSeriesV2IntervalThreeh  GetMonitoringTimeSeriesV2Interval = "3h"
	GetMonitoringTimeSeriesV2IntervalOned    GetMonitoringTimeSeriesV2Interval = "1d"
)

func (e GetMonitoringTimeSeriesV2Interval) ToPointer() *GetMonitoringTimeSeriesV2Interval {
	return &e
}
func (e *GetMonitoringTimeSeriesV2Interval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "5m":
		fallthrough
	case "10m":
		fallthrough
	case "30m":
		fallthrough
	case "1h":
		fallthrough
	case "3h":
		fallthrough
	case "1d":
		*e = GetMonitoringTimeSeriesV2Interval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetMonitoringTimeSeriesV2Interval: %v", v)
	}
}

// GetMonitoringTimeSeriesV2ResponseBody - Time-series data retrieved successfully
type GetMonitoringTimeSeriesV2ResponseBody struct {
	// The bucket interval
	Interval *GetMonitoringTimeSeriesV2Interval `json:"interval,omitempty"`
	FromDate *time.Time                         `json:"from_date,omitempty"`
	ToDate   *time.Time                         `json:"to_date,omitempty"`
	Buckets  []shared.TimeSeriesBucketV2        `json:"buckets,omitempty"`
}

func (g GetMonitoringTimeSeriesV2ResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMonitoringTimeSeriesV2ResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMonitoringTimeSeriesV2ResponseBody) GetInterval() *GetMonitoringTimeSeriesV2Interval {
	if g == nil {
		return nil
	}
	return g.Interval
}

func (g *GetMonitoringTimeSeriesV2ResponseBody) GetFromDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.FromDate
}

func (g *GetMonitoringTimeSeriesV2ResponseBody) GetToDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.ToDate
}

func (g *GetMonitoringTimeSeriesV2ResponseBody) GetBuckets() []shared.TimeSeriesBucketV2 {
	if g == nil {
		return nil
	}
	return g.Buckets
}

// #region class-body-getmonitoringtimeseriesv2responsebody
// #endregion class-body-getmonitoringtimeseriesv2responsebody

type GetMonitoringTimeSeriesV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Time-series data retrieved successfully
	Object *GetMonitoringTimeSeriesV2ResponseBody
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (g *GetMonitoringTimeSeriesV2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMonitoringTimeSeriesV2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMonitoringTimeSeriesV2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMonitoringTimeSeriesV2Response) GetObject() *GetMonitoringTimeSeriesV2ResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetMonitoringTimeSeriesV2Response) GetErrorResponseBase() *shared.ErrorResponseBase {
	if g == nil {
		return nil
	}
	return g.ErrorResponseBase
}

// #region class-body-getmonitoringtimeseriesv2response
// #endregion class-body-getmonitoringtimeseriesv2response
