// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type GetUseCaseRequest struct {
	// The integration ID
	IntegrationID string `pathParam:"style=simple,explode=false,name=integrationId"`
	// The use case ID
	UseCaseID string `pathParam:"style=simple,explode=false,name=useCaseId"`
}

func (g *GetUseCaseRequest) GetIntegrationID() string {
	if g == nil {
		return ""
	}
	return g.IntegrationID
}

func (g *GetUseCaseRequest) GetUseCaseID() string {
	if g == nil {
		return ""
	}
	return g.UseCaseID
}

type GetUseCaseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully retrieved use case
	UseCase *shared.UseCase
	// Unauthorized request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (g *GetUseCaseResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetUseCaseResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetUseCaseResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetUseCaseResponse) GetUseCase() *shared.UseCase {
	if g == nil {
		return nil
	}
	return g.UseCase
}

func (g *GetUseCaseResponse) GetUseCaseInbound() *shared.InboundUseCase {
	if v := g.GetUseCase(); v != nil {
		return v.InboundUseCase
	}
	return nil
}

func (g *GetUseCaseResponse) GetUseCaseOutbound() *shared.OutboundUseCase {
	if v := g.GetUseCase(); v != nil {
		return v.OutboundUseCase
	}
	return nil
}

func (g *GetUseCaseResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if g == nil {
		return nil
	}
	return g.ErrorResponseBase
}
