// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type ListNotificationHistoryRequest struct {
	// The integration ID
	IntegrationID string `pathParam:"style=simple,explode=false,name=integrationId"`
	// Opaque base64 pagination cursor returned as `next_cursor` by a prior page.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Requested number of items to return. Values above 100 are accepted and clamped server-side to 100 (the enforcement point is the handler, not this schema), so a large value never 400s at the contract layer.
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Optional notification type filter (e.g. `critical_error`, `error_threshold`).
	Type *string `queryParam:"style=form,explode=true,name=type"`
}

func (l ListNotificationHistoryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListNotificationHistoryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListNotificationHistoryRequest) GetIntegrationID() string {
	if l == nil {
		return ""
	}
	return l.IntegrationID
}

func (l *ListNotificationHistoryRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListNotificationHistoryRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListNotificationHistoryRequest) GetType() *string {
	if l == nil {
		return nil
	}
	return l.Type
}

type ListNotificationHistoryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Cursor-paginated notification history (newest first)
	NotificationHistoryResponse *shared.NotificationHistoryResponse
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (l *ListNotificationHistoryResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListNotificationHistoryResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListNotificationHistoryResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListNotificationHistoryResponse) GetNotificationHistoryResponse() *shared.NotificationHistoryResponse {
	if l == nil {
		return nil
	}
	return l.NotificationHistoryResponse
}

func (l *ListNotificationHistoryResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if l == nil {
		return nil
	}
	return l.ErrorResponseBase
}
