// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

// ListSecureProxiesResponseBody - Successfully retrieved secure proxy use cases
type ListSecureProxiesResponseBody struct {
	SecureProxies []shared.SecureProxySummary `json:"secure_proxies"`
}

func (l *ListSecureProxiesResponseBody) GetSecureProxies() []shared.SecureProxySummary {
	if l == nil {
		return []shared.SecureProxySummary{}
	}
	return l.SecureProxies
}

type ListSecureProxiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully retrieved secure proxy use cases
	Object *ListSecureProxiesResponseBody
	// Unauthorized request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (l *ListSecureProxiesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListSecureProxiesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListSecureProxiesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListSecureProxiesResponse) GetObject() *ListSecureProxiesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListSecureProxiesResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if l == nil {
		return nil
	}
	return l.ErrorResponseBase
}
