// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type ManagedCallExecuteRequest struct {
	// Use case slug (acts as the RPC method name)
	Slug                      string                           `pathParam:"style=simple,explode=false,name=slug"`
	ManagedCallExecuteRequest shared.ManagedCallExecuteRequest `request:"mediaType=application/json"`
}

func (m *ManagedCallExecuteRequest) GetSlug() string {
	if m == nil {
		return ""
	}
	return m.Slug
}

func (m *ManagedCallExecuteRequest) GetManagedCallExecuteRequest() shared.ManagedCallExecuteRequest {
	if m == nil {
		return shared.ManagedCallExecuteRequest{}
	}
	return m.ManagedCallExecuteRequest
}

type ManagedCallExecuteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Managed call executed successfully.
	// The response body is the JSONata-mapped result (or raw external API response if no mapping).
	// If inbound routing is configured, check X-Inbound-Event-Id header for tracking.
	//
	ManagedCallExecuteResponse map[string]any
	// Bad request (e.g., invalid URL blocked by SSRF protection)
	ManagedCallErrorResponse *shared.ManagedCallErrorResponse
	// Unauthorized request
	ErrorResponseBase *shared.ErrorResponseBase
	Headers           map[string][]string
}

func (m *ManagedCallExecuteResponse) GetContentType() string {
	if m == nil {
		return ""
	}
	return m.ContentType
}

func (m *ManagedCallExecuteResponse) GetStatusCode() int {
	if m == nil {
		return 0
	}
	return m.StatusCode
}

func (m *ManagedCallExecuteResponse) GetRawResponse() *http.Response {
	if m == nil {
		return nil
	}
	return m.RawResponse
}

func (m *ManagedCallExecuteResponse) GetManagedCallExecuteResponse() map[string]any {
	if m == nil {
		return nil
	}
	return m.ManagedCallExecuteResponse
}

func (m *ManagedCallExecuteResponse) GetManagedCallErrorResponse() *shared.ManagedCallErrorResponse {
	if m == nil {
		return nil
	}
	return m.ManagedCallErrorResponse
}

func (m *ManagedCallExecuteResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if m == nil {
		return nil
	}
	return m.ErrorResponseBase
}

func (m *ManagedCallExecuteResponse) GetHeaders() map[string][]string {
	if m == nil {
		return map[string][]string{}
	}
	return m.Headers
}
