// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type PollOutboundMessagesRequest struct {
	// The integration ID
	IntegrationID               string                              `pathParam:"style=simple,explode=false,name=integrationId"`
	PollOutboundMessagesRequest *shared.PollOutboundMessagesRequest `request:"mediaType=application/json"`
}

func (p *PollOutboundMessagesRequest) GetIntegrationID() string {
	if p == nil {
		return ""
	}
	return p.IntegrationID
}

func (p *PollOutboundMessagesRequest) GetPollOutboundMessagesRequest() *shared.PollOutboundMessagesRequest {
	if p == nil {
		return nil
	}
	return p.PollOutboundMessagesRequest
}

type PollOutboundMessagesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Leased batch of outbound messages (possibly empty)
	PollOutboundMessagesResponse *shared.PollOutboundMessagesResponse
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (p *PollOutboundMessagesResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PollOutboundMessagesResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PollOutboundMessagesResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PollOutboundMessagesResponse) GetPollOutboundMessagesResponse() *shared.PollOutboundMessagesResponse {
	if p == nil {
		return nil
	}
	return p.PollOutboundMessagesResponse
}

func (p *PollOutboundMessagesResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if p == nil {
		return nil
	}
	return p.ErrorResponseBase
}
