// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

// ProcessErpUpdatesEventsV2Status - Processing status for the event (skipped indicates duplicate deduplication_id, ignored indicates unconfigured event)
type ProcessErpUpdatesEventsV2Status string

const (
	ProcessErpUpdatesEventsV2StatusSuccess ProcessErpUpdatesEventsV2Status = "success"
	ProcessErpUpdatesEventsV2StatusError   ProcessErpUpdatesEventsV2Status = "error"
	ProcessErpUpdatesEventsV2StatusSkipped ProcessErpUpdatesEventsV2Status = "skipped"
	ProcessErpUpdatesEventsV2StatusIgnored ProcessErpUpdatesEventsV2Status = "ignored"
)

func (e ProcessErpUpdatesEventsV2Status) ToPointer() *ProcessErpUpdatesEventsV2Status {
	return &e
}
func (e *ProcessErpUpdatesEventsV2Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "error":
		fallthrough
	case "skipped":
		fallthrough
	case "ignored":
		*e = ProcessErpUpdatesEventsV2Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProcessErpUpdatesEventsV2Status: %v", v)
	}
}

type ProcessErpUpdatesEventsV2Results struct {
	// ID of the processed event
	EventID string `json:"event_id"`
	// Processing status for the event (skipped indicates duplicate deduplication_id, ignored indicates unconfigured event)
	Status  ProcessErpUpdatesEventsV2Status `json:"status"`
	Message *string                         `json:"message,omitempty"`
}

func (p *ProcessErpUpdatesEventsV2Results) GetEventID() string {
	if p == nil {
		return ""
	}
	return p.EventID
}

func (p *ProcessErpUpdatesEventsV2Results) GetStatus() ProcessErpUpdatesEventsV2Status {
	if p == nil {
		return ProcessErpUpdatesEventsV2Status("")
	}
	return p.Status
}

func (p *ProcessErpUpdatesEventsV2Results) GetMessage() *string {
	if p == nil {
		return nil
	}
	return p.Message
}

// ProcessErpUpdatesEventsV2ResponseBody - Some events failed to process
type ProcessErpUpdatesEventsV2ResponseBody struct {
	Results []ProcessErpUpdatesEventsV2Results `json:"results,omitempty"`
}

func (p *ProcessErpUpdatesEventsV2ResponseBody) GetResults() []ProcessErpUpdatesEventsV2Results {
	if p == nil {
		return nil
	}
	return p.Results
}

type ProcessErpUpdatesEventsV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Some events failed to process
	Object *ProcessErpUpdatesEventsV2ResponseBody
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (p *ProcessErpUpdatesEventsV2Response) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *ProcessErpUpdatesEventsV2Response) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *ProcessErpUpdatesEventsV2Response) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *ProcessErpUpdatesEventsV2Response) GetObject() *ProcessErpUpdatesEventsV2ResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}

func (p *ProcessErpUpdatesEventsV2Response) GetErrorResponseBase() *shared.ErrorResponseBase {
	if p == nil {
		return nil
	}
	return p.ErrorResponseBase
}
