// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

// Meta - Metadata to be passed along with the events
type Meta struct {
	// ID that identifies the specific request for debugging purposes
	CorrelationID        *string `json:"correlation_id,omitempty"`
	AdditionalProperties any     `additionalProperties:"true" json:"-"`
}

func (m Meta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Meta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *Meta) GetCorrelationID() *string {
	if m == nil {
		return nil
	}
	return m.CorrelationID
}

func (m *Meta) GetAdditionalProperties() any {
	if m == nil {
		return nil
	}
	return m.AdditionalProperties
}

type ProcessErpUpdatesEventsRequestBody struct {
	// UUID that identifies the specific integration app instance
	AppID string `json:"app_id"`
	// UUID that identifies the specific integration app component instance
	ComponentID string `json:"component_id"`
	// Metadata to be passed along with the events
	Meta Meta `json:"meta"`
	// List of ERP events to process
	Events []shared.ErpEvent `json:"events"`
}

func (p *ProcessErpUpdatesEventsRequestBody) GetAppID() string {
	if p == nil {
		return ""
	}
	return p.AppID
}

func (p *ProcessErpUpdatesEventsRequestBody) GetComponentID() string {
	if p == nil {
		return ""
	}
	return p.ComponentID
}

func (p *ProcessErpUpdatesEventsRequestBody) GetMeta() Meta {
	if p == nil {
		return Meta{}
	}
	return p.Meta
}

func (p *ProcessErpUpdatesEventsRequestBody) GetEvents() []shared.ErpEvent {
	if p == nil {
		return []shared.ErpEvent{}
	}
	return p.Events
}

// Status - Processing status for the event (skipped indicates duplicate deduplication_id, ignored indicates unconfigured event)
type Status string

const (
	StatusSuccess Status = "success"
	StatusError   Status = "error"
	StatusSkipped Status = "skipped"
	StatusIgnored Status = "ignored"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "error":
		fallthrough
	case "skipped":
		fallthrough
	case "ignored":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type Results struct {
	// ID of the processed event
	EventID string `json:"event_id"`
	// Processing status for the event (skipped indicates duplicate deduplication_id, ignored indicates unconfigured event)
	Status  Status  `json:"status"`
	Message *string `json:"message,omitempty"`
}

func (r *Results) GetEventID() string {
	if r == nil {
		return ""
	}
	return r.EventID
}

func (r *Results) GetStatus() Status {
	if r == nil {
		return Status("")
	}
	return r.Status
}

func (r *Results) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

// ProcessErpUpdatesEventsResponseBody - Some events failed to process
type ProcessErpUpdatesEventsResponseBody struct {
	Results []Results `json:"results,omitempty"`
}

func (p *ProcessErpUpdatesEventsResponseBody) GetResults() []Results {
	if p == nil {
		return nil
	}
	return p.Results
}

type ProcessErpUpdatesEventsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Some events failed to process
	Object *ProcessErpUpdatesEventsResponseBody
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (p *ProcessErpUpdatesEventsResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *ProcessErpUpdatesEventsResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *ProcessErpUpdatesEventsResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *ProcessErpUpdatesEventsResponse) GetObject() *ProcessErpUpdatesEventsResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}

func (p *ProcessErpUpdatesEventsResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if p == nil {
		return nil
	}
	return p.ErrorResponseBase
}
