// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
	"time"
)

type QueryAccessLogsRequest struct {
	// The integration ID (used for tenant authorization)
	IntegrationID          string                        `pathParam:"style=simple,explode=false,name=integrationId"`
	QueryAccessLogsRequest shared.QueryAccessLogsRequest `request:"mediaType=application/json"`
}

func (q *QueryAccessLogsRequest) GetIntegrationID() string {
	if q == nil {
		return ""
	}
	return q.IntegrationID
}

func (q *QueryAccessLogsRequest) GetQueryAccessLogsRequest() shared.QueryAccessLogsRequest {
	if q == nil {
		return shared.QueryAccessLogsRequest{}
	}
	return q.QueryAccessLogsRequest
}

// QueryAccessLogsNextCursor - Cursor to fetch the next page. Null if no more results.
type QueryAccessLogsNextCursor struct {
	Timestamp *time.Time `json:"timestamp,omitempty"`
	RequestID *string    `json:"request_id,omitempty"`
}

func (q QueryAccessLogsNextCursor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAccessLogsNextCursor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryAccessLogsNextCursor) GetTimestamp() *time.Time {
	if q == nil {
		return nil
	}
	return q.Timestamp
}

func (q *QueryAccessLogsNextCursor) GetRequestID() *string {
	if q == nil {
		return nil
	}
	return q.RequestID
}

// QueryAccessLogsResponseBody - Access logs queried successfully
type QueryAccessLogsResponseBody struct {
	// List of access log entries
	Data []shared.AccessLogEntry `json:"data,omitempty"`
	// Cursor to fetch the next page. Null if no more results.
	NextCursor *QueryAccessLogsNextCursor `json:"next_cursor,omitempty"`
	// Indicates if more results are available
	HasMore *bool `json:"has_more,omitempty"`
}

func (q *QueryAccessLogsResponseBody) GetData() []shared.AccessLogEntry {
	if q == nil {
		return nil
	}
	return q.Data
}

func (q *QueryAccessLogsResponseBody) GetNextCursor() *QueryAccessLogsNextCursor {
	if q == nil {
		return nil
	}
	return q.NextCursor
}

func (q *QueryAccessLogsResponseBody) GetHasMore() *bool {
	if q == nil {
		return nil
	}
	return q.HasMore
}

type QueryAccessLogsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Access logs queried successfully
	Object *QueryAccessLogsResponseBody
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (q *QueryAccessLogsResponse) GetContentType() string {
	if q == nil {
		return ""
	}
	return q.ContentType
}

func (q *QueryAccessLogsResponse) GetStatusCode() int {
	if q == nil {
		return 0
	}
	return q.StatusCode
}

func (q *QueryAccessLogsResponse) GetRawResponse() *http.Response {
	if q == nil {
		return nil
	}
	return q.RawResponse
}

func (q *QueryAccessLogsResponse) GetObject() *QueryAccessLogsResponseBody {
	if q == nil {
		return nil
	}
	return q.Object
}

func (q *QueryAccessLogsResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if q == nil {
		return nil
	}
	return q.ErrorResponseBase
}
