// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type SetIntegrationAppMappingRequest struct {
	// The integration ID to map to
	IntegrationID                   string                                 `pathParam:"style=simple,explode=false,name=integrationId"`
	SetIntegrationAppMappingRequest shared.SetIntegrationAppMappingRequest `request:"mediaType=application/json"`
}

func (s *SetIntegrationAppMappingRequest) GetIntegrationID() string {
	if s == nil {
		return ""
	}
	return s.IntegrationID
}

func (s *SetIntegrationAppMappingRequest) GetSetIntegrationAppMappingRequest() shared.SetIntegrationAppMappingRequest {
	if s == nil {
		return shared.SetIntegrationAppMappingRequest{}
	}
	return s.SetIntegrationAppMappingRequest
}

type SetIntegrationAppMappingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// App mapping set successfully
	IntegrationAppMapping *shared.IntegrationAppMapping
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (s *SetIntegrationAppMappingResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SetIntegrationAppMappingResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SetIntegrationAppMappingResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SetIntegrationAppMappingResponse) GetIntegrationAppMapping() *shared.IntegrationAppMapping {
	if s == nil {
		return nil
	}
	return s.IntegrationAppMapping
}

func (s *SetIntegrationAppMappingResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if s == nil {
		return nil
	}
	return s.ErrorResponseBase
}
