// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type UpdateUseCaseRequest struct {
	// The integration ID
	IntegrationID string `pathParam:"style=simple,explode=false,name=integrationId"`
	// The use case ID
	UseCaseID            string                      `pathParam:"style=simple,explode=false,name=useCaseId"`
	UpdateUseCaseRequest shared.UpdateUseCaseRequest `request:"mediaType=application/json"`
}

func (o *UpdateUseCaseRequest) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}

func (o *UpdateUseCaseRequest) GetUseCaseID() string {
	if o == nil {
		return ""
	}
	return o.UseCaseID
}

func (o *UpdateUseCaseRequest) GetUpdateUseCaseRequest() shared.UpdateUseCaseRequest {
	if o == nil {
		return shared.UpdateUseCaseRequest{}
	}
	return o.UpdateUseCaseRequest
}

func (o *UpdateUseCaseRequest) GetUpdateUseCaseRequestInbound() *shared.UpdateInboundUseCaseRequest {
	return o.GetUpdateUseCaseRequest().UpdateInboundUseCaseRequest
}

func (o *UpdateUseCaseRequest) GetUpdateUseCaseRequestOutbound() *shared.UpdateOutboundUseCaseRequest {
	return o.GetUpdateUseCaseRequest().UpdateOutboundUseCaseRequest
}

type UpdateUseCaseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Use case updated successfully
	UseCase *shared.UseCase
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (o *UpdateUseCaseResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateUseCaseResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateUseCaseResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateUseCaseResponse) GetUseCase() *shared.UseCase {
	if o == nil {
		return nil
	}
	return o.UseCase
}

func (o *UpdateUseCaseResponse) GetUseCaseInbound() *shared.Schemas {
	if v := o.GetUseCase(); v != nil {
		return v.Schemas
	}
	return nil
}

func (o *UpdateUseCaseResponse) GetUseCaseOutbound() *shared.OutboundUseCaseSchemas {
	if v := o.GetUseCase(); v != nil {
		return v.OutboundUseCaseSchemas
	}
	return nil
}

func (o *UpdateUseCaseResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if o == nil {
		return nil
	}
	return o.ErrorResponseBase
}
