// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"net/http"
)

type UpdateIntegrationRequest struct {
	// The integration ID
	IntegrationID            string                          `pathParam:"style=simple,explode=false,name=integrationId"`
	UpdateIntegrationRequest shared.UpdateIntegrationRequest `request:"mediaType=application/json"`
}

func (o *UpdateIntegrationRequest) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}

func (o *UpdateIntegrationRequest) GetUpdateIntegrationRequest() shared.UpdateIntegrationRequest {
	if o == nil {
		return shared.UpdateIntegrationRequest{}
	}
	return o.UpdateIntegrationRequest
}

type UpdateIntegrationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Integration updated successfully
	Integration *shared.Integration
	// Bad request
	ErrorResponseBase *shared.ErrorResponseBase
}

func (o *UpdateIntegrationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateIntegrationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateIntegrationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateIntegrationResponse) GetIntegration() *shared.Integration {
	if o == nil {
		return nil
	}
	return o.Integration
}

func (o *UpdateIntegrationResponse) GetErrorResponseBase() *shared.ErrorResponseBase {
	if o == nil {
		return nil
	}
	return o.ErrorResponseBase
}
