// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AckOutboundMessagesResponse struct {
	// Per-id acknowledgement outcome
	Results []AckResult `json:"results"`
}

func (a *AckOutboundMessagesResponse) GetResults() []AckResult {
	if a == nil {
		return []AckResult{}
	}
	return a.Results
}
