// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CommitTypesRequest struct {
	// npm package name
	PackageName string `json:"package_name"`
	// Package version
	Version string `json:"version"`
	// Type annotations per use case slug
	Annotations map[string]TypeAnnotations `json:"annotations,omitempty"`
}

func (c *CommitTypesRequest) GetPackageName() string {
	if c == nil {
		return ""
	}
	return c.PackageName
}

func (c *CommitTypesRequest) GetVersion() string {
	if c == nil {
		return ""
	}
	return c.Version
}

func (c *CommitTypesRequest) GetAnnotations() map[string]TypeAnnotations {
	if c == nil {
		return nil
	}
	return c.Annotations
}
