// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// CreateOutboundUseCaseRequestType - Use case type
type CreateOutboundUseCaseRequestType string

const (
	CreateOutboundUseCaseRequestTypeOutbound CreateOutboundUseCaseRequestType = "outbound"
)

func (e CreateOutboundUseCaseRequestType) ToPointer() *CreateOutboundUseCaseRequestType {
	return &e
}
func (e *CreateOutboundUseCaseRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "outbound":
		*e = CreateOutboundUseCaseRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateOutboundUseCaseRequestType: %v", v)
	}
}

type CreateOutboundUseCaseRequest struct {
	// Use case name
	Name string `json:"name"`
	// Whether the use case is enabled
	Enabled bool `json:"enabled"`
	// Use case type
	Type CreateOutboundUseCaseRequestType `json:"type"`
	// Configuration for outbound use cases (epilot to ERP). Structure TBD.
	Configuration map[string]any `json:"configuration,omitempty"`
}

func (c CreateOutboundUseCaseRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOutboundUseCaseRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOutboundUseCaseRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOutboundUseCaseRequest) GetEnabled() bool {
	if c == nil {
		return false
	}
	return c.Enabled
}

func (c *CreateOutboundUseCaseRequest) GetType() CreateOutboundUseCaseRequestType {
	if c == nil {
		return CreateOutboundUseCaseRequestType("")
	}
	return c.Type
}

func (c *CreateOutboundUseCaseRequest) GetConfiguration() map[string]any {
	if c == nil {
		return nil
	}
	return c.Configuration
}
