// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateIntegrationRequest struct {
	// Integration name
	Name string `json:"name"`
	// Optional description of the integration
	Description *string `json:"description,omitempty"`
}

func (o *CreateIntegrationRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateIntegrationRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
