// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateIntegrationRequest struct {
	// Integration name
	Name string `json:"name"`
	// Optional description of the integration
	Description *string `json:"description,omitempty"`
}

func (c *CreateIntegrationRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateIntegrationRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}
