// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

type DeliveryConfigType string

const (
	DeliveryConfigTypeWebhook DeliveryConfigType = "webhook"
	DeliveryConfigTypePoll    DeliveryConfigType = "poll"
)

// DeliveryConfig - Configuration for how the event should be delivered. webhook = push delivery via svc-webhooks (JSONata-transformed payload); poll = pull-based queue delivery where the consumer fetches items via the poll API (raw event payload)
type DeliveryConfig struct {
	WebhookDeliveryConfig *WebhookDeliveryConfig `queryParam:"inline" union:"member"`
	PollDeliveryConfig    *PollDeliveryConfig    `queryParam:"inline" union:"member"`

	Type DeliveryConfigType
}

func CreateDeliveryConfigWebhook(webhook WebhookDeliveryConfig) DeliveryConfig {
	typ := DeliveryConfigTypeWebhook

	typStr := WebhookDeliveryConfigType(typ)
	webhook.Type = typStr

	return DeliveryConfig{
		WebhookDeliveryConfig: &webhook,
		Type:                  typ,
	}
}

func CreateDeliveryConfigPoll(poll PollDeliveryConfig) DeliveryConfig {
	typ := DeliveryConfigTypePoll

	typStr := PollDeliveryConfigType(typ)
	poll.Type = typStr

	return DeliveryConfig{
		PollDeliveryConfig: &poll,
		Type:               typ,
	}
}

func (u *DeliveryConfig) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "webhook":
		webhookDeliveryConfig := new(WebhookDeliveryConfig)
		if err := utils.UnmarshalJSON(data, &webhookDeliveryConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == webhook) type WebhookDeliveryConfig within DeliveryConfig: %w", string(data), err)
		}

		u.WebhookDeliveryConfig = webhookDeliveryConfig
		u.Type = DeliveryConfigTypeWebhook
		return nil
	case "poll":
		pollDeliveryConfig := new(PollDeliveryConfig)
		if err := utils.UnmarshalJSON(data, &pollDeliveryConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == poll) type PollDeliveryConfig within DeliveryConfig: %w", string(data), err)
		}

		u.PollDeliveryConfig = pollDeliveryConfig
		u.Type = DeliveryConfigTypePoll
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DeliveryConfig", string(data))
}

func (u DeliveryConfig) MarshalJSON() ([]byte, error) {
	if u.WebhookDeliveryConfig != nil {
		return utils.MarshalJSON(u.WebhookDeliveryConfig, "", true)
	}

	if u.PollDeliveryConfig != nil {
		return utils.MarshalJSON(u.PollDeliveryConfig, "", true)
	}

	return nil, errors.New("could not marshal union type DeliveryConfig: all fields are null")
}
