// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// EmbeddedOutboundUseCaseRequestType - Use case type
type EmbeddedOutboundUseCaseRequestType string

const (
	EmbeddedOutboundUseCaseRequestTypeOutbound EmbeddedOutboundUseCaseRequestType = "outbound"
)

func (e EmbeddedOutboundUseCaseRequestType) ToPointer() *EmbeddedOutboundUseCaseRequestType {
	return &e
}
func (e *EmbeddedOutboundUseCaseRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "outbound":
		*e = EmbeddedOutboundUseCaseRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EmbeddedOutboundUseCaseRequestType: %v", v)
	}
}

type EmbeddedOutboundUseCaseRequest struct {
	// Optional use case ID for update matching.
	// - If provided and matches an existing use case, that use case is updated
	// - If provided but no match, a new use case with this ID is created
	// - If omitted, a new use case with auto-generated ID is created
	//
	ID *string `json:"id,omitempty"`
	// Use case name
	Name string `json:"name"`
	// Whether the use case is enabled
	Enabled bool `json:"enabled"`
	// Optional description of this change (like a commit message)
	ChangeDescription *string `json:"change_description,omitempty"`
	// Use case type
	Type EmbeddedOutboundUseCaseRequestType `json:"type"`
	// Configuration for outbound use cases. Defines the event that triggers the flow and the webhook mappings.
	Configuration *OutboundIntegrationEventConfiguration `json:"configuration,omitempty"`
}

func (e EmbeddedOutboundUseCaseRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmbeddedOutboundUseCaseRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EmbeddedOutboundUseCaseRequest) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EmbeddedOutboundUseCaseRequest) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EmbeddedOutboundUseCaseRequest) GetEnabled() bool {
	if e == nil {
		return false
	}
	return e.Enabled
}

func (e *EmbeddedOutboundUseCaseRequest) GetChangeDescription() *string {
	if e == nil {
		return nil
	}
	return e.ChangeDescription
}

func (e *EmbeddedOutboundUseCaseRequest) GetType() EmbeddedOutboundUseCaseRequestType {
	if e == nil {
		return EmbeddedOutboundUseCaseRequestType("")
	}
	return e.Type
}

func (e *EmbeddedOutboundUseCaseRequest) GetConfiguration() *OutboundIntegrationEventConfiguration {
	if e == nil {
		return nil
	}
	return e.Configuration
}
