// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// EmbeddedInboundUseCaseRequestType - Use case type
type EmbeddedInboundUseCaseRequestType string

const (
	EmbeddedInboundUseCaseRequestTypeInbound EmbeddedInboundUseCaseRequestType = "inbound"
)

func (e EmbeddedInboundUseCaseRequestType) ToPointer() *EmbeddedInboundUseCaseRequestType {
	return &e
}
func (e *EmbeddedInboundUseCaseRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inbound":
		*e = EmbeddedInboundUseCaseRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EmbeddedInboundUseCaseRequestType: %v", v)
	}
}

type EmbeddedInboundUseCaseRequest struct {
	// Optional use case ID for update matching.
	// - If provided and matches an existing use case, that use case is updated
	// - If provided but no match, a new use case with this ID is created
	// - If omitted, a new use case with auto-generated ID is created
	//
	ID *string `json:"id,omitempty"`
	// Use case name
	Name string `json:"name"`
	// Whether the use case is enabled
	Enabled bool `json:"enabled"`
	// Optional description of this change (like a commit message)
	ChangeDescription *string `json:"change_description,omitempty"`
	// Use case type
	Type EmbeddedInboundUseCaseRequestType `json:"type"`
	// Configuration for inbound use cases (ERP to epilot)
	Configuration *InboundIntegrationEventConfiguration `json:"configuration,omitempty"`
}

func (e EmbeddedInboundUseCaseRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmbeddedInboundUseCaseRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EmbeddedInboundUseCaseRequest) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EmbeddedInboundUseCaseRequest) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EmbeddedInboundUseCaseRequest) GetEnabled() bool {
	if e == nil {
		return false
	}
	return e.Enabled
}

func (e *EmbeddedInboundUseCaseRequest) GetChangeDescription() *string {
	if e == nil {
		return nil
	}
	return e.ChangeDescription
}

func (e *EmbeddedInboundUseCaseRequest) GetType() EmbeddedInboundUseCaseRequestType {
	if e == nil {
		return EmbeddedInboundUseCaseRequestType("")
	}
	return e.Type
}

func (e *EmbeddedInboundUseCaseRequest) GetConfiguration() *InboundIntegrationEventConfiguration {
	if e == nil {
		return nil
	}
	return e.Configuration
}
