// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EntityUpdate struct {
	// The entity type slug
	EntitySlug string `json:"entity_slug"`
	// Unique identifier mappings for this entity
	UniqueIdentifiers map[string]any `json:"unique_identifiers"`
	// Mapped attribute values
	Attributes map[string]any `json:"attributes"`
}

func (e *EntityUpdate) GetEntitySlug() string {
	if e == nil {
		return ""
	}
	return e.EntitySlug
}

func (e *EntityUpdate) GetUniqueIdentifiers() map[string]any {
	if e == nil {
		return map[string]any{}
	}
	return e.UniqueIdentifiers
}

func (e *EntityUpdate) GetAttributes() map[string]any {
	if e == nil {
		return map[string]any{}
	}
	return e.Attributes
}
