// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// Type - Whether the value is a plain string or an encrypted secret
type Type string

const (
	TypeString       Type = "String"
	TypeSecretString Type = "SecretString"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "String":
		fallthrough
	case "SecretString":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type EnvironmentFieldConfig struct {
	// Environment variable key, used to look up the value in the Environments API.
	Key string `json:"key"`
	// Display label for the field in the UI
	Label string `json:"label"`
	// Whether the value is a plain string or an encrypted secret
	Type Type `json:"type"`
	// Help text shown below the field
	Description *string `json:"description,omitempty"`
	// Whether this field must be filled before the integration can be used
	Required *bool `default:"false" json:"required"`
	// Sort order for display and drag-to-reorder
	Order *int64 `json:"order,omitempty"`
}

func (e EnvironmentFieldConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvironmentFieldConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnvironmentFieldConfig) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *EnvironmentFieldConfig) GetLabel() string {
	if e == nil {
		return ""
	}
	return e.Label
}

func (e *EnvironmentFieldConfig) GetType() Type {
	if e == nil {
		return Type("")
	}
	return e.Type
}

func (e *EnvironmentFieldConfig) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *EnvironmentFieldConfig) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvironmentFieldConfig) GetOrder() *int64 {
	if e == nil {
		return nil
	}
	return e.Order
}
