// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// EnvVarRefConfigSchemasReturn - Evaluate the sibling `jsonataExpression` against the resolved env-var value (the input `$` is the string value).
type EnvVarRefConfigSchemasReturn string

const (
	EnvVarRefConfigSchemasReturnJsonata EnvVarRefConfigSchemasReturn = "jsonata"
)

func (e EnvVarRefConfigSchemasReturn) ToPointer() *EnvVarRefConfigSchemasReturn {
	return &e
}
func (e *EnvVarRefConfigSchemasReturn) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "jsonata":
		*e = EnvVarRefConfigSchemasReturn(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvVarRefConfigSchemasReturn: %v", v)
	}
}

type EnvVarRefConfig2 struct {
	Key     string  `json:"key"`
	Default *string `json:"default,omitempty"`
	// Evaluate the sibling `jsonataExpression` against the resolved env-var value (the input `$` is the string value).
	//
	Return EnvVarRefConfigSchemasReturn `json:"return"`
	// JSONata expression evaluated against the resolved env-var value.
	JsonataExpression string `json:"jsonataExpression"`
}

func (e EnvVarRefConfig2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvVarRefConfig2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnvVarRefConfig2) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *EnvVarRefConfig2) GetDefault() *string {
	if e == nil {
		return nil
	}
	return e.Default
}

func (e *EnvVarRefConfig2) GetReturn() EnvVarRefConfigSchemasReturn {
	if e == nil {
		return EnvVarRefConfigSchemasReturn("")
	}
	return e.Return
}

func (e *EnvVarRefConfig2) GetJsonataExpression() string {
	if e == nil {
		return ""
	}
	return e.JsonataExpression
}

// #region class-body-envvarrefconfig2
// #endregion class-body-envvarrefconfig2

// EnvVarRefConfigReturn - `value` returns the resolved env-var string as-is.
type EnvVarRefConfigReturn string

const (
	EnvVarRefConfigReturnValue EnvVarRefConfigReturn = "value"
)

func (e EnvVarRefConfigReturn) ToPointer() *EnvVarRefConfigReturn {
	return &e
}
func (e *EnvVarRefConfigReturn) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "value":
		*e = EnvVarRefConfigReturn(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvVarRefConfigReturn: %v", v)
	}
}

type EnvVarRefConfig1 struct {
	// Environment variable key. Must match the environments-api key contract (lowercase, digits, `_`, `.`, `-`; max 128 chars; starts with a lowercase letter or digit). Supports dot-namespaced keys like `erp_api.base_url`.
	//
	Key string `json:"key"`
	// Literal string returned when the key is missing (or is a secret). When provided, the `ENV_VAR_REF_NOT_FOUND` warning is suppressed because the author signalled the absence is expected.
	//
	Default *string `json:"default,omitempty"`
	// `value` returns the resolved env-var string as-is.
	//
	Return *EnvVarRefConfigReturn `default:"value" json:"return"`
}

func (e EnvVarRefConfig1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvVarRefConfig1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnvVarRefConfig1) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *EnvVarRefConfig1) GetDefault() *string {
	if e == nil {
		return nil
	}
	return e.Default
}

func (e *EnvVarRefConfig1) GetReturn() *EnvVarRefConfigReturn {
	if e == nil {
		return nil
	}
	return e.Return
}

// #region class-body-envvarrefconfig1
// #endregion class-body-envvarrefconfig1

type EnvVarRefConfigType string

const (
	EnvVarRefConfigTypeEnvVarRefConfig1 EnvVarRefConfigType = "EnvVarRefConfig_1"
	EnvVarRefConfigTypeEnvVarRefConfig2 EnvVarRefConfigType = "EnvVarRefConfig_2"
)

// EnvVarRefConfig - Resolves to an org-scoped environment variable from the epilot environments-api service at runtime, replacing hard-coded environment-specific values (URLs, prefixes, identifiers) in inbound mappings. Secrets (`SecretString` values) are never exposed; the runtime treats both "missing key" and "secret-typed key" as identical `undefined` outcomes (no info disclosure via error code). For secret-resolving contexts (e.g. authorization headers in managed-call or file-proxy step configurations), use the templated `{{ env.<key> }}` syntax instead — that mechanism does decrypt secrets.
type EnvVarRefConfig struct {
	EnvVarRefConfig1 *EnvVarRefConfig1 `queryParam:"inline" union:"member"`
	EnvVarRefConfig2 *EnvVarRefConfig2 `queryParam:"inline" union:"member"`

	Type EnvVarRefConfigType
}

func CreateEnvVarRefConfigEnvVarRefConfig1(envVarRefConfig1 EnvVarRefConfig1) EnvVarRefConfig {
	typ := EnvVarRefConfigTypeEnvVarRefConfig1

	return EnvVarRefConfig{
		EnvVarRefConfig1: &envVarRefConfig1,
		Type:             typ,
	}
}

func CreateEnvVarRefConfigEnvVarRefConfig2(envVarRefConfig2 EnvVarRefConfig2) EnvVarRefConfig {
	typ := EnvVarRefConfigTypeEnvVarRefConfig2

	return EnvVarRefConfig{
		EnvVarRefConfig2: &envVarRefConfig2,
		Type:             typ,
	}
}

func (u *EnvVarRefConfig) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var envVarRefConfig1 EnvVarRefConfig1 = EnvVarRefConfig1{}
	if err := utils.UnmarshalJSON(data, &envVarRefConfig1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EnvVarRefConfigTypeEnvVarRefConfig1,
			Value: &envVarRefConfig1,
		})
	}

	var envVarRefConfig2 EnvVarRefConfig2 = EnvVarRefConfig2{}
	if err := utils.UnmarshalJSON(data, &envVarRefConfig2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EnvVarRefConfigTypeEnvVarRefConfig2,
			Value: &envVarRefConfig2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for EnvVarRefConfig", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for EnvVarRefConfig", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(EnvVarRefConfigType)
	switch best.Type {
	case EnvVarRefConfigTypeEnvVarRefConfig1:
		u.EnvVarRefConfig1 = best.Value.(*EnvVarRefConfig1)
		return nil
	case EnvVarRefConfigTypeEnvVarRefConfig2:
		u.EnvVarRefConfig2 = best.Value.(*EnvVarRefConfig2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EnvVarRefConfig", string(data))
}

func (u EnvVarRefConfig) MarshalJSON() ([]byte, error) {
	if u.EnvVarRefConfig1 != nil {
		return utils.MarshalJSON(u.EnvVarRefConfig1, "", true)
	}

	if u.EnvVarRefConfig2 != nil {
		return utils.MarshalJSON(u.EnvVarRefConfig2, "", true)
	}

	return nil, errors.New("could not marshal union type EnvVarRefConfig: all fields are null")
}
