// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// ErpEventV3Format - Format of the payload data
type ErpEventV3Format string

const (
	ErpEventV3FormatJSON ErpEventV3Format = "json"
	ErpEventV3FormatXML  ErpEventV3Format = "xml"
)

func (e ErpEventV3Format) ToPointer() *ErpEventV3Format {
	return &e
}
func (e *ErpEventV3Format) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "json":
		fallthrough
	case "xml":
		*e = ErpEventV3Format(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErpEventV3Format: %v", v)
	}
}

type ErpEventV3PayloadType string

const (
	ErpEventV3PayloadTypeStr      ErpEventV3PayloadType = "str"
	ErpEventV3PayloadTypeMapOfAny ErpEventV3PayloadType = "mapOfAny"
)

// ErpEventV3Payload - The object data payload - can be either a serialized string or a direct JSON object
type ErpEventV3Payload struct {
	Str      *string        `queryParam:"inline" union:"member"`
	MapOfAny map[string]any `queryParam:"inline" union:"member"`

	Type ErpEventV3PayloadType
}

func CreateErpEventV3PayloadStr(str string) ErpEventV3Payload {
	typ := ErpEventV3PayloadTypeStr

	return ErpEventV3Payload{
		Str:  &str,
		Type: typ,
	}
}

func CreateErpEventV3PayloadMapOfAny(mapOfAny map[string]any) ErpEventV3Payload {
	typ := ErpEventV3PayloadTypeMapOfAny

	return ErpEventV3Payload{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func (u *ErpEventV3Payload) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ErpEventV3PayloadTypeStr,
			Value: &str,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ErpEventV3PayloadTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ErpEventV3Payload", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ErpEventV3Payload", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ErpEventV3PayloadType)
	switch best.Type {
	case ErpEventV3PayloadTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case ErpEventV3PayloadTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ErpEventV3Payload", string(data))
}

func (u ErpEventV3Payload) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type ErpEventV3Payload: all fields are null")
}

type ErpEventV3 struct {
	// Name of the event (e.g., business_partner, contract_account). Corresponds to the "Event Name" from the integration UI. Replaces object_type from V2.
	EventName string `json:"event_name"`
	// Timestamp when the event occurred
	Timestamp time.Time `json:"timestamp"`
	// Format of the payload data
	Format *ErpEventV3Format `default:"json" json:"format"`
	// The object data payload - can be either a serialized string or a direct JSON object
	Payload ErpEventV3Payload `json:"payload"`
	// Optional unique identifier for idempotency - prevents duplicate processing of the same event within 24 hours in context of the same integration. Must contain only alphanumeric characters, hyphens, and underscores.
	//
	DeduplicationID *string `json:"deduplication_id,omitempty"`
}

func (e ErpEventV3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ErpEventV3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ErpEventV3) GetEventName() string {
	if e == nil {
		return ""
	}
	return e.EventName
}

func (e *ErpEventV3) GetTimestamp() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.Timestamp
}

func (e *ErpEventV3) GetFormat() *ErpEventV3Format {
	if e == nil {
		return nil
	}
	return e.Format
}

func (e *ErpEventV3) GetPayload() ErpEventV3Payload {
	if e == nil {
		return ErpEventV3Payload{}
	}
	return e.Payload
}

func (e *ErpEventV3) GetDeduplicationID() *string {
	if e == nil {
		return nil
	}
	return e.DeduplicationID
}
