// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ErpUpdatesEventsV2Request struct {
	// UUID that identifies the integration configuration to use
	IntegrationID string `json:"integration_id"`
	// Optional ID that identifies the specific request for debugging purposes
	CorrelationID *string `json:"correlation_id,omitempty"`
	// List of ERP events to process
	Events []ErpEvent `json:"events"`
}

func (o *ErpUpdatesEventsV2Request) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}

func (o *ErpUpdatesEventsV2Request) GetCorrelationID() *string {
	if o == nil {
		return nil
	}
	return o.CorrelationID
}

func (o *ErpUpdatesEventsV2Request) GetEvents() []ErpEvent {
	if o == nil {
		return []ErpEvent{}
	}
	return o.Events
}
