// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ErpUpdatesEventsV3Request struct {
	// UUID that identifies the integration configuration to use
	IntegrationID string `json:"integration_id"`
	// Optional ID that identifies the specific request for debugging purposes
	CorrelationID *string `json:"correlation_id,omitempty"`
	// List of ERP events to process
	Events []ErpEventV3 `json:"events"`
}

func (e *ErpUpdatesEventsV3Request) GetIntegrationID() string {
	if e == nil {
		return ""
	}
	return e.IntegrationID
}

func (e *ErpUpdatesEventsV3Request) GetCorrelationID() *string {
	if e == nil {
		return nil
	}
	return e.CorrelationID
}

func (e *ErpUpdatesEventsV3Request) GetEvents() []ErpEventV3 {
	if e == nil {
		return []ErpEventV3{}
	}
	return e.Events
}
