// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ErrorResponseBase - Bad request
type ErrorResponseBase struct {
	// Computer-readable error code
	Code *string `json:"code,omitempty"`
	// Error message
	Message *string `json:"message,omitempty"`
}

func (e *ErrorResponseBase) GetCode() *string {
	if e == nil {
		return nil
	}
	return e.Code
}

func (e *ErrorResponseBase) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}
