// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// ExternalMonitoringSpan - A single monitoring span produced by an external system. `correlation_id`, `level`, `use_case_slug`, `occurred_at` and `message` are all required and `level` must be one of success|error|warning|info — but these are validated PER SPAN at ingest and reported in the per-item `results[]`, so one malformed span never fails the whole batch (the fields are intentionally not marked `required`/`enum` at the schema level to preserve that partial-acceptance behavior). The client does NOT send a `code` (server-assigned from `level`), a `source` (origin is the EXTERNAL_* code prefix), or span/event ids (the external system owns its own identity and dedup).
type ExternalMonitoringSpan struct {
	// Trace id — links this span to the epilot trace. Unique per business operation. Required.
	CorrelationID *string `json:"correlation_id,omitempty"`
	// Span outcome level — one of success | error | warning | info. Drives the server-assigned EXTERNAL_* code, coloring, and alerting. Required.
	//
	Level *string `json:"level,omitempty"`
	// Business use case slug (e.g. "business_partner"). Resolved server-side against the integration's configured use cases to a use_case_id/use_case_type; stored as the grouping dimension. Portable — no epilot-internal UUIDs required.
	//
	UseCaseSlug *string `json:"use_case_slug,omitempty"`
	// External clock time the span occurred; stored as created_at.
	OccurredAt *time.Time `json:"occurred_at,omitempty"`
	// Human-readable line shown in the trace and event tables.
	Message *string `json:"message,omitempty"`
	// Free-form context (step, http_status, reason, …). The place for external-system specificity — the taxonomy code stays clean (EXTERNAL_*).
	//
	Detail map[string]any `json:"detail,omitempty"`
}

func (e ExternalMonitoringSpan) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExternalMonitoringSpan) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExternalMonitoringSpan) GetCorrelationID() *string {
	if e == nil {
		return nil
	}
	return e.CorrelationID
}

func (e *ExternalMonitoringSpan) GetLevel() *string {
	if e == nil {
		return nil
	}
	return e.Level
}

func (e *ExternalMonitoringSpan) GetUseCaseSlug() *string {
	if e == nil {
		return nil
	}
	return e.UseCaseSlug
}

func (e *ExternalMonitoringSpan) GetOccurredAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.OccurredAt
}

func (e *ExternalMonitoringSpan) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *ExternalMonitoringSpan) GetDetail() map[string]any {
	if e == nil {
		return nil
	}
	return e.Detail
}
