// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

type Three struct {
	// JSONata expression for transformation
	JsonataExpression string `json:"jsonataExpression"`
}

func (t Three) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Three) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Three) GetJsonataExpression() string {
	if t == nil {
		return ""
	}
	return t.JsonataExpression
}

type Two struct {
	// Constant value (any type, stringified for URL)
	Constant any `json:"constant"`
}

func (t Two) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Two) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Two) GetConstant() any {
	if t == nil {
		return nil
	}
	return t.Constant
}

type One struct {
	// Source field name or JSONPath expression (if starts with $)
	Field string `json:"field"`
}

func (o One) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *One) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *One) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

type FileProxyURLParamType string

const (
	FileProxyURLParamTypeOne   FileProxyURLParamType = "1"
	FileProxyURLParamTypeTwo   FileProxyURLParamType = "2"
	FileProxyURLParamTypeThree FileProxyURLParamType = "3"
)

// FileProxyURLParam - Parameter for file proxy URL. Exactly one of field, constant, or jsonataExpression must be set.
type FileProxyURLParam struct {
	One   *One   `queryParam:"inline" union:"member"`
	Two   *Two   `queryParam:"inline" union:"member"`
	Three *Three `queryParam:"inline" union:"member"`

	Type FileProxyURLParamType
}

func CreateFileProxyURLParamOne(one One) FileProxyURLParam {
	typ := FileProxyURLParamTypeOne

	return FileProxyURLParam{
		One:  &one,
		Type: typ,
	}
}

func CreateFileProxyURLParamTwo(two Two) FileProxyURLParam {
	typ := FileProxyURLParamTypeTwo

	return FileProxyURLParam{
		Two:  &two,
		Type: typ,
	}
}

func CreateFileProxyURLParamThree(three Three) FileProxyURLParam {
	typ := FileProxyURLParamTypeThree

	return FileProxyURLParam{
		Three: &three,
		Type:  typ,
	}
}

func (u *FileProxyURLParam) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var one One = One{}
	if err := utils.UnmarshalJSON(data, &one, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FileProxyURLParamTypeOne,
			Value: &one,
		})
	}

	var two Two = Two{}
	if err := utils.UnmarshalJSON(data, &two, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FileProxyURLParamTypeTwo,
			Value: &two,
		})
	}

	var three Three = Three{}
	if err := utils.UnmarshalJSON(data, &three, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FileProxyURLParamTypeThree,
			Value: &three,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileProxyURLParam", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileProxyURLParam", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FileProxyURLParamType)
	switch best.Type {
	case FileProxyURLParamTypeOne:
		u.One = best.Value.(*One)
		return nil
	case FileProxyURLParamTypeTwo:
		u.Two = best.Value.(*Two)
		return nil
	case FileProxyURLParamTypeThree:
		u.Three = best.Value.(*Three)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileProxyURLParam", string(data))
}

func (u FileProxyURLParam) MarshalJSON() ([]byte, error) {
	if u.One != nil {
		return utils.MarshalJSON(u.One, "", true)
	}

	if u.Two != nil {
		return utils.MarshalJSON(u.Two, "", true)
	}

	if u.Three != nil {
		return utils.MarshalJSON(u.Three, "", true)
	}

	return nil, errors.New("could not marshal union type FileProxyURLParam: all fields are null")
}
