// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// Method - HTTP method
type Method string

const (
	MethodGet  Method = "GET"
	MethodPost Method = "POST"
)

func (e Method) ToPointer() *Method {
	return &e
}
func (e *Method) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GET":
		fallthrough
	case "POST":
		*e = Method(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Method: %v", v)
	}
}

// ResponseType - Expected response type
type ResponseType string

const (
	ResponseTypeJSON   ResponseType = "json"
	ResponseTypeBinary ResponseType = "binary"
)

func (e ResponseType) ToPointer() *ResponseType {
	return &e
}
func (e *ResponseType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "json":
		fallthrough
	case "binary":
		*e = ResponseType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseType: %v", v)
	}
}

type FileProxyStep struct {
	// Handlebars template for the request URL
	URL string `json:"url"`
	// HTTP method
	Method Method `json:"method"`
	// Handlebars templates for request headers
	Headers map[string]string `json:"headers,omitempty"`
	// Handlebars template for the request body (POST only)
	Body *string `json:"body,omitempty"`
	// Expected response type
	ResponseType ResponseType `json:"response_type"`
}

func (f FileProxyStep) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileProxyStep) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileProxyStep) GetURL() string {
	if f == nil {
		return ""
	}
	return f.URL
}

func (f *FileProxyStep) GetMethod() Method {
	if f == nil {
		return Method("")
	}
	return f.Method
}

func (f *FileProxyStep) GetHeaders() map[string]string {
	if f == nil {
		return nil
	}
	return f.Headers
}

func (f *FileProxyStep) GetBody() *string {
	if f == nil {
		return nil
	}
	return f.Body
}

func (f *FileProxyStep) GetResponseType() ResponseType {
	if f == nil {
		return ResponseType("")
	}
	return f.ResponseType
}
