// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

type Three struct {
	// JSONata expression for transformation
	JsonataExpression string `json:"jsonataExpression"`
}

func (t Three) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Three) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Three) GetJsonataExpression() string {
	if t == nil {
		return ""
	}
	return t.JsonataExpression
}

type FileProxyURLParam2 struct {
	// Constant value (any type, stringified for URL)
	Constant any `json:"constant"`
}

func (f FileProxyURLParam2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileProxyURLParam2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileProxyURLParam2) GetConstant() any {
	if f == nil {
		return nil
	}
	return f.Constant
}

type FileProxyURLParam1 struct {
	// Source field name or JSONPath expression (if starts with $)
	Field string `json:"field"`
}

func (f FileProxyURLParam1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileProxyURLParam1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileProxyURLParam1) GetField() string {
	if f == nil {
		return ""
	}
	return f.Field
}

type FileProxyURLParamType string

const (
	FileProxyURLParamTypeFileProxyURLParam1 FileProxyURLParamType = "FileProxyUrlParam_1"
	FileProxyURLParamTypeFileProxyURLParam2 FileProxyURLParamType = "FileProxyUrlParam_2"
	FileProxyURLParamTypeThree              FileProxyURLParamType = "3"
)

// FileProxyURLParam - Parameter for file proxy URL. Exactly one of field, constant, or jsonataExpression must be set.
type FileProxyURLParam struct {
	FileProxyURLParam1 *FileProxyURLParam1 `queryParam:"inline" union:"member"`
	FileProxyURLParam2 *FileProxyURLParam2 `queryParam:"inline" union:"member"`
	Three              *Three              `queryParam:"inline" union:"member"`

	Type FileProxyURLParamType
}

func CreateFileProxyURLParamFileProxyURLParam1(fileProxyURLParam1 FileProxyURLParam1) FileProxyURLParam {
	typ := FileProxyURLParamTypeFileProxyURLParam1

	return FileProxyURLParam{
		FileProxyURLParam1: &fileProxyURLParam1,
		Type:               typ,
	}
}

func CreateFileProxyURLParamFileProxyURLParam2(fileProxyURLParam2 FileProxyURLParam2) FileProxyURLParam {
	typ := FileProxyURLParamTypeFileProxyURLParam2

	return FileProxyURLParam{
		FileProxyURLParam2: &fileProxyURLParam2,
		Type:               typ,
	}
}

func CreateFileProxyURLParamThree(three Three) FileProxyURLParam {
	typ := FileProxyURLParamTypeThree

	return FileProxyURLParam{
		Three: &three,
		Type:  typ,
	}
}

func (u *FileProxyURLParam) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var fileProxyURLParam1 FileProxyURLParam1 = FileProxyURLParam1{}
	if err := utils.UnmarshalJSON(data, &fileProxyURLParam1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FileProxyURLParamTypeFileProxyURLParam1,
			Value: &fileProxyURLParam1,
		})
	}

	var fileProxyURLParam2 FileProxyURLParam2 = FileProxyURLParam2{}
	if err := utils.UnmarshalJSON(data, &fileProxyURLParam2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FileProxyURLParamTypeFileProxyURLParam2,
			Value: &fileProxyURLParam2,
		})
	}

	var three Three = Three{}
	if err := utils.UnmarshalJSON(data, &three, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FileProxyURLParamTypeThree,
			Value: &three,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileProxyURLParam", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileProxyURLParam", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FileProxyURLParamType)
	switch best.Type {
	case FileProxyURLParamTypeFileProxyURLParam1:
		u.FileProxyURLParam1 = best.Value.(*FileProxyURLParam1)
		return nil
	case FileProxyURLParamTypeFileProxyURLParam2:
		u.FileProxyURLParam2 = best.Value.(*FileProxyURLParam2)
		return nil
	case FileProxyURLParamTypeThree:
		u.Three = best.Value.(*Three)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileProxyURLParam", string(data))
}

func (u FileProxyURLParam) MarshalJSON() ([]byte, error) {
	if u.FileProxyURLParam1 != nil {
		return utils.MarshalJSON(u.FileProxyURLParam1, "", true)
	}

	if u.FileProxyURLParam2 != nil {
		return utils.MarshalJSON(u.FileProxyURLParam2, "", true)
	}

	if u.Three != nil {
		return utils.MarshalJSON(u.Three, "", true)
	}

	return nil, errors.New("could not marshal union type FileProxyURLParam: all fields are null")
}
