// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// FileProxyUseCaseHistoryEntryType - Use case type
type FileProxyUseCaseHistoryEntryType string

const (
	FileProxyUseCaseHistoryEntryTypeFileProxy FileProxyUseCaseHistoryEntryType = "file_proxy"
)

func (e FileProxyUseCaseHistoryEntryType) ToPointer() *FileProxyUseCaseHistoryEntryType {
	return &e
}
func (e *FileProxyUseCaseHistoryEntryType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "file_proxy":
		*e = FileProxyUseCaseHistoryEntryType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FileProxyUseCaseHistoryEntryType: %v", v)
	}
}

type FileProxyUseCaseHistoryEntry struct {
	// Unique identifier for this history entry
	ID string `json:"id"`
	// Reference to the parent use case
	UseCaseID string `json:"useCaseId"`
	// Parent integration ID
	IntegrationID string `json:"integrationId"`
	// Use case name at this point in history
	Name string `json:"name"`
	// Whether the use case was enabled at this point in history
	Enabled bool `json:"enabled"`
	// Description of the change that was made at this point in history
	ChangeDescription *string `json:"change_description,omitempty"`
	// ISO-8601 timestamp when the use case was originally created
	CreatedAt time.Time `json:"created_at"`
	// ISO-8601 timestamp of this historical snapshot (before the update)
	UpdatedAt time.Time `json:"updated_at"`
	// ISO-8601 timestamp when this history entry was created
	HistoryCreatedAt time.Time `json:"history_created_at"`
	// Use case type
	Type FileProxyUseCaseHistoryEntryType `json:"type"`
	// Configuration for file_proxy use cases. Defines how to authenticate and fetch files from external document systems.
	//
	// The file proxy download URL always requires `orgId`, `integrationId`, and `useCaseId` as query parameters.
	// The `orgId` is included in the signed URL to establish organization context without requiring authentication.
	// Additional use-case-specific parameters are declared in the `params` array.
	//
	Configuration *FileProxyUseCaseConfiguration `json:"configuration,omitempty"`
}

func (f FileProxyUseCaseHistoryEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileProxyUseCaseHistoryEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileProxyUseCaseHistoryEntry) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FileProxyUseCaseHistoryEntry) GetUseCaseID() string {
	if f == nil {
		return ""
	}
	return f.UseCaseID
}

func (f *FileProxyUseCaseHistoryEntry) GetIntegrationID() string {
	if f == nil {
		return ""
	}
	return f.IntegrationID
}

func (f *FileProxyUseCaseHistoryEntry) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FileProxyUseCaseHistoryEntry) GetEnabled() bool {
	if f == nil {
		return false
	}
	return f.Enabled
}

func (f *FileProxyUseCaseHistoryEntry) GetChangeDescription() *string {
	if f == nil {
		return nil
	}
	return f.ChangeDescription
}

func (f *FileProxyUseCaseHistoryEntry) GetCreatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.CreatedAt
}

func (f *FileProxyUseCaseHistoryEntry) GetUpdatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.UpdatedAt
}

func (f *FileProxyUseCaseHistoryEntry) GetHistoryCreatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.HistoryCreatedAt
}

func (f *FileProxyUseCaseHistoryEntry) GetType() FileProxyUseCaseHistoryEntryType {
	if f == nil {
		return FileProxyUseCaseHistoryEntryType("")
	}
	return f.Type
}

func (f *FileProxyUseCaseHistoryEntry) GetConfiguration() *FileProxyUseCaseConfiguration {
	if f == nil {
		return nil
	}
	return f.Configuration
}
