// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

type FileProxyParam struct {
	// Parameter name as it appears in the query string
	Name string `json:"name"`
	// Whether this parameter is required
	Required bool `json:"required"`
	// Human-readable description of the parameter
	Description *string `json:"description,omitempty"`
}

func (f FileProxyParam) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileProxyParam) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileProxyParam) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FileProxyParam) GetRequired() bool {
	if f == nil {
		return false
	}
	return f.Required
}

func (f *FileProxyParam) GetDescription() *string {
	if f == nil {
		return nil
	}
	return f.Description
}
