// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// FileProxyUseCaseConfiguration - Configuration for file_proxy use cases. Defines how to authenticate and fetch files from external document systems.
//
// The file proxy download URL always requires `orgId`, `integrationId`, and `useCaseId` as query parameters.
// The `orgId` is included in the signed URL to establish organization context without requiring authentication.
// Additional use-case-specific parameters are declared in the `params` array.
type FileProxyUseCaseConfiguration struct {
	// Whether requests require VPC routing for IP allowlisting
	RequiresVpc *bool          `default:"false" json:"requires_vpc"`
	Auth        *FileProxyAuth `json:"auth,omitempty"`
	// Additional use-case-specific parameters expected in the download URL query string (beyond the required orgId, integrationId, useCaseId)
	Params []FileProxyParam `json:"params,omitempty"`
	// Ordered list of HTTP steps to execute to retrieve the file
	Steps    []FileProxyStep         `json:"steps"`
	Response FileProxyResponseConfig `json:"response"`
}

func (f FileProxyUseCaseConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileProxyUseCaseConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileProxyUseCaseConfiguration) GetRequiresVpc() *bool {
	if f == nil {
		return nil
	}
	return f.RequiresVpc
}

func (f *FileProxyUseCaseConfiguration) GetAuth() *FileProxyAuth {
	if f == nil {
		return nil
	}
	return f.Auth
}

func (f *FileProxyUseCaseConfiguration) GetParams() []FileProxyParam {
	if f == nil {
		return nil
	}
	return f.Params
}

func (f *FileProxyUseCaseConfiguration) GetSteps() []FileProxyStep {
	if f == nil {
		return []FileProxyStep{}
	}
	return f.Steps
}

func (f *FileProxyUseCaseConfiguration) GetResponse() FileProxyResponseConfig {
	if f == nil {
		return FileProxyResponseConfig{}
	}
	return f.Response
}
