// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GenerateTypesRequest struct {
	// npm package name
	PackageName string `json:"package_name"`
	// Package version
	Version     string  `json:"version"`
	Description *string `json:"description,omitempty"`
	// Domain standard package to extend
	DomainPackage *string `json:"domain_package,omitempty"`
	// Name of the domain UseCaseMap to extend
	DomainMapName *string `json:"domain_map_name,omitempty"`
	// Type annotations per use case slug
	Annotations map[string]TypeAnnotations `json:"annotations,omitempty"`
}

func (g *GenerateTypesRequest) GetPackageName() string {
	if g == nil {
		return ""
	}
	return g.PackageName
}

func (g *GenerateTypesRequest) GetVersion() string {
	if g == nil {
		return ""
	}
	return g.Version
}

func (g *GenerateTypesRequest) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GenerateTypesRequest) GetDomainPackage() *string {
	if g == nil {
		return nil
	}
	return g.DomainPackage
}

func (g *GenerateTypesRequest) GetDomainMapName() *string {
	if g == nil {
		return nil
	}
	return g.DomainMapName
}

func (g *GenerateTypesRequest) GetAnnotations() map[string]TypeAnnotations {
	if g == nil {
		return nil
	}
	return g.Annotations
}
