// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GenerateTypesResponse struct {
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
	// Generated file contents keyed by file path
	Files    map[string]string `json:"files"`
	Warnings []string          `json:"warnings,omitempty"`
}

func (g *GenerateTypesResponse) GetPackageName() string {
	if g == nil {
		return ""
	}
	return g.PackageName
}

func (g *GenerateTypesResponse) GetVersion() string {
	if g == nil {
		return ""
	}
	return g.Version
}

func (g *GenerateTypesResponse) GetFiles() map[string]string {
	if g == nil {
		return map[string]string{}
	}
	return g.Files
}

func (g *GenerateTypesResponse) GetWarnings() []string {
	if g == nil {
		return nil
	}
	return g.Warnings
}
