// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// GetMonitoringTimeSeriesV2RequestInterval - Time bucket interval
type GetMonitoringTimeSeriesV2RequestInterval string

const (
	GetMonitoringTimeSeriesV2RequestIntervalFivem   GetMonitoringTimeSeriesV2RequestInterval = "5m"
	GetMonitoringTimeSeriesV2RequestIntervalTenm    GetMonitoringTimeSeriesV2RequestInterval = "10m"
	GetMonitoringTimeSeriesV2RequestIntervalThirtym GetMonitoringTimeSeriesV2RequestInterval = "30m"
	GetMonitoringTimeSeriesV2RequestIntervalOneh    GetMonitoringTimeSeriesV2RequestInterval = "1h"
	GetMonitoringTimeSeriesV2RequestIntervalThreeh  GetMonitoringTimeSeriesV2RequestInterval = "3h"
	GetMonitoringTimeSeriesV2RequestIntervalOned    GetMonitoringTimeSeriesV2RequestInterval = "1d"
)

func (e GetMonitoringTimeSeriesV2RequestInterval) ToPointer() *GetMonitoringTimeSeriesV2RequestInterval {
	return &e
}
func (e *GetMonitoringTimeSeriesV2RequestInterval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "5m":
		fallthrough
	case "10m":
		fallthrough
	case "30m":
		fallthrough
	case "1h":
		fallthrough
	case "3h":
		fallthrough
	case "1d":
		*e = GetMonitoringTimeSeriesV2RequestInterval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetMonitoringTimeSeriesV2RequestInterval: %v", v)
	}
}

// GetMonitoringTimeSeriesV2RequestUseCaseType - Filter by use case type
type GetMonitoringTimeSeriesV2RequestUseCaseType string

const (
	GetMonitoringTimeSeriesV2RequestUseCaseTypeInbound     GetMonitoringTimeSeriesV2RequestUseCaseType = "inbound"
	GetMonitoringTimeSeriesV2RequestUseCaseTypeOutbound    GetMonitoringTimeSeriesV2RequestUseCaseType = "outbound"
	GetMonitoringTimeSeriesV2RequestUseCaseTypeFileProxy   GetMonitoringTimeSeriesV2RequestUseCaseType = "file_proxy"
	GetMonitoringTimeSeriesV2RequestUseCaseTypeManagedCall GetMonitoringTimeSeriesV2RequestUseCaseType = "managed_call"
	GetMonitoringTimeSeriesV2RequestUseCaseTypeSecureProxy GetMonitoringTimeSeriesV2RequestUseCaseType = "secure_proxy"
)

func (e GetMonitoringTimeSeriesV2RequestUseCaseType) ToPointer() *GetMonitoringTimeSeriesV2RequestUseCaseType {
	return &e
}
func (e *GetMonitoringTimeSeriesV2RequestUseCaseType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inbound":
		fallthrough
	case "outbound":
		fallthrough
	case "file_proxy":
		fallthrough
	case "managed_call":
		fallthrough
	case "secure_proxy":
		*e = GetMonitoringTimeSeriesV2RequestUseCaseType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetMonitoringTimeSeriesV2RequestUseCaseType: %v", v)
	}
}

type GetMonitoringTimeSeriesV2Request struct {
	// Start of the time range (required)
	FromDate time.Time `json:"from_date"`
	// End of the time range (defaults to now)
	ToDate *time.Time `json:"to_date,omitempty"`
	// Time bucket interval
	Interval GetMonitoringTimeSeriesV2RequestInterval `json:"interval"`
	// Filter by use case type
	UseCaseType *GetMonitoringTimeSeriesV2RequestUseCaseType `json:"use_case_type,omitempty"`
}

func (g GetMonitoringTimeSeriesV2Request) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMonitoringTimeSeriesV2Request) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMonitoringTimeSeriesV2Request) GetFromDate() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.FromDate
}

func (g *GetMonitoringTimeSeriesV2Request) GetToDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.ToDate
}

func (g *GetMonitoringTimeSeriesV2Request) GetInterval() GetMonitoringTimeSeriesV2RequestInterval {
	if g == nil {
		return GetMonitoringTimeSeriesV2RequestInterval("")
	}
	return g.Interval
}

func (g *GetMonitoringTimeSeriesV2Request) GetUseCaseType() *GetMonitoringTimeSeriesV2RequestUseCaseType {
	if g == nil {
		return nil
	}
	return g.UseCaseType
}

// #region class-body-getmonitoringtimeseriesv2request
// #endregion class-body-getmonitoringtimeseriesv2request
