// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// Interval - The time bucket interval for aggregation
type Interval string

const (
	IntervalFivem   Interval = "5m"
	IntervalTenm    Interval = "10m"
	IntervalThirtym Interval = "30m"
	IntervalOneh    Interval = "1h"
	IntervalThreeh  Interval = "3h"
	IntervalOned    Interval = "1d"
)

func (e Interval) ToPointer() *Interval {
	return &e
}
func (e *Interval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "5m":
		fallthrough
	case "10m":
		fallthrough
	case "30m":
		fallthrough
	case "1h":
		fallthrough
	case "3h":
		fallthrough
	case "1d":
		*e = Interval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Interval: %v", v)
	}
}

// Direction - Filter by event direction. Defaults to both.
type Direction string

const (
	DirectionInbound  Direction = "inbound"
	DirectionOutbound Direction = "outbound"
	DirectionBoth     Direction = "both"
)

func (e Direction) ToPointer() *Direction {
	return &e
}
func (e *Direction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inbound":
		fallthrough
	case "outbound":
		fallthrough
	case "both":
		*e = Direction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Direction: %v", v)
	}
}

type GetMonitoringTimeSeriesRequest struct {
	// Start date for the time series (inclusive)
	FromDate time.Time `json:"from_date"`
	// End date for the time series (inclusive). Defaults to current time if not specified.
	ToDate *time.Time `json:"to_date,omitempty"`
	// The time bucket interval for aggregation
	Interval Interval `json:"interval"`
	// Filter by event direction. Defaults to both.
	Direction *Direction `default:"both" json:"direction"`
}

func (g GetMonitoringTimeSeriesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMonitoringTimeSeriesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMonitoringTimeSeriesRequest) GetFromDate() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.FromDate
}

func (g *GetMonitoringTimeSeriesRequest) GetToDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.ToDate
}

func (g *GetMonitoringTimeSeriesRequest) GetInterval() Interval {
	if g == nil {
		return Interval("")
	}
	return g.Interval
}

func (g *GetMonitoringTimeSeriesRequest) GetDirection() *Direction {
	if g == nil {
		return nil
	}
	return g.Direction
}
