// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// InboundUseCaseHistoryEntryType - Use case type
type InboundUseCaseHistoryEntryType string

const (
	InboundUseCaseHistoryEntryTypeInbound InboundUseCaseHistoryEntryType = "inbound"
)

func (e InboundUseCaseHistoryEntryType) ToPointer() *InboundUseCaseHistoryEntryType {
	return &e
}
func (e *InboundUseCaseHistoryEntryType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inbound":
		*e = InboundUseCaseHistoryEntryType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InboundUseCaseHistoryEntryType: %v", v)
	}
}

type InboundUseCaseHistoryEntry struct {
	// Unique identifier for this history entry
	ID string `json:"id"`
	// Reference to the parent use case
	UseCaseID string `json:"useCaseId"`
	// Parent integration ID
	IntegrationID string `json:"integrationId"`
	// Use case name at this point in history
	Name string `json:"name"`
	// Whether the use case was enabled at this point in history
	Enabled bool `json:"enabled"`
	// Description of the change that was made at this point in history
	ChangeDescription *string `json:"change_description,omitempty"`
	// ISO-8601 timestamp when the use case was originally created
	CreatedAt time.Time `json:"created_at"`
	// ISO-8601 timestamp of this historical snapshot (before the update)
	UpdatedAt time.Time `json:"updated_at"`
	// ISO-8601 timestamp when this history entry was created
	HistoryCreatedAt time.Time `json:"history_created_at"`
	// Use case type
	Type InboundUseCaseHistoryEntryType `json:"type"`
	// Configuration for inbound use cases (ERP to epilot)
	Configuration *InboundIntegrationEventConfiguration `json:"configuration,omitempty"`
}

func (i InboundUseCaseHistoryEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboundUseCaseHistoryEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"id", "useCaseId", "integrationId", "name", "enabled", "created_at", "updated_at", "history_created_at", "type"}); err != nil {
		return err
	}
	return nil
}

func (o *InboundUseCaseHistoryEntry) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *InboundUseCaseHistoryEntry) GetUseCaseID() string {
	if o == nil {
		return ""
	}
	return o.UseCaseID
}

func (o *InboundUseCaseHistoryEntry) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}

func (o *InboundUseCaseHistoryEntry) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *InboundUseCaseHistoryEntry) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *InboundUseCaseHistoryEntry) GetChangeDescription() *string {
	if o == nil {
		return nil
	}
	return o.ChangeDescription
}

func (o *InboundUseCaseHistoryEntry) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *InboundUseCaseHistoryEntry) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *InboundUseCaseHistoryEntry) GetHistoryCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.HistoryCreatedAt
}

func (o *InboundUseCaseHistoryEntry) GetType() InboundUseCaseHistoryEntryType {
	if o == nil {
		return InboundUseCaseHistoryEntryType("")
	}
	return o.Type
}

func (o *InboundUseCaseHistoryEntry) GetConfiguration() *InboundIntegrationEventConfiguration {
	if o == nil {
		return nil
	}
	return o.Configuration
}
