// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

type Type string

const (
	TypeInbound Type = "inbound"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inbound":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type InboundUseCase struct {
	ID                string    `json:"id"`
	IntegrationID     string    `json:"integrationId"`
	Name              string    `json:"name"`
	Type              Type      `json:"type"`
	Enabled           bool      `json:"enabled"`
	ChangeDescription *string   `json:"change_description,omitempty"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	// Configuration for inbound use cases (ERP to epilot)
	Configuration *InboundIntegrationEventConfiguration `json:"configuration,omitempty"`
}

func (i InboundUseCase) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboundUseCase) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboundUseCase) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *InboundUseCase) GetIntegrationID() string {
	if i == nil {
		return ""
	}
	return i.IntegrationID
}

func (i *InboundUseCase) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *InboundUseCase) GetType() Type {
	if i == nil {
		return Type("")
	}
	return i.Type
}

func (i *InboundUseCase) GetEnabled() bool {
	if i == nil {
		return false
	}
	return i.Enabled
}

func (i *InboundUseCase) GetChangeDescription() *string {
	if i == nil {
		return nil
	}
	return i.ChangeDescription
}

func (i *InboundUseCase) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *InboundUseCase) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}

func (i *InboundUseCase) GetConfiguration() *InboundIntegrationEventConfiguration {
	if i == nil {
		return nil
	}
	return i.Configuration
}
