// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// IntegrationNotificationConfig - Integration monitoring notification configuration. Rides Integration.settings.notifications (camelCase) and surfaces on both v1 and v2 GET/PUT. Unknown keys are stripped server-side to stay forward-compatible with deferred (V2) rule types.
type IntegrationNotificationConfig struct {
	// Master switch for this integration's notifications.
	Enabled bool `json:"enabled"`
	// epilot user ids notified for this integration. Same-org membership and per-user notification preferences are enforced at send time (Phases 3–5), not at config-write time.
	Recipients []NotificationRecipient `json:"recipients"`
	// Delivery channel toggles. New channels added in svc-notification-api inherit here.
	DefaultChannels NotificationChannelSet `json:"defaultChannels"`
	// Integration-level use-case include-filter; absent/empty means all use cases.
	MonitoredUseCases []string `json:"monitoredUseCases,omitempty"`
	// Integration-level code scope; absent/empty resolves to ['_error_']. Accepts concrete monitoring error codes or group sentinels (_error_, _warning_, _success_, _info_, _any_, _parent_).
	MonitoredCodes []string `json:"monitoredCodes,omitempty"`
	// Enabled triggers and their params. A type MAY repeat; capped at 20 rules (enforced at the write boundary).
	Rules []NotificationRule `json:"rules"`
	// Digest schedule and content configuration.
	Digest NotificationDigestConfig `json:"digest"`
	// ISO instant; snooze all non-digest alerts until this time. `null` means not muted.
	MuteUntil *time.Time `json:"muteUntil,omitempty"`
}

func (i IntegrationNotificationConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntegrationNotificationConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IntegrationNotificationConfig) GetEnabled() bool {
	if i == nil {
		return false
	}
	return i.Enabled
}

func (i *IntegrationNotificationConfig) GetRecipients() []NotificationRecipient {
	if i == nil {
		return []NotificationRecipient{}
	}
	return i.Recipients
}

func (i *IntegrationNotificationConfig) GetDefaultChannels() NotificationChannelSet {
	if i == nil {
		return NotificationChannelSet{}
	}
	return i.DefaultChannels
}

func (i *IntegrationNotificationConfig) GetMonitoredUseCases() []string {
	if i == nil {
		return nil
	}
	return i.MonitoredUseCases
}

func (i *IntegrationNotificationConfig) GetMonitoredCodes() []string {
	if i == nil {
		return nil
	}
	return i.MonitoredCodes
}

func (i *IntegrationNotificationConfig) GetRules() []NotificationRule {
	if i == nil {
		return []NotificationRule{}
	}
	return i.Rules
}

func (i *IntegrationNotificationConfig) GetDigest() NotificationDigestConfig {
	if i == nil {
		return NotificationDigestConfig{}
	}
	return i.Digest
}

func (i *IntegrationNotificationConfig) GetMuteUntil() *time.Time {
	if i == nil {
		return nil
	}
	return i.MuteUntil
}
