// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// Version - Mapping specification version
type Version string

const (
	VersionOneDot0 Version = "1.0"
)

func (e Version) ToPointer() *Version {
	return &e
}
func (e *Version) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1.0":
		*e = Version(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Version: %v", v)
	}
}

type Mapping struct {
	// [v1.0] Object type mappings
	Objects map[string]IntegrationObjectV1 `json:"objects"`
}

func (m Mapping) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Mapping) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"objects"}); err != nil {
		return err
	}
	return nil
}

func (o *Mapping) GetObjects() map[string]IntegrationObjectV1 {
	if o == nil {
		return map[string]IntegrationObjectV1{}
	}
	return o.Objects
}

type IntegrationConfigurationV1 struct {
	// Mapping specification version
	Version *Version `default:"1.0" json:"version"`
	Mapping Mapping  `json:"mapping"`
}

func (i IntegrationConfigurationV1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntegrationConfigurationV1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"mapping"}); err != nil {
		return err
	}
	return nil
}

func (o *IntegrationConfigurationV1) GetVersion() *Version {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *IntegrationConfigurationV1) GetMapping() Mapping {
	if o == nil {
		return Mapping{}
	}
	return o.Mapping
}
