// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// IntegrationWithUseCasesIntegrationType - Type of integration. "erp" is the ERP integration with inbound/outbound use cases. "connector" is for complex proxy integrations with external APIs.
type IntegrationWithUseCasesIntegrationType string

const (
	IntegrationWithUseCasesIntegrationTypeErp       IntegrationWithUseCasesIntegrationType = "erp"
	IntegrationWithUseCasesIntegrationTypeConnector IntegrationWithUseCasesIntegrationType = "connector"
)

func (e IntegrationWithUseCasesIntegrationType) ToPointer() *IntegrationWithUseCasesIntegrationType {
	return &e
}
func (e *IntegrationWithUseCasesIntegrationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "erp":
		fallthrough
	case "connector":
		*e = IntegrationWithUseCasesIntegrationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationWithUseCasesIntegrationType: %v", v)
	}
}

// IntegrationWithUseCases - Integration with embedded use cases for atomic CRUD operations
type IntegrationWithUseCases struct {
	// Unique identifier for the integration
	ID string `json:"id"`
	// Organization ID
	OrgID string `json:"orgId"`
	// ISO-8601 timestamp when the integration was created
	CreatedAt time.Time `json:"created_at"`
	// ISO-8601 timestamp when the integration was last updated
	UpdatedAt time.Time `json:"updated_at"`
	// Integration name
	Name string `json:"name"`
	// Optional description of the integration
	Description *string `json:"description,omitempty"`
	// List of access token IDs associated with this integration
	AccessTokenIds []string `json:"access_token_ids,omitempty"`
	// List of app IDs associated with this integration
	AppIds []string `json:"app_ids,omitempty"`
	// Settings for the integration
	Settings *IntegrationSettings `json:"settings,omitempty"`
	// Type of integration. "erp" is the ERP integration with inbound/outbound use cases. "connector" is for complex proxy integrations with external APIs.
	//
	IntegrationType *IntegrationWithUseCasesIntegrationType `default:"erp" json:"integration_type"`
	// Shared configuration for connector-type integrations
	ConnectorConfig *ConnectorConfig `json:"connector_config,omitempty"`
	// If true, integration is displayed in read-only mode in the UI to discourage changes
	Protected *bool `json:"protected,omitempty"`
	// The manifest IDs associated with this integration
	Manifest          []string `json:"_manifest,omitempty"`
	EnvironmentConfig any      `json:"environment_config,omitempty"`
	UseCases          any      `json:"use_cases"`
}

func (i IntegrationWithUseCases) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntegrationWithUseCases) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IntegrationWithUseCases) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *IntegrationWithUseCases) GetOrgID() string {
	if i == nil {
		return ""
	}
	return i.OrgID
}

func (i *IntegrationWithUseCases) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *IntegrationWithUseCases) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}

func (i *IntegrationWithUseCases) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *IntegrationWithUseCases) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IntegrationWithUseCases) GetAccessTokenIds() []string {
	if i == nil {
		return nil
	}
	return i.AccessTokenIds
}

func (i *IntegrationWithUseCases) GetAppIds() []string {
	if i == nil {
		return nil
	}
	return i.AppIds
}

func (i *IntegrationWithUseCases) GetSettings() *IntegrationSettings {
	if i == nil {
		return nil
	}
	return i.Settings
}

func (i *IntegrationWithUseCases) GetIntegrationType() *IntegrationWithUseCasesIntegrationType {
	if i == nil {
		return nil
	}
	return i.IntegrationType
}

func (i *IntegrationWithUseCases) GetConnectorConfig() *ConnectorConfig {
	if i == nil {
		return nil
	}
	return i.ConnectorConfig
}

func (i *IntegrationWithUseCases) GetProtected() *bool {
	if i == nil {
		return nil
	}
	return i.Protected
}

func (i *IntegrationWithUseCases) GetManifest() []string {
	if i == nil {
		return nil
	}
	return i.Manifest
}

func (i *IntegrationWithUseCases) GetEnvironmentConfig() any {
	if i == nil {
		return nil
	}
	return i.EnvironmentConfig
}

func (i *IntegrationWithUseCases) GetUseCases() any {
	if i == nil {
		return nil
	}
	return i.UseCases
}
