// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type IntegrationAppMapping struct {
	// The integration ID this app/component is mapped to
	IntegrationID string `json:"integration_id"`
}

func (i *IntegrationAppMapping) GetIntegrationID() string {
	if i == nil {
		return ""
	}
	return i.IntegrationID
}
