// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

type IntegrationMeterReading struct {
	// JSONata expression to extract meter reading items from the event data
	JsonataExpression string                `json:"jsonataExpression"`
	Meter             MeterUniqueIdsConfig  `json:"meter"`
	MeterCounter      *MeterUniqueIdsConfig `json:"meter_counter,omitempty"`
	// Field mapping definitions for meter reading attributes
	Fields []IntegrationEntityField `json:"fields"`
}

func (i IntegrationMeterReading) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntegrationMeterReading) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"jsonataExpression", "meter", "fields"}); err != nil {
		return err
	}
	return nil
}

func (o *IntegrationMeterReading) GetJsonataExpression() string {
	if o == nil {
		return ""
	}
	return o.JsonataExpression
}

func (o *IntegrationMeterReading) GetMeter() MeterUniqueIdsConfig {
	if o == nil {
		return MeterUniqueIdsConfig{}
	}
	return o.Meter
}

func (o *IntegrationMeterReading) GetMeterCounter() *MeterUniqueIdsConfig {
	if o == nil {
		return nil
	}
	return o.MeterCounter
}

func (o *IntegrationMeterReading) GetFields() []IntegrationEntityField {
	if o == nil {
		return []IntegrationEntityField{}
	}
	return o.Fields
}
