// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type IntegrationAppMapping struct {
	// The integration ID this app/component is mapped to
	IntegrationID string `json:"integration_id"`
}

func (o *IntegrationAppMapping) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}
