// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// MonitoringTraceResponseStatus - Rolled-up status across all spans (error > warning > success > info).
type MonitoringTraceResponseStatus string

const (
	MonitoringTraceResponseStatusSuccess MonitoringTraceResponseStatus = "success"
	MonitoringTraceResponseStatusError   MonitoringTraceResponseStatus = "error"
	MonitoringTraceResponseStatusWarning MonitoringTraceResponseStatus = "warning"
	MonitoringTraceResponseStatusInfo    MonitoringTraceResponseStatus = "info"
)

func (e MonitoringTraceResponseStatus) ToPointer() *MonitoringTraceResponseStatus {
	return &e
}
func (e *MonitoringTraceResponseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "error":
		fallthrough
	case "warning":
		fallthrough
	case "info":
		*e = MonitoringTraceResponseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MonitoringTraceResponseStatus: %v", v)
	}
}

type MonitoringTraceResponse struct {
	// The trace id these spans share.
	CorrelationID string `json:"correlation_id"`
	// Rolled-up status across all spans (error > warning > success > info).
	Status MonitoringTraceResponseStatus `json:"status"`
	// created_at of the earliest span (null when the trace is empty).
	StartedAt *time.Time `json:"started_at,omitempty"`
	// created_at of the latest returned span (null when the trace is empty).
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// Number of spans RETURNED (== spans.length; capped).
	SpanCount int64 `json:"span_count"`
	// True when the trace has more spans than the cap; the returned window is the earliest spans, so ended_at/status reflect only that window.
	//
	Truncated bool `json:"truncated"`
	// All spans sharing the correlation_id, chronological. External-origin spans carry an EXTERNAL_* code; epilot spans carry an epilot code or empty (success).
	//
	Spans []MonitoringEventV2 `json:"spans"`
	// The epilot inbound event "head" (raw payload), when present.
	InboundEvent map[string]any `json:"inbound_event,omitempty"`
}

func (m MonitoringTraceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MonitoringTraceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MonitoringTraceResponse) GetCorrelationID() string {
	if m == nil {
		return ""
	}
	return m.CorrelationID
}

func (m *MonitoringTraceResponse) GetStatus() MonitoringTraceResponseStatus {
	if m == nil {
		return MonitoringTraceResponseStatus("")
	}
	return m.Status
}

func (m *MonitoringTraceResponse) GetStartedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.StartedAt
}

func (m *MonitoringTraceResponse) GetEndedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.EndedAt
}

func (m *MonitoringTraceResponse) GetSpanCount() int64 {
	if m == nil {
		return 0
	}
	return m.SpanCount
}

func (m *MonitoringTraceResponse) GetTruncated() bool {
	if m == nil {
		return false
	}
	return m.Truncated
}

func (m *MonitoringTraceResponse) GetSpans() []MonitoringEventV2 {
	if m == nil {
		return []MonitoringEventV2{}
	}
	return m.Spans
}

func (m *MonitoringTraceResponse) GetInboundEvent() map[string]any {
	if m == nil {
		return nil
	}
	return m.InboundEvent
}
