// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// MonitoringEventDirection - Sync direction
type MonitoringEventDirection string

const (
	MonitoringEventDirectionInbound  MonitoringEventDirection = "inbound"
	MonitoringEventDirectionOutbound MonitoringEventDirection = "outbound"
)

func (e MonitoringEventDirection) ToPointer() *MonitoringEventDirection {
	return &e
}
func (e *MonitoringEventDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inbound":
		fallthrough
	case "outbound":
		*e = MonitoringEventDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MonitoringEventDirection: %v", v)
	}
}

// MonitoringEventEventType - Type of event
type MonitoringEventEventType string

const (
	MonitoringEventEventTypeCreate  MonitoringEventEventType = "CREATE"
	MonitoringEventEventTypeUpdate  MonitoringEventEventType = "UPDATE"
	MonitoringEventEventTypeDelete  MonitoringEventEventType = "DELETE"
	MonitoringEventEventTypeTrigger MonitoringEventEventType = "TRIGGER"
)

func (e MonitoringEventEventType) ToPointer() *MonitoringEventEventType {
	return &e
}
func (e *MonitoringEventEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CREATE":
		fallthrough
	case "UPDATE":
		fallthrough
	case "DELETE":
		fallthrough
	case "TRIGGER":
		*e = MonitoringEventEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MonitoringEventEventType: %v", v)
	}
}

// MonitoringEventSyncType - Type of sync operation
type MonitoringEventSyncType string

const (
	MonitoringEventSyncTypeEntity       MonitoringEventSyncType = "entity"
	MonitoringEventSyncTypeMeterReading MonitoringEventSyncType = "meter_reading"
	MonitoringEventSyncTypeWebhook      MonitoringEventSyncType = "webhook"
)

func (e MonitoringEventSyncType) ToPointer() *MonitoringEventSyncType {
	return &e
}
func (e *MonitoringEventSyncType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "entity":
		fallthrough
	case "meter_reading":
		fallthrough
	case "webhook":
		*e = MonitoringEventSyncType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MonitoringEventSyncType: %v", v)
	}
}

// MonitoringEventStatus - Processing status
type MonitoringEventStatus string

const (
	MonitoringEventStatusSuccess MonitoringEventStatus = "success"
	MonitoringEventStatusError   MonitoringEventStatus = "error"
	MonitoringEventStatusSkipped MonitoringEventStatus = "skipped"
)

func (e MonitoringEventStatus) ToPointer() *MonitoringEventStatus {
	return &e
}
func (e *MonitoringEventStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "error":
		fallthrough
	case "skipped":
		*e = MonitoringEventStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MonitoringEventStatus: %v", v)
	}
}

// MonitoringEventErrorCategory - Error category (when status=error)
type MonitoringEventErrorCategory string

const (
	MonitoringEventErrorCategoryValidation      MonitoringEventErrorCategory = "validation"
	MonitoringEventErrorCategoryConfiguration   MonitoringEventErrorCategory = "configuration"
	MonitoringEventErrorCategoryDownstreamAPI   MonitoringEventErrorCategory = "downstream_api"
	MonitoringEventErrorCategoryTimeout         MonitoringEventErrorCategory = "timeout"
	MonitoringEventErrorCategorySystem          MonitoringEventErrorCategory = "system"
	MonitoringEventErrorCategoryWebhookDelivery MonitoringEventErrorCategory = "webhook_delivery"
)

func (e MonitoringEventErrorCategory) ToPointer() *MonitoringEventErrorCategory {
	return &e
}
func (e *MonitoringEventErrorCategory) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "validation":
		fallthrough
	case "configuration":
		fallthrough
	case "downstream_api":
		fallthrough
	case "timeout":
		fallthrough
	case "system":
		fallthrough
	case "webhook_delivery":
		*e = MonitoringEventErrorCategory(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MonitoringEventErrorCategory: %v", v)
	}
}

type MonitoringEvent struct {
	// Organization ID
	OrgID string `json:"org_id"`
	// Unique event identifier
	EventID string `json:"event_id"`
	// Correlation ID for tracing related events
	CorrelationID *string `json:"correlation_id,omitempty"`
	// Integration ID
	IntegrationID *string `json:"integration_id,omitempty"`
	// Use case ID
	UseCaseID *string `json:"use_case_id,omitempty"`
	// Sync direction
	Direction MonitoringEventDirection `json:"direction"`
	// Type of event
	EventType MonitoringEventEventType `json:"event_type"`
	// Type of object being synced (e.g., 'contract', 'meter')
	ObjectType string `json:"object_type"`
	// Type of sync operation
	SyncType MonitoringEventSyncType `json:"sync_type"`
	// Processing status
	Status MonitoringEventStatus `json:"status"`
	// Error code (when status=error)
	ErrorCode *string `json:"error_code,omitempty"`
	// Error message (when status=error)
	ErrorMessage *string `json:"error_message,omitempty"`
	// Error category (when status=error)
	ErrorCategory *MonitoringEventErrorCategory `json:"error_category,omitempty"`
	// Processing duration in milliseconds
	ProcessingDurationMs *int64 `json:"processing_duration_ms,omitempty"`
	// Target URL for outbound requests
	TargetURL *string `json:"target_url,omitempty"`
	// HTTP status code from target (outbound only)
	HTTPStatusCode *int64 `json:"http_status_code,omitempty"`
	// When the event was received
	ReceivedAt time.Time `json:"received_at"`
	// When processing completed
	CompletedAt time.Time `json:"completed_at"`
}

func (m MonitoringEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MonitoringEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MonitoringEvent) GetOrgID() string {
	if m == nil {
		return ""
	}
	return m.OrgID
}

func (m *MonitoringEvent) GetEventID() string {
	if m == nil {
		return ""
	}
	return m.EventID
}

func (m *MonitoringEvent) GetCorrelationID() *string {
	if m == nil {
		return nil
	}
	return m.CorrelationID
}

func (m *MonitoringEvent) GetIntegrationID() *string {
	if m == nil {
		return nil
	}
	return m.IntegrationID
}

func (m *MonitoringEvent) GetUseCaseID() *string {
	if m == nil {
		return nil
	}
	return m.UseCaseID
}

func (m *MonitoringEvent) GetDirection() MonitoringEventDirection {
	if m == nil {
		return MonitoringEventDirection("")
	}
	return m.Direction
}

func (m *MonitoringEvent) GetEventType() MonitoringEventEventType {
	if m == nil {
		return MonitoringEventEventType("")
	}
	return m.EventType
}

func (m *MonitoringEvent) GetObjectType() string {
	if m == nil {
		return ""
	}
	return m.ObjectType
}

func (m *MonitoringEvent) GetSyncType() MonitoringEventSyncType {
	if m == nil {
		return MonitoringEventSyncType("")
	}
	return m.SyncType
}

func (m *MonitoringEvent) GetStatus() MonitoringEventStatus {
	if m == nil {
		return MonitoringEventStatus("")
	}
	return m.Status
}

func (m *MonitoringEvent) GetErrorCode() *string {
	if m == nil {
		return nil
	}
	return m.ErrorCode
}

func (m *MonitoringEvent) GetErrorMessage() *string {
	if m == nil {
		return nil
	}
	return m.ErrorMessage
}

func (m *MonitoringEvent) GetErrorCategory() *MonitoringEventErrorCategory {
	if m == nil {
		return nil
	}
	return m.ErrorCategory
}

func (m *MonitoringEvent) GetProcessingDurationMs() *int64 {
	if m == nil {
		return nil
	}
	return m.ProcessingDurationMs
}

func (m *MonitoringEvent) GetTargetURL() *string {
	if m == nil {
		return nil
	}
	return m.TargetURL
}

func (m *MonitoringEvent) GetHTTPStatusCode() *int64 {
	if m == nil {
		return nil
	}
	return m.HTTPStatusCode
}

func (m *MonitoringEvent) GetReceivedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.ReceivedAt
}

func (m *MonitoringEvent) GetCompletedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CompletedAt
}
