// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NotificationHistoryResponse struct {
	// Notification-history rows, newest first.
	History []NotificationHistoryItem `json:"history"`
	// Opaque base64 cursor for the next page, or null when there are no more rows.
	NextCursor *string `json:"next_cursor,omitempty"`
}

func (n *NotificationHistoryResponse) GetHistory() []NotificationHistoryItem {
	if n == nil {
		return []NotificationHistoryItem{}
	}
	return n.History
}

func (n *NotificationHistoryResponse) GetNextCursor() *string {
	if n == nil {
		return nil
	}
	return n.NextCursor
}
