// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// NotificationRecipient - A configured recipient. Only the epilot user_id is stored.
type NotificationRecipient struct {
	// epilot user id. Same-org membership is enforced at send time (Phases 3–5), which re-validates each recipient against the integration's org before fanning out — it is not enforced at config-write time.
	UserID string `json:"user_id"`
}

func (n *NotificationRecipient) GetUserID() string {
	if n == nil {
		return ""
	}
	return n.UserID
}
