// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// OutboundPollStatus - Queue/consumer health for a poll-mode use case. Present only on use
// cases with a poll delivery mapping — webhook-only use cases are
// unaffected. Depth/age/DLQ numbers are first-page approximations.
type OutboundPollStatus struct {
	// Unconsumed messages attributable to this use case (first-page approximation)
	QueueDepth int64 `json:"queue_depth"`
	// Age of the oldest unconsumed message in seconds — null when the queue is empty
	OldestUnconsumedAgeSeconds *int64 `json:"oldest_unconsumed_age_seconds"`
	// Timestamp of the last successful poll lease — null before the first poll
	LastPollAt *time.Time `json:"last_poll_at"`
	// Timestamp of the last committed acknowledgment — null before the first ack
	LastAckAt *time.Time `json:"last_ack_at"`
	// Whether the integration's outbound stream is currently halted by a
	// blocked head message (poison_policy 'block'). Stream-level flag —
	// the same value is reported on every poll use case of the
	// integration, because the stream spans them.
	//
	Blocked bool `json:"blocked"`
	// Dead-lettered messages of this use case awaiting redrive or expiry (first-page approximation)
	DlqCount int64 `json:"dlq_count"`
}

func (o OutboundPollStatus) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutboundPollStatus) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutboundPollStatus) GetQueueDepth() int64 {
	if o == nil {
		return 0
	}
	return o.QueueDepth
}

func (o *OutboundPollStatus) GetOldestUnconsumedAgeSeconds() *int64 {
	if o == nil {
		return nil
	}
	return o.OldestUnconsumedAgeSeconds
}

func (o *OutboundPollStatus) GetLastPollAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastPollAt
}

func (o *OutboundPollStatus) GetLastAckAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastAckAt
}

func (o *OutboundPollStatus) GetBlocked() bool {
	if o == nil {
		return false
	}
	return o.Blocked
}

func (o *OutboundPollStatus) GetDlqCount() int64 {
	if o == nil {
		return 0
	}
	return o.DlqCount
}
