// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OutboundDlqListResponse struct {
	// Dead-lettered messages, oldest first
	Items []OutboundDlqMessage `json:"items"`
	// Opaque pagination token — present when more entries exist
	NextToken *string `json:"next_token,omitempty"`
}

func (o *OutboundDlqListResponse) GetItems() []OutboundDlqMessage {
	if o == nil {
		return []OutboundDlqMessage{}
	}
	return o.Items
}

func (o *OutboundDlqListResponse) GetNextToken() *string {
	if o == nil {
		return nil
	}
	return o.NextToken
}
