// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OutboundConflictType - Type of conflict:
// - 'event_disabled': Event catalog event is disabled while use case is enabled
// - 'all_webhooks_disabled': All webhooks are disabled while use case is enabled
// - 'event_enabled_while_disabled': Event is enabled while use case is disabled
// - 'webhook_enabled_while_disabled': A webhook is enabled while use case is disabled
type OutboundConflictType string

const (
	OutboundConflictTypeEventDisabled               OutboundConflictType = "event_disabled"
	OutboundConflictTypeAllWebhooksDisabled         OutboundConflictType = "all_webhooks_disabled"
	OutboundConflictTypeEventEnabledWhileDisabled   OutboundConflictType = "event_enabled_while_disabled"
	OutboundConflictTypeWebhookEnabledWhileDisabled OutboundConflictType = "webhook_enabled_while_disabled"
)

func (e OutboundConflictType) ToPointer() *OutboundConflictType {
	return &e
}
func (e *OutboundConflictType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "event_disabled":
		fallthrough
	case "all_webhooks_disabled":
		fallthrough
	case "event_enabled_while_disabled":
		fallthrough
	case "webhook_enabled_while_disabled":
		*e = OutboundConflictType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutboundConflictType: %v", v)
	}
}

type OutboundConflict struct {
	// Type of conflict:
	// - 'event_disabled': Event catalog event is disabled while use case is enabled
	// - 'all_webhooks_disabled': All webhooks are disabled while use case is enabled
	// - 'event_enabled_while_disabled': Event is enabled while use case is disabled
	// - 'webhook_enabled_while_disabled': A webhook is enabled while use case is disabled
	//
	Type OutboundConflictType `json:"type"`
	// Webhook ID (only present for webhook_enabled_while_disabled conflicts)
	WebhookID *string `json:"webhookId,omitempty"`
	// Human-readable description of the conflict
	Message string `json:"message"`
}

func (o *OutboundConflict) GetType() OutboundConflictType {
	if o == nil {
		return OutboundConflictType("")
	}
	return o.Type
}

func (o *OutboundConflict) GetWebhookID() *string {
	if o == nil {
		return nil
	}
	return o.WebhookID
}

func (o *OutboundConflict) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
