// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

type OutboundMessage struct {
	// Opaque message id (msg_…) — stable per message across leases
	ID string `json:"id"`
	// Opaque lease token (lt_…) — echo back on ack
	LeaseToken string `json:"lease_token"`
	// The poll-mode use case that produced this message
	UseCaseID string `json:"use_case_id"`
	// Standardized event name (e.g. contract.updated)
	EventName string `json:"event_name"`
	// Unique id of the originating event
	EventID string `json:"event_id"`
	// Ordering group — messages sharing a group are strictly ordered,
	// distinct groups are independent. Constant "0" in v1.
	//
	Group string `json:"group"`
	// The raw standardized event-catalog event, always inlined as-is
	Payload map[string]any `json:"payload"`
	// When the message was enqueued
	EnqueuedAt time.Time `json:"enqueued_at"`
}

func (o OutboundMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutboundMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutboundMessage) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OutboundMessage) GetLeaseToken() string {
	if o == nil {
		return ""
	}
	return o.LeaseToken
}

func (o *OutboundMessage) GetUseCaseID() string {
	if o == nil {
		return ""
	}
	return o.UseCaseID
}

func (o *OutboundMessage) GetEventName() string {
	if o == nil {
		return ""
	}
	return o.EventName
}

func (o *OutboundMessage) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}

func (o *OutboundMessage) GetGroup() string {
	if o == nil {
		return ""
	}
	return o.Group
}

func (o *OutboundMessage) GetPayload() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Payload
}

func (o *OutboundMessage) GetEnqueuedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.EnqueuedAt
}
