// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// OutboundMonitoringEventStatus - Delivery status
type OutboundMonitoringEventStatus string

const (
	OutboundMonitoringEventStatusSucceeded OutboundMonitoringEventStatus = "succeeded"
	OutboundMonitoringEventStatusFailed    OutboundMonitoringEventStatus = "failed"
	OutboundMonitoringEventStatusPending   OutboundMonitoringEventStatus = "pending"
)

func (e OutboundMonitoringEventStatus) ToPointer() *OutboundMonitoringEventStatus {
	return &e
}
func (e *OutboundMonitoringEventStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "succeeded":
		fallthrough
	case "failed":
		fallthrough
	case "pending":
		*e = OutboundMonitoringEventStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutboundMonitoringEventStatus: %v", v)
	}
}

type OutboundMonitoringEvent struct {
	// Organization ID
	OrgID string `json:"org_id"`
	// Unique event identifier
	EventID string `json:"event_id"`
	// Event name (event_catalog_event)
	EventName string `json:"event_name"`
	// Delivery status
	Status OutboundMonitoringEventStatus `json:"status"`
	// Target URL
	URL *string `json:"url,omitempty"`
	// HTTP method used (e.g., POST)
	HTTPMethod *string `json:"http_method,omitempty"`
	// HTTP response details (status_code, message, headers)
	HTTPResponse map[string]any `json:"http_response,omitempty"`
	// Webhook configuration ID
	WebhookConfigID *string `json:"webhook_config_id,omitempty"`
	// Additional metadata (webhook_id, organization details, correlation_id, etc.)
	Metadata map[string]any `json:"metadata,omitempty"`
	// Execution context (execution_arn, state_machine_arn, etc.)
	ExecutionContext map[string]any `json:"execution_context,omitempty"`
	// Payload that was sent
	Payload map[string]any `json:"payload,omitempty"`
	// When the event was created
	CreatedAt time.Time `json:"created_at"`
	// When the event was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

func (o OutboundMonitoringEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutboundMonitoringEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutboundMonitoringEvent) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

func (o *OutboundMonitoringEvent) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}

func (o *OutboundMonitoringEvent) GetEventName() string {
	if o == nil {
		return ""
	}
	return o.EventName
}

func (o *OutboundMonitoringEvent) GetStatus() OutboundMonitoringEventStatus {
	if o == nil {
		return OutboundMonitoringEventStatus("")
	}
	return o.Status
}

func (o *OutboundMonitoringEvent) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *OutboundMonitoringEvent) GetHTTPMethod() *string {
	if o == nil {
		return nil
	}
	return o.HTTPMethod
}

func (o *OutboundMonitoringEvent) GetHTTPResponse() map[string]any {
	if o == nil {
		return nil
	}
	return o.HTTPResponse
}

func (o *OutboundMonitoringEvent) GetWebhookConfigID() *string {
	if o == nil {
		return nil
	}
	return o.WebhookConfigID
}

func (o *OutboundMonitoringEvent) GetMetadata() map[string]any {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *OutboundMonitoringEvent) GetExecutionContext() map[string]any {
	if o == nil {
		return nil
	}
	return o.ExecutionContext
}

func (o *OutboundMonitoringEvent) GetPayload() map[string]any {
	if o == nil {
		return nil
	}
	return o.Payload
}

func (o *OutboundMonitoringEvent) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OutboundMonitoringEvent) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
