// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// OutboundIntegrationEventConfiguration - Configuration for outbound use cases. Defines the event that triggers the flow and the webhook mappings.
type OutboundIntegrationEventConfiguration struct {
	// The Event Catalog event name that triggers this outbound flow
	EventCatalogEvent string `json:"event_catalog_event"`
	// List of mappings that transform and deliver the event
	Mappings []OutboundMapping `json:"mappings"`
}

func (o OutboundIntegrationEventConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutboundIntegrationEventConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutboundIntegrationEventConfiguration) GetEventCatalogEvent() string {
	if o == nil {
		return ""
	}
	return o.EventCatalogEvent
}

func (o *OutboundIntegrationEventConfiguration) GetMappings() []OutboundMapping {
	if o == nil {
		return []OutboundMapping{}
	}
	return o.Mappings
}
