// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

type OutboundDlqMessage struct {
	// Opaque message id (msg_…) of the dead-lettered message
	ID string `json:"id"`
	// The poll-mode use case that produced this message
	UseCaseID string `json:"use_case_id"`
	// Standardized event name (e.g. contract.updated)
	EventName string `json:"event_name"`
	// Unique id of the originating event
	EventID string `json:"event_id"`
	// When the message was originally enqueued
	EnqueuedAt *time.Time `json:"enqueued_at,omitempty"`
	// When the message was dead-lettered
	DeadLetteredAt time.Time `json:"dead_lettered_at"`
	// Delivery attempts at the moment the message was dead-lettered
	DeliveryAttempts int64 `json:"delivery_attempts"`
	// Why the message was dead-lettered (policy or operator reason)
	Reason *string `json:"reason,omitempty"`
	// When the DLQ entry expires (retention window re-armed at dead-letter time)
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

func (o OutboundDlqMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutboundDlqMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutboundDlqMessage) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OutboundDlqMessage) GetUseCaseID() string {
	if o == nil {
		return ""
	}
	return o.UseCaseID
}

func (o *OutboundDlqMessage) GetEventName() string {
	if o == nil {
		return ""
	}
	return o.EventName
}

func (o *OutboundDlqMessage) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}

func (o *OutboundDlqMessage) GetEnqueuedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.EnqueuedAt
}

func (o *OutboundDlqMessage) GetDeadLetteredAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.DeadLetteredAt
}

func (o *OutboundDlqMessage) GetDeliveryAttempts() int64 {
	if o == nil {
		return 0
	}
	return o.DeliveryAttempts
}

func (o *OutboundDlqMessage) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}

func (o *OutboundDlqMessage) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}
