// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OutboundUseCaseStatusStatus - Overall status of the use case:
// - 'ok': Use case is enabled and all dependencies are properly configured
// - 'conflict': Use case has configuration issues (disabled events/webhooks while enabled)
// - 'disabled': Use case is disabled
type OutboundUseCaseStatusStatus string

const (
	OutboundUseCaseStatusStatusOk       OutboundUseCaseStatusStatus = "ok"
	OutboundUseCaseStatusStatusConflict OutboundUseCaseStatusStatus = "conflict"
	OutboundUseCaseStatusStatusDisabled OutboundUseCaseStatusStatus = "disabled"
)

func (e OutboundUseCaseStatusStatus) ToPointer() *OutboundUseCaseStatusStatus {
	return &e
}
func (e *OutboundUseCaseStatusStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ok":
		fallthrough
	case "conflict":
		fallthrough
	case "disabled":
		*e = OutboundUseCaseStatusStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutboundUseCaseStatusStatus: %v", v)
	}
}

type OutboundUseCaseStatus struct {
	// Unique identifier for the use case
	UseCaseID string `json:"useCaseId"`
	// Human-readable name of the use case
	Name string `json:"name"`
	// Whether the use case is enabled
	UseCaseEnabled bool `json:"useCaseEnabled"`
	// The Event Catalog event name that triggers this outbound flow
	EventCatalogEvent *string `json:"eventCatalogEvent,omitempty"`
	// Whether the event is enabled in Event Catalog. Null if the API is unreachable.
	EventEnabled *bool           `json:"eventEnabled,omitempty"`
	Webhooks     []WebhookStatus `json:"webhooks,omitempty"`
	// Overall status of the use case:
	// - 'ok': Use case is enabled and all dependencies are properly configured
	// - 'conflict': Use case has configuration issues (disabled events/webhooks while enabled)
	// - 'disabled': Use case is disabled
	//
	Status OutboundUseCaseStatusStatus `json:"status"`
	// List of detected conflicts, if any
	Conflicts []OutboundConflict `json:"conflicts,omitempty"`
}

func (o *OutboundUseCaseStatus) GetUseCaseID() string {
	if o == nil {
		return ""
	}
	return o.UseCaseID
}

func (o *OutboundUseCaseStatus) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OutboundUseCaseStatus) GetUseCaseEnabled() bool {
	if o == nil {
		return false
	}
	return o.UseCaseEnabled
}

func (o *OutboundUseCaseStatus) GetEventCatalogEvent() *string {
	if o == nil {
		return nil
	}
	return o.EventCatalogEvent
}

func (o *OutboundUseCaseStatus) GetEventEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.EventEnabled
}

func (o *OutboundUseCaseStatus) GetWebhooks() []WebhookStatus {
	if o == nil {
		return nil
	}
	return o.Webhooks
}

func (o *OutboundUseCaseStatus) GetStatus() OutboundUseCaseStatusStatus {
	if o == nil {
		return OutboundUseCaseStatusStatus("")
	}
	return o.Status
}

func (o *OutboundUseCaseStatus) GetConflicts() []OutboundConflict {
	if o == nil {
		return nil
	}
	return o.Conflicts
}
