// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PortalOrigin - Origin/type of an epilot portal configuration.
type PortalOrigin string

const (
	PortalOriginEndCustomerPortal PortalOrigin = "END_CUSTOMER_PORTAL"
	PortalOriginInstallerPortal   PortalOrigin = "INSTALLER_PORTAL"
	PortalOriginB2BPortal         PortalOrigin = "B2B_PORTAL"
	PortalOriginAdditionalPortal  PortalOrigin = "ADDITIONAL_PORTAL"
)

func (e PortalOrigin) ToPointer() *PortalOrigin {
	return &e
}
func (e *PortalOrigin) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "END_CUSTOMER_PORTAL":
		fallthrough
	case "INSTALLER_PORTAL":
		fallthrough
	case "B2B_PORTAL":
		fallthrough
	case "ADDITIONAL_PORTAL":
		*e = PortalOrigin(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PortalOrigin: %v", v)
	}
}
