// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

type PortalRefConfigSelect string

const (
	PortalRefConfigSelectSingle PortalRefConfigSelect = "single"
	PortalRefConfigSelectAll    PortalRefConfigSelect = "all"
)

func (e PortalRefConfigSelect) ToPointer() *PortalRefConfigSelect {
	return &e
}
func (e *PortalRefConfigSelect) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "single":
		fallthrough
	case "all":
		*e = PortalRefConfigSelect(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PortalRefConfigSelect: %v", v)
	}
}

// PortalRefConfigReturn - Evaluate the sibling `jsonataExpression` against the matched portal(s). With `select: "single"` the input is the matched PortalConfig object; with `select: "all"` it is the full filtered+sorted array.
type PortalRefConfigReturn string

const (
	PortalRefConfigReturnJsonata PortalRefConfigReturn = "jsonata"
)

func (e PortalRefConfigReturn) ToPointer() *PortalRefConfigReturn {
	return &e
}
func (e *PortalRefConfigReturn) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "jsonata":
		*e = PortalRefConfigReturn(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PortalRefConfigReturn: %v", v)
	}
}

type PortalRefConfig2 struct {
	// Filter applied to the org's portal configurations before selection. All filters default to "match any" except `enabled` (default `true`) and `is_dummy` (default `false`). Set `enabled` or `is_dummy` to `null` to opt out of the default.
	//
	Filter *PortalRefFilter       `json:"filter,omitempty"`
	Select *PortalRefConfigSelect `default:"single" json:"select"`
	// Evaluate the sibling `jsonataExpression` against the matched portal(s). With `select: "single"` the input is the matched PortalConfig object; with `select: "all"` it is the full filtered+sorted array.
	//
	Return PortalRefConfigReturn `json:"return"`
	// JSONata expression evaluated against the matched portal(s).
	JsonataExpression string `json:"jsonataExpression"`
}

func (p PortalRefConfig2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PortalRefConfig2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PortalRefConfig2) GetFilter() *PortalRefFilter {
	if p == nil {
		return nil
	}
	return p.Filter
}

func (p *PortalRefConfig2) GetSelect() *PortalRefConfigSelect {
	if p == nil {
		return nil
	}
	return p.Select
}

func (p *PortalRefConfig2) GetReturn() PortalRefConfigReturn {
	if p == nil {
		return PortalRefConfigReturn("")
	}
	return p.Return
}

func (p *PortalRefConfig2) GetJsonataExpression() string {
	if p == nil {
		return ""
	}
	return p.JsonataExpression
}

// #region class-body-portalrefconfig2
// #endregion class-body-portalrefconfig2

// Select - `single` returns one literal value (the oldest matching portal); `all` returns an array of literal values (0, 1, or many).
type Select string

const (
	SelectSingle Select = "single"
	SelectAll    Select = "all"
)

func (e Select) ToPointer() *Select {
	return &e
}
func (e *Select) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "single":
		fallthrough
	case "all":
		*e = Select(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Select: %v", v)
	}
}

// Return - Which portal field to emit.
type Return string

const (
	ReturnPortalID Return = "portal_id"
	ReturnOrigin   Return = "origin"
	ReturnDomain   Return = "domain"
	ReturnName     Return = "name"
)

func (e Return) ToPointer() *Return {
	return &e
}
func (e *Return) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "portal_id":
		fallthrough
	case "origin":
		fallthrough
	case "domain":
		fallthrough
	case "name":
		*e = Return(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Return: %v", v)
	}
}

type PortalRefConfig1 struct {
	// Filter applied to the org's portal configurations before selection. All filters default to "match any" except `enabled` (default `true`) and `is_dummy` (default `false`). Set `enabled` or `is_dummy` to `null` to opt out of the default.
	//
	Filter *PortalRefFilter `json:"filter,omitempty"`
	// `single` returns one literal value (the oldest matching portal); `all` returns an array of literal values (0, 1, or many).
	//
	Select *Select `default:"single" json:"select"`
	// Which portal field to emit.
	Return *Return `default:"portal_id" json:"return"`
}

func (p PortalRefConfig1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PortalRefConfig1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PortalRefConfig1) GetFilter() *PortalRefFilter {
	if p == nil {
		return nil
	}
	return p.Filter
}

func (p *PortalRefConfig1) GetSelect() *Select {
	if p == nil {
		return nil
	}
	return p.Select
}

func (p *PortalRefConfig1) GetReturn() *Return {
	if p == nil {
		return nil
	}
	return p.Return
}

// #region class-body-portalrefconfig1
// #endregion class-body-portalrefconfig1

type PortalRefConfigType string

const (
	PortalRefConfigTypePortalRefConfig1 PortalRefConfigType = "PortalRefConfig_1"
	PortalRefConfigTypePortalRefConfig2 PortalRefConfigType = "PortalRefConfig_2"
)

// PortalRefConfig - Resolves to a property of one of the calling organization's epilot portal configurations at runtime, replacing hard-coded environment-specific portal UUIDs in inbound mappings. Matched portals are sorted ascending by `(_created_at, portal_id)`; portals without `_created_at` sort first (treated as oldest). When `select: "single"` matches more than one portal, the resolver still returns the oldest match and emits a `PORTAL_REF_AMBIGUOUS` warning.
type PortalRefConfig struct {
	PortalRefConfig1 *PortalRefConfig1 `queryParam:"inline" union:"member"`
	PortalRefConfig2 *PortalRefConfig2 `queryParam:"inline" union:"member"`

	Type PortalRefConfigType
}

func CreatePortalRefConfigPortalRefConfig1(portalRefConfig1 PortalRefConfig1) PortalRefConfig {
	typ := PortalRefConfigTypePortalRefConfig1

	return PortalRefConfig{
		PortalRefConfig1: &portalRefConfig1,
		Type:             typ,
	}
}

func CreatePortalRefConfigPortalRefConfig2(portalRefConfig2 PortalRefConfig2) PortalRefConfig {
	typ := PortalRefConfigTypePortalRefConfig2

	return PortalRefConfig{
		PortalRefConfig2: &portalRefConfig2,
		Type:             typ,
	}
}

func (u *PortalRefConfig) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var portalRefConfig1 PortalRefConfig1 = PortalRefConfig1{}
	if err := utils.UnmarshalJSON(data, &portalRefConfig1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PortalRefConfigTypePortalRefConfig1,
			Value: &portalRefConfig1,
		})
	}

	var portalRefConfig2 PortalRefConfig2 = PortalRefConfig2{}
	if err := utils.UnmarshalJSON(data, &portalRefConfig2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PortalRefConfigTypePortalRefConfig2,
			Value: &portalRefConfig2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PortalRefConfig", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PortalRefConfig", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(PortalRefConfigType)
	switch best.Type {
	case PortalRefConfigTypePortalRefConfig1:
		u.PortalRefConfig1 = best.Value.(*PortalRefConfig1)
		return nil
	case PortalRefConfigTypePortalRefConfig2:
		u.PortalRefConfig2 = best.Value.(*PortalRefConfig2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PortalRefConfig", string(data))
}

func (u PortalRefConfig) MarshalJSON() ([]byte, error) {
	if u.PortalRefConfig1 != nil {
		return utils.MarshalJSON(u.PortalRefConfig1, "", true)
	}

	if u.PortalRefConfig2 != nil {
		return utils.MarshalJSON(u.PortalRefConfig2, "", true)
	}

	return nil, errors.New("could not marshal union type PortalRefConfig: all fields are null")
}
