// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// QueryAccessLogsRequestMethod - Filter by HTTP method
type QueryAccessLogsRequestMethod string

const (
	QueryAccessLogsRequestMethodGet     QueryAccessLogsRequestMethod = "GET"
	QueryAccessLogsRequestMethodPost    QueryAccessLogsRequestMethod = "POST"
	QueryAccessLogsRequestMethodPut     QueryAccessLogsRequestMethod = "PUT"
	QueryAccessLogsRequestMethodPatch   QueryAccessLogsRequestMethod = "PATCH"
	QueryAccessLogsRequestMethodDelete  QueryAccessLogsRequestMethod = "DELETE"
	QueryAccessLogsRequestMethodOptions QueryAccessLogsRequestMethod = "OPTIONS"
	QueryAccessLogsRequestMethodHead    QueryAccessLogsRequestMethod = "HEAD"
)

func (e QueryAccessLogsRequestMethod) ToPointer() *QueryAccessLogsRequestMethod {
	return &e
}
func (e *QueryAccessLogsRequestMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GET":
		fallthrough
	case "POST":
		fallthrough
	case "PUT":
		fallthrough
	case "PATCH":
		fallthrough
	case "DELETE":
		fallthrough
	case "OPTIONS":
		fallthrough
	case "HEAD":
		*e = QueryAccessLogsRequestMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryAccessLogsRequestMethod: %v", v)
	}
}

// QueryAccessLogsRequestCursor - Cursor for pagination (infinite scroll)
type QueryAccessLogsRequestCursor struct {
	// Timestamp from the last log entry in the previous page
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Request ID from the last log entry in the previous page
	RequestID *string `json:"request_id,omitempty"`
}

func (q QueryAccessLogsRequestCursor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAccessLogsRequestCursor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryAccessLogsRequestCursor) GetTimestamp() *time.Time {
	if q == nil {
		return nil
	}
	return q.Timestamp
}

func (q *QueryAccessLogsRequestCursor) GetRequestID() *string {
	if q == nil {
		return nil
	}
	return q.RequestID
}

type QueryAccessLogsRequest struct {
	// Filter by a specific access token ID (e.g., 'api_5ZugdRXasLfWBypHi93Fk').
	// Must be one of the access_token_ids linked to the integration.
	// If omitted, returns logs for all access tokens linked to the integration.
	//
	TokenID *string `json:"token_id,omitempty"`
	// Filter by service name (e.g., 'entity', 'metering', 'submission-api')
	Service *string `json:"service,omitempty"`
	// Filter by HTTP method
	Method *QueryAccessLogsRequestMethod `json:"method,omitempty"`
	// Filter by request path (partial match)
	Path *string `json:"path,omitempty"`
	// Filter by HTTP status code
	Status *int64 `json:"status,omitempty"`
	// Filter logs from this date (inclusive)
	FromDate *time.Time `json:"from_date,omitempty"`
	// Filter logs until this date (inclusive)
	ToDate *time.Time `json:"to_date,omitempty"`
	// Maximum number of results to return
	Limit *int64 `default:"50" json:"limit"`
	// Cursor for pagination (infinite scroll)
	Cursor *QueryAccessLogsRequestCursor `json:"cursor,omitempty"`
}

func (q QueryAccessLogsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAccessLogsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryAccessLogsRequest) GetTokenID() *string {
	if q == nil {
		return nil
	}
	return q.TokenID
}

func (q *QueryAccessLogsRequest) GetService() *string {
	if q == nil {
		return nil
	}
	return q.Service
}

func (q *QueryAccessLogsRequest) GetMethod() *QueryAccessLogsRequestMethod {
	if q == nil {
		return nil
	}
	return q.Method
}

func (q *QueryAccessLogsRequest) GetPath() *string {
	if q == nil {
		return nil
	}
	return q.Path
}

func (q *QueryAccessLogsRequest) GetStatus() *int64 {
	if q == nil {
		return nil
	}
	return q.Status
}

func (q *QueryAccessLogsRequest) GetFromDate() *time.Time {
	if q == nil {
		return nil
	}
	return q.FromDate
}

func (q *QueryAccessLogsRequest) GetToDate() *time.Time {
	if q == nil {
		return nil
	}
	return q.ToDate
}

func (q *QueryAccessLogsRequest) GetLimit() *int64 {
	if q == nil {
		return nil
	}
	return q.Limit
}

func (q *QueryAccessLogsRequest) GetCursor() *QueryAccessLogsRequestCursor {
	if q == nil {
		return nil
	}
	return q.Cursor
}
