// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
	"time"
)

// QueryEventsRequestEventType - Filter by event type
type QueryEventsRequestEventType string

const (
	QueryEventsRequestEventTypeCreate QueryEventsRequestEventType = "CREATE"
	QueryEventsRequestEventTypeUpdate QueryEventsRequestEventType = "UPDATE"
	QueryEventsRequestEventTypeDelete QueryEventsRequestEventType = "DELETE"
)

func (e QueryEventsRequestEventType) ToPointer() *QueryEventsRequestEventType {
	return &e
}
func (e *QueryEventsRequestEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CREATE":
		fallthrough
	case "UPDATE":
		fallthrough
	case "DELETE":
		*e = QueryEventsRequestEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryEventsRequestEventType: %v", v)
	}
}

// Cursor for pagination. Use the next_cursor from the previous response to get the next page.
type Cursor struct {
	// Timestamp from the last event in the previous page
	EventTime *time.Time `json:"event_time,omitempty"`
	// Event ID from the last event in the previous page
	EventID *string `json:"event_id,omitempty"`
}

func (c Cursor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Cursor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Cursor) GetEventTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EventTime
}

func (o *Cursor) GetEventID() *string {
	if o == nil {
		return nil
	}
	return o.EventID
}

type QueryEventsRequest struct {
	// Filter by event ID
	EventID *string `json:"event_id,omitempty"`
	// Filter by event type
	EventType *QueryEventsRequestEventType `json:"event_type,omitempty"`
	// Filter by correlation ID
	CorrelationID *string `json:"correlation_id,omitempty"`
	// Filter by object type
	ObjectType *string `json:"object_type,omitempty"`
	// Maximum number of results to return
	Limit *int64 `default:"25" json:"limit"`
	// Cursor for pagination. Use the next_cursor from the previous response to get the next page.
	Cursor *Cursor `json:"cursor,omitempty"`
}

func (q QueryEventsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryEventsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *QueryEventsRequest) GetEventID() *string {
	if o == nil {
		return nil
	}
	return o.EventID
}

func (o *QueryEventsRequest) GetEventType() *QueryEventsRequestEventType {
	if o == nil {
		return nil
	}
	return o.EventType
}

func (o *QueryEventsRequest) GetCorrelationID() *string {
	if o == nil {
		return nil
	}
	return o.CorrelationID
}

func (o *QueryEventsRequest) GetObjectType() *string {
	if o == nil {
		return nil
	}
	return o.ObjectType
}

func (o *QueryEventsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *QueryEventsRequest) GetCursor() *Cursor {
	if o == nil {
		return nil
	}
	return o.Cursor
}
