// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// RelationRefItemConfig - Configuration for a single relation reference item
type RelationRefItemConfig struct {
	// Schema of the related entity (e.g., "contact")
	EntitySchema string `json:"entity_schema"`
	// Unique identifier mappings for the related entity
	UniqueIds []RelationUniqueIDField `json:"unique_ids"`
	// Attribute path on the related entity (e.g., "address")
	Path string `json:"path"`
	// Configuration for the value to set on the related entity's attribute
	Value RelationRefValueConfig `json:"value"`
}

func (r RelationRefItemConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RelationRefItemConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"entity_schema", "unique_ids", "path", "value"}); err != nil {
		return err
	}
	return nil
}

func (o *RelationRefItemConfig) GetEntitySchema() string {
	if o == nil {
		return ""
	}
	return o.EntitySchema
}

func (o *RelationRefItemConfig) GetUniqueIds() []RelationUniqueIDField {
	if o == nil {
		return []RelationUniqueIDField{}
	}
	return o.UniqueIds
}

func (o *RelationRefItemConfig) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *RelationRefItemConfig) GetValue() RelationRefValueConfig {
	if o == nil {
		return RelationRefValueConfig{}
	}
	return o.Value
}
