// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// RelationRefsConfigOperation - Relation reference operation:
// - '_set': Replace all existing relation_refs with the specified items
// - '_append': Add new unique items to existing relation_refs (deduplicates by entity_id + _id)
// - '_append_all': Add all items to existing relation_refs (no deduplication, allows duplicates)
type RelationRefsConfigOperation string

const (
	RelationRefsConfigOperationSet       RelationRefsConfigOperation = "_set"
	RelationRefsConfigOperationAppend    RelationRefsConfigOperation = "_append"
	RelationRefsConfigOperationAppendAll RelationRefsConfigOperation = "_append_all"
)

func (e RelationRefsConfigOperation) ToPointer() *RelationRefsConfigOperation {
	return &e
}
func (e *RelationRefsConfigOperation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "_set":
		fallthrough
	case "_append":
		fallthrough
	case "_append_all":
		*e = RelationRefsConfigOperation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RelationRefsConfigOperation: %v", v)
	}
}

// RelationRefsConfig - Configuration for relation references ($relation_ref).
// Relation references link to a specific item within a repeatable attribute on a related entity.
// Common use case: referencing a specific address within a contact's address list.
type RelationRefsConfig struct {
	// Relation reference operation:
	// - '_set': Replace all existing relation_refs with the specified items
	// - '_append': Add new unique items to existing relation_refs (deduplicates by entity_id + _id)
	// - '_append_all': Add all items to existing relation_refs (no deduplication, allows duplicates)
	//
	Operation RelationRefsConfigOperation `json:"operation"`
	// Array of relation reference item configurations
	Items []RelationRefItemConfig `json:"items,omitempty"`
	// JSONata expression that returns relation_ref items array (alternative to 'items')
	JsonataExpression *string `json:"jsonataExpression,omitempty"`
}

func (r RelationRefsConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RelationRefsConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RelationRefsConfig) GetOperation() RelationRefsConfigOperation {
	if r == nil {
		return RelationRefsConfigOperation("")
	}
	return r.Operation
}

func (r *RelationRefsConfig) GetItems() []RelationRefItemConfig {
	if r == nil {
		return nil
	}
	return r.Items
}

func (r *RelationRefsConfig) GetJsonataExpression() *string {
	if r == nil {
		return nil
	}
	return r.JsonataExpression
}
