// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// RelationRefValueConfigOperation - Operation for the attribute value:
// - '_set': Replace the attribute value
// - '_append': Add new unique items (deduplicates)
// - '_append_all': Add all items (no deduplication)
type RelationRefValueConfigOperation string

const (
	RelationRefValueConfigOperationSet       RelationRefValueConfigOperation = "_set"
	RelationRefValueConfigOperationAppend    RelationRefValueConfigOperation = "_append"
	RelationRefValueConfigOperationAppendAll RelationRefValueConfigOperation = "_append_all"
)

func (e RelationRefValueConfigOperation) ToPointer() *RelationRefValueConfigOperation {
	return &e
}
func (e *RelationRefValueConfigOperation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "_set":
		fallthrough
	case "_append":
		fallthrough
	case "_append_all":
		*e = RelationRefValueConfigOperation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RelationRefValueConfigOperation: %v", v)
	}
}

// RelationRefValueConfig - Configuration for the value to set on the related entity's attribute
type RelationRefValueConfig struct {
	// Target attribute name on the related entity
	Attribute string `json:"attribute"`
	// Operation for the attribute value:
	// - '_set': Replace the attribute value
	// - '_append': Add new unique items (deduplicates)
	// - '_append_all': Add all items (no deduplication)
	//
	Operation *RelationRefValueConfigOperation `json:"operation,omitempty"`
	// Source field name from the event data
	Field *string `json:"field,omitempty"`
	// JSONata expression to compute the value
	JsonataExpression *string `json:"jsonataExpression,omitempty"`
	// Constant value (any type)
	Constant any `json:"constant,omitempty"`
}

func (r RelationRefValueConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RelationRefValueConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"attribute"}); err != nil {
		return err
	}
	return nil
}

func (o *RelationRefValueConfig) GetAttribute() string {
	if o == nil {
		return ""
	}
	return o.Attribute
}

func (o *RelationRefValueConfig) GetOperation() *RelationRefValueConfigOperation {
	if o == nil {
		return nil
	}
	return o.Operation
}

func (o *RelationRefValueConfig) GetField() *string {
	if o == nil {
		return nil
	}
	return o.Field
}

func (o *RelationRefValueConfig) GetJsonataExpression() *string {
	if o == nil {
		return nil
	}
	return o.JsonataExpression
}

func (o *RelationRefValueConfig) GetConstant() any {
	if o == nil {
		return nil
	}
	return o.Constant
}
