// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReplayEventsRequest struct {
	// List of event IDs to replay. Maximum 100 events per request.
	EventIds []string `json:"event_ids"`
}

func (r *ReplayEventsRequest) GetEventIds() []string {
	if r == nil {
		return []string{}
	}
	return r.EventIds
}
