// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RuleBaselineBucket struct {
	// Day of week, 1=Monday … 7=Sunday.
	Dow int64 `json:"dow"`
	// Hour of day, 0 … 23 (UTC).
	Hour   int64   `json:"hour"`
	Median float64 `json:"median"`
	Mad    float64 `json:"mad"`
}

func (r *RuleBaselineBucket) GetDow() int64 {
	if r == nil {
		return 0
	}
	return r.Dow
}

func (r *RuleBaselineBucket) GetHour() int64 {
	if r == nil {
		return 0
	}
	return r.Hour
}

func (r *RuleBaselineBucket) GetMedian() float64 {
	if r == nil {
		return 0.0
	}
	return r.Median
}

func (r *RuleBaselineBucket) GetMad() float64 {
	if r == nil {
		return 0.0
	}
	return r.Mad
}
