// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SecureProxyWhitelistUpdate - Partial update for a secure_proxy whitelist. At least one of
// `allowed_domains` or `allowed_ips` must be provided.
//
// Per-field semantics:
//   - **omitted** — the field is not modified; the stored value is preserved.
//   - **non-empty array** — the stored value is replaced with the supplied list.
//   - **empty array (`[]`)** — the list is cleared (stored as `[]`). This is the
//     canonical way to remove all entries from a list. `null` is not accepted.
type SecureProxyWhitelistUpdate struct {
	// Exact domain ("api.example.com") or wildcard prefix ("*.example.com").
	// Wildcards must have at least 2 labels in the suffix.
	// Pass `[]` to clear all allowed domains.
	//
	AllowedDomains []string `json:"allowed_domains,omitempty"`
	// CIDR-notation IP ranges, e.g. "10.0.0.0/24".
	// Pass `[]` to clear all allowed IPs.
	//
	AllowedIps []string `json:"allowed_ips,omitempty"`
}

func (s *SecureProxyWhitelistUpdate) GetAllowedDomains() []string {
	if s == nil {
		return nil
	}
	return s.AllowedDomains
}

func (s *SecureProxyWhitelistUpdate) GetAllowedIps() []string {
	if s == nil {
		return nil
	}
	return s.AllowedIps
}
