// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SecureProxySummaryVpcMode string

const (
	SecureProxySummaryVpcModeStaticIP   SecureProxySummaryVpcMode = "static_ip"
	SecureProxySummaryVpcModeSecureLink SecureProxySummaryVpcMode = "secure_link"
)

func (e SecureProxySummaryVpcMode) ToPointer() *SecureProxySummaryVpcMode {
	return &e
}
func (e *SecureProxySummaryVpcMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "static_ip":
		fallthrough
	case "secure_link":
		*e = SecureProxySummaryVpcMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SecureProxySummaryVpcMode: %v", v)
	}
}

type SecureProxySummary struct {
	ID              string                    `json:"id"`
	Name            string                    `json:"name"`
	Slug            *string                   `json:"slug,omitempty"`
	Enabled         bool                      `json:"enabled"`
	VpcMode         SecureProxySummaryVpcMode `json:"vpc_mode"`
	AllowedDomains  []string                  `json:"allowed_domains,omitempty"`
	AllowedIps      []string                  `json:"allowed_ips,omitempty"`
	IntegrationID   string                    `json:"integration_id"`
	IntegrationName string                    `json:"integration_name"`
}

func (s *SecureProxySummary) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SecureProxySummary) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SecureProxySummary) GetSlug() *string {
	if s == nil {
		return nil
	}
	return s.Slug
}

func (s *SecureProxySummary) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *SecureProxySummary) GetVpcMode() SecureProxySummaryVpcMode {
	if s == nil {
		return SecureProxySummaryVpcMode("")
	}
	return s.VpcMode
}

func (s *SecureProxySummary) GetAllowedDomains() []string {
	if s == nil {
		return nil
	}
	return s.AllowedDomains
}

func (s *SecureProxySummary) GetAllowedIps() []string {
	if s == nil {
		return nil
	}
	return s.AllowedIps
}

func (s *SecureProxySummary) GetIntegrationID() string {
	if s == nil {
		return ""
	}
	return s.IntegrationID
}

func (s *SecureProxySummary) GetIntegrationName() string {
	if s == nil {
		return ""
	}
	return s.IntegrationName
}
