// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// SecureProxyWhitelistVpcMode - VPC routing mode (read-only). `null` if not yet set.
type SecureProxyWhitelistVpcMode string

const (
	SecureProxyWhitelistVpcModeStaticIP   SecureProxyWhitelistVpcMode = "static_ip"
	SecureProxyWhitelistVpcModeSecureLink SecureProxyWhitelistVpcMode = "secure_link"
)

func (e SecureProxyWhitelistVpcMode) ToPointer() *SecureProxyWhitelistVpcMode {
	return &e
}
func (e *SecureProxyWhitelistVpcMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "static_ip":
		fallthrough
	case "secure_link":
		*e = SecureProxyWhitelistVpcMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SecureProxyWhitelistVpcMode: %v", v)
	}
}

// SecureProxyWhitelist - Current whitelist state for a secure_proxy use case. vpc_mode is read-only
// context so the UI can show the user what mode the pool is in.
type SecureProxyWhitelist struct {
	// VPC routing mode (read-only). `null` if not yet set.
	VpcMode *SecureProxyWhitelistVpcMode `json:"vpc_mode"`
	// Exact domain ("api.example.com") or wildcard prefix ("*.example.com").
	// Wildcards must have at least 2 labels in the suffix.
	//
	AllowedDomains []string `json:"allowed_domains"`
	// CIDR-notation IP ranges, e.g. "10.0.0.0/24".
	AllowedIps []string `json:"allowed_ips"`
}

func (s *SecureProxyWhitelist) GetVpcMode() *SecureProxyWhitelistVpcMode {
	if s == nil {
		return nil
	}
	return s.VpcMode
}

func (s *SecureProxyWhitelist) GetAllowedDomains() []string {
	if s == nil {
		return []string{}
	}
	return s.AllowedDomains
}

func (s *SecureProxyWhitelist) GetAllowedIps() []string {
	if s == nil {
		return []string{}
	}
	return s.AllowedIps
}
