// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// VpcMode - VPC routing mode. Read-only after creation.
// - static_ip: Routes through a VPC with static outbound IP (NAT Gateway) for IP-allowlisted external APIs.
// - secure_link: Routes through a VPN VPC for accessing private customer networks.
type VpcMode string

const (
	VpcModeStaticIP   VpcMode = "static_ip"
	VpcModeSecureLink VpcMode = "secure_link"
)

func (e VpcMode) ToPointer() *VpcMode {
	return &e
}
func (e *VpcMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "static_ip":
		fallthrough
	case "secure_link":
		*e = VpcMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VpcMode: %v", v)
	}
}

// SecureProxyUseCaseConfiguration - Configuration for secure_proxy use cases. Defines how to route requests through a secure VPC.
type SecureProxyUseCaseConfiguration struct {
	// VPC routing mode. Read-only after creation.
	// - static_ip: Routes through a VPC with static outbound IP (NAT Gateway) for IP-allowlisted external APIs.
	// - secure_link: Routes through a VPN VPC for accessing private customer networks.
	//
	VpcMode VpcMode `json:"vpc_mode"`
	// Domain whitelist for secure_link mode. Admin-only — can only be modified directly in DynamoDB via admin script.
	// Supports exact match (e.g., "api.wemag.com") and wildcard prefix (e.g., "*.wemag.com").
	//
	AllowedDomains []string `json:"allowed_domains,omitempty"`
	// IP allowlist (CIDR notation) for secure_link mode. Admin-only — can only be modified directly in DynamoDB via admin script.
	// Required for secure_link mode. All DNS-resolved IPs must match at least one range.
	// Example: ["10.0.1.0/24", "192.168.1.0/24"]
	//
	AllowedIps []string `json:"allowed_ips,omitempty"`
}

func (s SecureProxyUseCaseConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SecureProxyUseCaseConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SecureProxyUseCaseConfiguration) GetVpcMode() VpcMode {
	if s == nil {
		return VpcMode("")
	}
	return s.VpcMode
}

func (s *SecureProxyUseCaseConfiguration) GetAllowedDomains() []string {
	if s == nil {
		return nil
	}
	return s.AllowedDomains
}

func (s *SecureProxyUseCaseConfiguration) GetAllowedIps() []string {
	if s == nil {
		return nil
	}
	return s.AllowedIps
}
