// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// SecureProxyUseCaseConfigurationInput - Configuration for secure_proxy use cases. Defines how to route requests through a secure VPC.
type SecureProxyUseCaseConfigurationInput struct {
}

func (s SecureProxyUseCaseConfigurationInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SecureProxyUseCaseConfigurationInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}
