// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// TimeSeriesBreakdownItemV2UseCaseType - Present when grouping by use_case_type
type TimeSeriesBreakdownItemV2UseCaseType string

const (
	TimeSeriesBreakdownItemV2UseCaseTypeInbound     TimeSeriesBreakdownItemV2UseCaseType = "inbound"
	TimeSeriesBreakdownItemV2UseCaseTypeOutbound    TimeSeriesBreakdownItemV2UseCaseType = "outbound"
	TimeSeriesBreakdownItemV2UseCaseTypeFileProxy   TimeSeriesBreakdownItemV2UseCaseType = "file_proxy"
	TimeSeriesBreakdownItemV2UseCaseTypeManagedCall TimeSeriesBreakdownItemV2UseCaseType = "managed_call"
	TimeSeriesBreakdownItemV2UseCaseTypeSecureProxy TimeSeriesBreakdownItemV2UseCaseType = "secure_proxy"
)

func (e TimeSeriesBreakdownItemV2UseCaseType) ToPointer() *TimeSeriesBreakdownItemV2UseCaseType {
	return &e
}
func (e *TimeSeriesBreakdownItemV2UseCaseType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inbound":
		fallthrough
	case "outbound":
		fallthrough
	case "file_proxy":
		fallthrough
	case "managed_call":
		fallthrough
	case "secure_proxy":
		*e = TimeSeriesBreakdownItemV2UseCaseType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TimeSeriesBreakdownItemV2UseCaseType: %v", v)
	}
}

type TimeSeriesBreakdownItemV2 struct {
	// Present when grouping by use_case_type
	UseCaseType *TimeSeriesBreakdownItemV2UseCaseType `json:"use_case_type,omitempty"`
	// Present when grouping by use_case. Unknown historical IDs are collapsed into "__unknown__"
	UseCaseID *string `json:"use_case_id,omitempty"`
	// Number of successful events in the breakdown item
	SuccessCount int64 `json:"success_count"`
	// Number of error events in the breakdown item
	ErrorCount int64 `json:"error_count"`
	// Number of warning events in the breakdown item
	WarningCount int64 `json:"warning_count"`
	// Number of skipped events in the breakdown item
	SkippedCount int64 `json:"skipped_count"`
	// Total events in the breakdown item
	TotalCount int64 `json:"total_count"`
}

func (t *TimeSeriesBreakdownItemV2) GetUseCaseType() *TimeSeriesBreakdownItemV2UseCaseType {
	if t == nil {
		return nil
	}
	return t.UseCaseType
}

func (t *TimeSeriesBreakdownItemV2) GetUseCaseID() *string {
	if t == nil {
		return nil
	}
	return t.UseCaseID
}

func (t *TimeSeriesBreakdownItemV2) GetSuccessCount() int64 {
	if t == nil {
		return 0
	}
	return t.SuccessCount
}

func (t *TimeSeriesBreakdownItemV2) GetErrorCount() int64 {
	if t == nil {
		return 0
	}
	return t.ErrorCount
}

func (t *TimeSeriesBreakdownItemV2) GetWarningCount() int64 {
	if t == nil {
		return 0
	}
	return t.WarningCount
}

func (t *TimeSeriesBreakdownItemV2) GetSkippedCount() int64 {
	if t == nil {
		return 0
	}
	return t.SkippedCount
}

func (t *TimeSeriesBreakdownItemV2) GetTotalCount() int64 {
	if t == nil {
		return 0
	}
	return t.TotalCount
}

// #region class-body-timeseriesbreakdownitemv2
// #endregion class-body-timeseriesbreakdownitemv2
