// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Kind string

const (
	KindObject  Kind = "object"
	KindArray   Kind = "array"
	KindString  Kind = "string"
	KindNumber  Kind = "number"
	KindBoolean Kind = "boolean"
	KindNull    Kind = "null"
	KindUnknown Kind = "unknown"
	KindUnion   Kind = "union"
)

func (e Kind) ToPointer() *Kind {
	return &e
}
func (e *Kind) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "object":
		fallthrough
	case "array":
		fallthrough
	case "string":
		fallthrough
	case "number":
		fallthrough
	case "boolean":
		fallthrough
	case "null":
		fallthrough
	case "unknown":
		fallthrough
	case "union":
		*e = Kind(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Kind: %v", v)
	}
}

// TypeDescriptor - Describes the inferred type shape of a JSONata expression
type TypeDescriptor struct {
	Kind Kind `json:"kind"`
	// For kind=object, the properties and their type descriptors
	Properties map[string]TypeDescriptor `json:"properties,omitempty"`
	// For kind=array, the type of array items
	Items *TypeDescriptor `json:"items,omitempty"`
	// For kind=unknown, the JSONata path that produced this value
	Source *string `json:"source,omitempty"`
	// For kind=union, the variant types
	Variants []TypeDescriptor `json:"variants,omitempty"`
}

func (t *TypeDescriptor) GetKind() Kind {
	if t == nil {
		return Kind("")
	}
	return t.Kind
}

func (t *TypeDescriptor) GetProperties() map[string]TypeDescriptor {
	if t == nil {
		return nil
	}
	return t.Properties
}

func (t *TypeDescriptor) GetItems() *TypeDescriptor {
	if t == nil {
		return nil
	}
	return t.Items
}

func (t *TypeDescriptor) GetSource() *string {
	if t == nil {
		return nil
	}
	return t.Source
}

func (t *TypeDescriptor) GetVariants() []TypeDescriptor {
	if t == nil {
		return nil
	}
	return t.Variants
}
