// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UnblockOutboundStreamResponse struct {
	// Whether a blocked head was skipped (false = no-op, stream was not blocked)
	Unblocked bool `json:"unblocked"`
	// Message id of the skipped head — present only when unblocked is true
	DeadLetteredID *string `json:"dead_lettered_id,omitempty"`
}

func (u *UnblockOutboundStreamResponse) GetUnblocked() bool {
	if u == nil {
		return false
	}
	return u.Unblocked
}

func (u *UnblockOutboundStreamResponse) GetDeadLetteredID() *string {
	if u == nil {
		return nil
	}
	return u.DeadLetteredID
}
