// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateIntegrationRequest struct {
	// Integration name
	Name *string `json:"name,omitempty"`
	// Optional description of the integration
	Description *string `json:"description,omitempty"`
	// List of access token IDs to associate with this integration
	AccessTokenIds []string `json:"access_token_ids,omitempty"`
}

func (u *UpdateIntegrationRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateIntegrationRequest) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateIntegrationRequest) GetAccessTokenIds() []string {
	if u == nil {
		return nil
	}
	return u.AccessTokenIds
}
