// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// UpdateOutboundUseCaseRequestType - Use case type
type UpdateOutboundUseCaseRequestType string

const (
	UpdateOutboundUseCaseRequestTypeOutbound UpdateOutboundUseCaseRequestType = "outbound"
)

func (e UpdateOutboundUseCaseRequestType) ToPointer() *UpdateOutboundUseCaseRequestType {
	return &e
}
func (e *UpdateOutboundUseCaseRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "outbound":
		*e = UpdateOutboundUseCaseRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateOutboundUseCaseRequestType: %v", v)
	}
}

type UpdateOutboundUseCaseRequest struct {
	// Use case name
	Name *string `json:"name,omitempty"`
	// Whether the use case is enabled
	Enabled *bool `json:"enabled,omitempty"`
	// Optional description of this change (like a commit message)
	ChangeDescription *string `json:"change_description,omitempty"`
	// Use case type
	Type *UpdateOutboundUseCaseRequestType `json:"type,omitempty"`
	// Configuration for outbound use cases (epilot to ERP). Structure TBD.
	Configuration map[string]any `json:"configuration,omitempty"`
}

func (u UpdateOutboundUseCaseRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateOutboundUseCaseRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *UpdateOutboundUseCaseRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateOutboundUseCaseRequest) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *UpdateOutboundUseCaseRequest) GetChangeDescription() *string {
	if o == nil {
		return nil
	}
	return o.ChangeDescription
}

func (o *UpdateOutboundUseCaseRequest) GetType() *UpdateOutboundUseCaseRequestType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *UpdateOutboundUseCaseRequest) GetConfiguration() map[string]any {
	if o == nil {
		return nil
	}
	return o.Configuration
}
