// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

type UpdateUseCaseRequestType string

const (
	UpdateUseCaseRequestTypeInbound   UpdateUseCaseRequestType = "inbound"
	UpdateUseCaseRequestTypeOutbound  UpdateUseCaseRequestType = "outbound"
	UpdateUseCaseRequestTypeFileProxy UpdateUseCaseRequestType = "file_proxy"
)

type UpdateUseCaseRequest struct {
	UpdateInboundUseCaseRequest   *UpdateInboundUseCaseRequest   `queryParam:"inline" union:"member"`
	UpdateOutboundUseCaseRequest  *UpdateOutboundUseCaseRequest  `queryParam:"inline" union:"member"`
	UpdateFileProxyUseCaseRequest *UpdateFileProxyUseCaseRequest `queryParam:"inline" union:"member"`

	Type UpdateUseCaseRequestType
}

func CreateUpdateUseCaseRequestInbound(inbound UpdateInboundUseCaseRequest) UpdateUseCaseRequest {
	typ := UpdateUseCaseRequestTypeInbound

	typStr := UpdateInboundUseCaseRequestType(typ)
	inbound.Type = &typStr

	return UpdateUseCaseRequest{
		UpdateInboundUseCaseRequest: &inbound,
		Type:                        typ,
	}
}

func CreateUpdateUseCaseRequestOutbound(outbound UpdateOutboundUseCaseRequest) UpdateUseCaseRequest {
	typ := UpdateUseCaseRequestTypeOutbound

	typStr := UpdateOutboundUseCaseRequestType(typ)
	outbound.Type = &typStr

	return UpdateUseCaseRequest{
		UpdateOutboundUseCaseRequest: &outbound,
		Type:                         typ,
	}
}

func CreateUpdateUseCaseRequestFileProxy(fileProxy UpdateFileProxyUseCaseRequest) UpdateUseCaseRequest {
	typ := UpdateUseCaseRequestTypeFileProxy

	typStr := UpdateFileProxyUseCaseRequestType(typ)
	fileProxy.Type = &typStr

	return UpdateUseCaseRequest{
		UpdateFileProxyUseCaseRequest: &fileProxy,
		Type:                          typ,
	}
}

func (u *UpdateUseCaseRequest) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "inbound":
		updateInboundUseCaseRequest := new(UpdateInboundUseCaseRequest)
		if err := utils.UnmarshalJSON(data, &updateInboundUseCaseRequest, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == inbound) type UpdateInboundUseCaseRequest within UpdateUseCaseRequest: %w", string(data), err)
		}

		u.UpdateInboundUseCaseRequest = updateInboundUseCaseRequest
		u.Type = UpdateUseCaseRequestTypeInbound
		return nil
	case "outbound":
		updateOutboundUseCaseRequest := new(UpdateOutboundUseCaseRequest)
		if err := utils.UnmarshalJSON(data, &updateOutboundUseCaseRequest, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == outbound) type UpdateOutboundUseCaseRequest within UpdateUseCaseRequest: %w", string(data), err)
		}

		u.UpdateOutboundUseCaseRequest = updateOutboundUseCaseRequest
		u.Type = UpdateUseCaseRequestTypeOutbound
		return nil
	case "file_proxy":
		updateFileProxyUseCaseRequest := new(UpdateFileProxyUseCaseRequest)
		if err := utils.UnmarshalJSON(data, &updateFileProxyUseCaseRequest, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == file_proxy) type UpdateFileProxyUseCaseRequest within UpdateUseCaseRequest: %w", string(data), err)
		}

		u.UpdateFileProxyUseCaseRequest = updateFileProxyUseCaseRequest
		u.Type = UpdateUseCaseRequestTypeFileProxy
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateUseCaseRequest", string(data))
}

func (u UpdateUseCaseRequest) MarshalJSON() ([]byte, error) {
	if u.UpdateInboundUseCaseRequest != nil {
		return utils.MarshalJSON(u.UpdateInboundUseCaseRequest, "", true)
	}

	if u.UpdateOutboundUseCaseRequest != nil {
		return utils.MarshalJSON(u.UpdateOutboundUseCaseRequest, "", true)
	}

	if u.UpdateFileProxyUseCaseRequest != nil {
		return utils.MarshalJSON(u.UpdateFileProxyUseCaseRequest, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateUseCaseRequest: all fields are null")
}
