// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

// UpdateSecureProxyUseCaseRequestType - Use case type
type UpdateSecureProxyUseCaseRequestType string

const (
	UpdateSecureProxyUseCaseRequestTypeSecureProxy UpdateSecureProxyUseCaseRequestType = "secure_proxy"
)

func (e UpdateSecureProxyUseCaseRequestType) ToPointer() *UpdateSecureProxyUseCaseRequestType {
	return &e
}
func (e *UpdateSecureProxyUseCaseRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "secure_proxy":
		*e = UpdateSecureProxyUseCaseRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateSecureProxyUseCaseRequestType: %v", v)
	}
}

type UpdateSecureProxyUseCaseRequest struct {
	// Use case name
	Name *string `json:"name,omitempty"`
	// URL-safe identifier for the use case. Recommended for portable cross-environment referencing. Can only be set once on use cases that don't have a slug yet. Immutable after being set.
	//
	Slug *string `json:"slug,omitempty"`
	// Whether the use case is enabled
	Enabled *bool `json:"enabled,omitempty"`
	// Optional description of this change (like a commit message)
	ChangeDescription *string `json:"change_description,omitempty"`
	// Use case type
	Type *UpdateSecureProxyUseCaseRequestType `json:"type,omitempty"`
	// Configuration for secure_proxy use cases. Defines how to route requests through a secure VPC.
	//
	Configuration *SecureProxyUseCaseConfigurationInput `json:"configuration,omitempty"`
}

func (u UpdateSecureProxyUseCaseRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSecureProxyUseCaseRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSecureProxyUseCaseRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateSecureProxyUseCaseRequest) GetSlug() *string {
	if u == nil {
		return nil
	}
	return u.Slug
}

func (u *UpdateSecureProxyUseCaseRequest) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

func (u *UpdateSecureProxyUseCaseRequest) GetChangeDescription() *string {
	if u == nil {
		return nil
	}
	return u.ChangeDescription
}

func (u *UpdateSecureProxyUseCaseRequest) GetType() *UpdateSecureProxyUseCaseRequestType {
	if u == nil {
		return nil
	}
	return u.Type
}

func (u *UpdateSecureProxyUseCaseRequest) GetConfiguration() *SecureProxyUseCaseConfigurationInput {
	if u == nil {
		return nil
	}
	return u.Configuration
}
