// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// UpsertIntegrationWithUseCasesRequest - Request to create or update an integration with embedded use cases (upsert).
// This is a declarative operation - the request represents the desired state.
type UpsertIntegrationWithUseCasesRequest struct {
	// Integration name
	Name string `json:"name"`
	// Optional description of the integration
	Description *string `json:"description,omitempty"`
	// List of access token IDs to associate with this integration
	AccessTokenIds []string `json:"access_token_ids,omitempty"`
	// Settings for the integration
	Settings *IntegrationSettings `json:"settings,omitempty"`
	// Full list of use cases (declarative). This replaces ALL existing use cases.
	// - Use cases with an `id` field matching an existing use case will be updated
	// - Use cases without an `id` or with a non-matching `id` will be created
	// - Existing use cases not in this list will be deleted
	//
	UseCases []EmbeddedUseCaseRequest `json:"use_cases,omitempty"`
}

func (u *UpsertIntegrationWithUseCasesRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpsertIntegrationWithUseCasesRequest) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpsertIntegrationWithUseCasesRequest) GetAccessTokenIds() []string {
	if u == nil {
		return nil
	}
	return u.AccessTokenIds
}

func (u *UpsertIntegrationWithUseCasesRequest) GetSettings() *IntegrationSettings {
	if u == nil {
		return nil
	}
	return u.Settings
}

func (u *UpsertIntegrationWithUseCasesRequest) GetUseCases() []EmbeddedUseCaseRequest {
	if u == nil {
		return nil
	}
	return u.UseCases
}
