// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// UpsertIntegrationWithUseCasesRequest - Request to create or update an integration with embedded use cases (upsert).
// This is a declarative operation - the request represents the desired state.
type UpsertIntegrationWithUseCasesRequest struct {
	// Integration name
	Name string `json:"name"`
	// Optional description of the integration
	Description *string `json:"description,omitempty"`
	// List of access token IDs associated with this integration
	AccessTokenIds []string `json:"access_token_ids,omitempty"`
	// List of app IDs associated with this integration
	AppIds []string `json:"app_ids,omitempty"`
	// Settings for the integration
	Settings          *IntegrationSettings `json:"settings,omitempty"`
	EnvironmentConfig any                  `json:"environment_config,omitempty"`
	UseCases          any                  `json:"use_cases,omitempty"`
}

func (u *UpsertIntegrationWithUseCasesRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpsertIntegrationWithUseCasesRequest) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpsertIntegrationWithUseCasesRequest) GetAccessTokenIds() []string {
	if u == nil {
		return nil
	}
	return u.AccessTokenIds
}

func (u *UpsertIntegrationWithUseCasesRequest) GetAppIds() []string {
	if u == nil {
		return nil
	}
	return u.AppIds
}

func (u *UpsertIntegrationWithUseCasesRequest) GetSettings() *IntegrationSettings {
	if u == nil {
		return nil
	}
	return u.Settings
}

func (u *UpsertIntegrationWithUseCasesRequest) GetEnvironmentConfig() any {
	if u == nil {
		return nil
	}
	return u.EnvironmentConfig
}

func (u *UpsertIntegrationWithUseCasesRequest) GetUseCases() any {
	if u == nil {
		return nil
	}
	return u.UseCases
}
