// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/internal/utils"
)

type UseCaseType string

const (
	UseCaseTypeInbound  UseCaseType = "inbound"
	UseCaseTypeOutbound UseCaseType = "outbound"
)

type UseCase struct {
	InboundUseCase  *InboundUseCase  `queryParam:"inline" union:"member"`
	OutboundUseCase *OutboundUseCase `queryParam:"inline" union:"member"`

	Type UseCaseType
}

func CreateUseCaseInbound(inbound InboundUseCase) UseCase {
	typ := UseCaseTypeInbound

	typStr := InboundUseCaseType(typ)
	inbound.Type = typStr

	return UseCase{
		InboundUseCase: &inbound,
		Type:           typ,
	}
}

func CreateUseCaseOutbound(outbound OutboundUseCase) UseCase {
	typ := UseCaseTypeOutbound

	typStr := OutboundUseCaseType(typ)
	outbound.Type = typStr

	return UseCase{
		OutboundUseCase: &outbound,
		Type:            typ,
	}
}

func (u *UseCase) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "inbound":
		inboundUseCase := new(InboundUseCase)
		if err := utils.UnmarshalJSON(data, &inboundUseCase, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == inbound) type InboundUseCase within UseCase: %w", string(data), err)
		}

		u.InboundUseCase = inboundUseCase
		u.Type = UseCaseTypeInbound
		return nil
	case "outbound":
		outboundUseCase := new(OutboundUseCase)
		if err := utils.UnmarshalJSON(data, &outboundUseCase, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == outbound) type OutboundUseCase within UseCase: %w", string(data), err)
		}

		u.OutboundUseCase = outboundUseCase
		u.Type = UseCaseTypeOutbound
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UseCase", string(data))
}

func (u UseCase) MarshalJSON() ([]byte, error) {
	if u.InboundUseCase != nil {
		return utils.MarshalJSON(u.InboundUseCase, "", true)
	}

	if u.OutboundUseCase != nil {
		return utils.MarshalJSON(u.OutboundUseCase, "", true)
	}

	return nil, errors.New("could not marshal union type UseCase: all fields are null")
}
