// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// UseCaseTypePreview - Scaffolded type descriptors for a single use case
type UseCaseTypePreview struct {
	Slug string  `json:"slug"`
	Name *string `json:"name,omitempty"`
	// Describes the inferred type shape of a JSONata expression
	RequestShape TypeDescriptor `json:"request_shape"`
	// Describes the inferred type shape of a JSONata expression
	ResponseShape TypeDescriptor `json:"response_shape"`
	// Developer-provided type annotations for a use case's request and response fields
	ExistingAnnotations *TypeAnnotations `json:"existing_annotations,omitempty"`
}

func (u *UseCaseTypePreview) GetSlug() string {
	if u == nil {
		return ""
	}
	return u.Slug
}

func (u *UseCaseTypePreview) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UseCaseTypePreview) GetRequestShape() TypeDescriptor {
	if u == nil {
		return TypeDescriptor{}
	}
	return u.RequestShape
}

func (u *UseCaseTypePreview) GetResponseShape() TypeDescriptor {
	if u == nil {
		return TypeDescriptor{}
	}
	return u.ResponseShape
}

func (u *UseCaseTypePreview) GetExistingAnnotations() *TypeAnnotations {
	if u == nil {
		return nil
	}
	return u.ExistingAnnotations
}
