// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/validators"
	speakeasy_boolvalidators "github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/validators/boolvalidators"
	speakeasy_listvalidators "github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/validators/listvalidators"
	speakeasy_objectvalidators "github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/validators/objectvalidators"
	speakeasy_stringvalidators "github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/validators/stringvalidators"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/boolvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"regexp"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &IntegrationResource{}
var _ resource.ResourceWithImportState = &IntegrationResource{}

func NewIntegrationResource() resource.Resource {
	return &IntegrationResource{}
}

// IntegrationResource defines the resource implementation.
type IntegrationResource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// IntegrationResourceModel describes the resource data model.
type IntegrationResourceModel struct {
	AccessTokenIds    []types.String                   `tfsdk:"access_token_ids"`
	AppIds            []types.String                   `tfsdk:"app_ids"`
	CreatedAt         types.String                     `tfsdk:"created_at"`
	Description       types.String                     `tfsdk:"description"`
	EnvironmentConfig []tfTypes.EnvironmentFieldConfig `tfsdk:"environment_config"`
	ID                types.String                     `tfsdk:"id"`
	Name              types.String                     `tfsdk:"name"`
	OrgID             types.String                     `tfsdk:"org_id"`
	Settings          *tfTypes.IntegrationSettings     `tfsdk:"settings"`
	UpdatedAt         types.String                     `tfsdk:"updated_at"`
	UseCases          []tfTypes.UseCase                `tfsdk:"use_cases"`
}

func (r *IntegrationResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_integration"
}

func (r *IntegrationResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Integration Resource",
		Attributes: map[string]schema.Attribute{
			"access_token_ids": schema.ListAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				Description: `List of access token IDs associated with this integration`,
			},
			"app_ids": schema.ListAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				Description: `List of app IDs associated with this integration`,
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `ISO-8601 timestamp when the integration was created`,
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `Optional description of the integration`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthAtMost(1000),
				},
			},
			"environment_config": schema.ListNestedAttribute{
				Computed: true,
				Optional: true,
				NestedObject: schema.NestedAttributeObject{
					Validators: []validator.Object{
						speakeasy_objectvalidators.NotNull(),
					},
					Attributes: map[string]schema.Attribute{
						"description": schema.StringAttribute{
							Computed:    true,
							Optional:    true,
							Description: `Help text shown below the field`,
							Validators: []validator.String{
								stringvalidator.UTF8LengthAtMost(1000),
							},
						},
						"key": schema.StringAttribute{
							Computed:    true,
							Optional:    true,
							Description: `Environment variable key, used to look up the value in the Environments API. Not Null`,
							Validators: []validator.String{
								speakeasy_stringvalidators.NotNull(),
								stringvalidator.RegexMatches(regexp.MustCompile(`^[a-z0-9][a-z0-9_.\-]{0,127}$`), "must match pattern "+regexp.MustCompile(`^[a-z0-9][a-z0-9_.\-]{0,127}$`).String()),
							},
						},
						"label": schema.StringAttribute{
							Computed:    true,
							Optional:    true,
							Description: `Display label for the field in the UI. Not Null`,
							Validators: []validator.String{
								speakeasy_stringvalidators.NotNull(),
								stringvalidator.UTF8LengthBetween(1, 255),
							},
						},
						"order": schema.Int64Attribute{
							Computed:    true,
							Optional:    true,
							Description: `Sort order for display and drag-to-reorder`,
						},
						"required": schema.BoolAttribute{
							Computed:    true,
							Optional:    true,
							Default:     booldefault.StaticBool(false),
							Description: `Whether this field must be filled before the integration can be used. Default: false`,
						},
						"type": schema.StringAttribute{
							Computed:    true,
							Optional:    true,
							Description: `Whether the value is a plain string or an encrypted secret. Not Null; must be one of ["String", "SecretString"]`,
							Validators: []validator.String{
								speakeasy_stringvalidators.NotNull(),
								stringvalidator.OneOf(
									"String",
									"SecretString",
								),
							},
						},
					},
				},
				Description: `Configuration defining environment variables needed by this integration. Values are stored in the Environments API.`,
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `Unique identifier for the integration`,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: `Integration name`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthBetween(1, 255),
				},
			},
			"org_id": schema.StringAttribute{
				Computed:    true,
				Description: `Organization ID`,
			},
			"settings": schema.SingleNestedAttribute{
				Computed: true,
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"auto_refresh": schema.SingleNestedAttribute{
						Computed: true,
						Optional: true,
						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Computed:    true,
								Optional:    true,
								Default:     booldefault.StaticBool(false),
								Description: `Whether auto-refresh is enabled. Default: false`,
							},
							"freshness_threshold_minutes": schema.Int64Attribute{
								Computed:    true,
								Optional:    true,
								Description: `Maximum age (in minutes) of data before it is considered stale and eligible for refresh`,
								Validators: []validator.Int64{
									int64validator.AtLeast(1),
								},
							},
						},
						Description: `Auto-refresh settings for keeping integration data fresh`,
					},
				},
				Description: `Settings for the integration`,
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `ISO-8601 timestamp when the integration was last updated`,
			},
			"use_cases": schema.ListNestedAttribute{
				Computed: true,
				Optional: true,
				NestedObject: schema.NestedAttributeObject{
					Validators: []validator.Object{
						speakeasy_objectvalidators.NotNull(),
					},
					Attributes: map[string]schema.Attribute{
						"file_proxy_use_case": schema.SingleNestedAttribute{
							Optional: true,
							Attributes: map[string]schema.Attribute{
								"change_description": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Description of the last change made to this use case`,
									Validators: []validator.String{
										stringvalidator.UTF8LengthAtMost(2000),
									},
								},
								"configuration": schema.SingleNestedAttribute{
									Computed: true,
									Optional: true,
									Attributes: map[string]schema.Attribute{
										"auth": schema.SingleNestedAttribute{
											Computed: true,
											Optional: true,
											Attributes: map[string]schema.Attribute{
												"client_id": schema.StringAttribute{
													Computed:    true,
													Optional:    true,
													Description: `Handlebars template for the OAuth2 client ID. Not Null`,
													Validators: []validator.String{
														speakeasy_stringvalidators.NotNull(),
													},
												},
												"client_secret": schema.StringAttribute{
													Computed:    true,
													Optional:    true,
													Description: `Handlebars template for the OAuth2 client secret. Not Null`,
													Validators: []validator.String{
														speakeasy_stringvalidators.NotNull(),
													},
												},
												"scope": schema.StringAttribute{
													Computed:    true,
													Optional:    true,
													Description: `Optional OAuth2 scope`,
												},
												"token_url": schema.StringAttribute{
													Computed:    true,
													Optional:    true,
													Description: `Handlebars template for the OAuth2 token endpoint URL. Not Null`,
													Validators: []validator.String{
														speakeasy_stringvalidators.NotNull(),
													},
												},
												"type": schema.StringAttribute{
													Computed:    true,
													Optional:    true,
													Description: `Authentication type. Not Null; must be "oauth2_client_credentials"`,
													Validators: []validator.String{
														speakeasy_stringvalidators.NotNull(),
														stringvalidator.OneOf(
															"oauth2_client_credentials",
														),
													},
												},
											},
										},
										"params": schema.ListNestedAttribute{
											Computed: true,
											Optional: true,
											NestedObject: schema.NestedAttributeObject{
												Validators: []validator.Object{
													speakeasy_objectvalidators.NotNull(),
												},
												Attributes: map[string]schema.Attribute{
													"description": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Human-readable description of the parameter`,
													},
													"name": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Parameter name as it appears in the query string. Not Null`,
														Validators: []validator.String{
															speakeasy_stringvalidators.NotNull(),
														},
													},
													"required": schema.BoolAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Whether this parameter is required. Not Null`,
														Validators: []validator.Bool{
															speakeasy_boolvalidators.NotNull(),
														},
													},
												},
											},
											Description: `Additional use-case-specific parameters expected in the download URL query string (beyond the required orgId, integrationId, useCaseId)`,
										},
										"requires_vpc": schema.BoolAttribute{
											Computed:    true,
											Optional:    true,
											Default:     booldefault.StaticBool(false),
											Description: `Whether requests require VPC routing for IP allowlisting. Default: false`,
										},
										"response": schema.SingleNestedAttribute{
											Computed: true,
											Optional: true,
											Attributes: map[string]schema.Attribute{
												"body": schema.StringAttribute{
													Computed:    true,
													Optional:    true,
													Description: `JSONata expression to extract file content from step results. Not Null`,
													Validators: []validator.String{
														speakeasy_stringvalidators.NotNull(),
													},
												},
												"content_type": schema.StringAttribute{
													Computed:    true,
													Optional:    true,
													Description: `JSONata expression to extract the content type`,
												},
												"encoding": schema.StringAttribute{
													Computed:    true,
													Optional:    true,
													Description: `Encoding of the extracted body. Not Null; must be one of ["base64", "binary"]`,
													Validators: []validator.String{
														speakeasy_stringvalidators.NotNull(),
														stringvalidator.OneOf(
															"base64",
															"binary",
														),
													},
												},
												"filename": schema.StringAttribute{
													Computed:    true,
													Optional:    true,
													Description: `JSONata expression to extract the filename`,
												},
											},
											Description: `Not Null`,
											Validators: []validator.Object{
												speakeasy_objectvalidators.NotNull(),
											},
										},
										"steps": schema.ListNestedAttribute{
											Computed: true,
											Optional: true,
											NestedObject: schema.NestedAttributeObject{
												Validators: []validator.Object{
													speakeasy_objectvalidators.NotNull(),
												},
												Attributes: map[string]schema.Attribute{
													"body": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Handlebars template for the request body (POST only)`,
													},
													"headers": schema.MapAttribute{
														Computed:    true,
														Optional:    true,
														ElementType: types.StringType,
														Description: `Handlebars templates for request headers`,
													},
													"method": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `HTTP method. Not Null; must be one of ["GET", "POST"]`,
														Validators: []validator.String{
															speakeasy_stringvalidators.NotNull(),
															stringvalidator.OneOf(
																"GET",
																"POST",
															),
														},
													},
													"response_type": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Expected response type. Not Null; must be one of ["json", "binary"]`,
														Validators: []validator.String{
															speakeasy_stringvalidators.NotNull(),
															stringvalidator.OneOf(
																"json",
																"binary",
															),
														},
													},
													"url": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Handlebars template for the request URL. Not Null`,
														Validators: []validator.String{
															speakeasy_stringvalidators.NotNull(),
														},
													},
												},
											},
											Description: `Ordered list of HTTP steps to execute to retrieve the file. Not Null`,
											Validators: []validator.List{
												speakeasy_listvalidators.NotNull(),
												listvalidator.SizeAtLeast(1),
											},
										},
									},
									MarkdownDescription: `Configuration for file_proxy use cases. Defines how to authenticate and fetch files from external document systems.` + "\n" +
										`` + "\n" +
										`The file proxy download URL always requires ` + "`" + `orgId` + "`" + `, ` + "`" + `integrationId` + "`" + `, and ` + "`" + `useCaseId` + "`" + ` as query parameters.` + "\n" +
										`The ` + "`" + `orgId` + "`" + ` is included in the signed URL to establish organization context without requiring authentication.` + "\n" +
										`Additional use-case-specific parameters are declared in the ` + "`" + `params` + "`" + ` array.`,
								},
								"created_at": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `ISO-8601 timestamp when the use case was created. Not Null`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
										validators.IsRFC3339(),
									},
								},
								"enabled": schema.BoolAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Not Null`,
									Validators: []validator.Bool{
										speakeasy_boolvalidators.NotNull(),
									},
								},
								"id": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Unique identifier for the use case. Not Null`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
									},
								},
								"integration_id": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Parent integration ID. Not Null`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
									},
								},
								"name": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Use case name. Not Null`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
									},
								},
								"type": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Use case type. Not Null; must be "file_proxy"`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
										stringvalidator.OneOf(
											"file_proxy",
										),
									},
								},
								"updated_at": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `ISO-8601 timestamp when the use case was last updated. Not Null`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
										validators.IsRFC3339(),
									},
								},
							},
							Validators: []validator.Object{
								objectvalidator.ConflictsWith(path.Expressions{
									path.MatchRelative().AtParent().AtName("inbound"),
									path.MatchRelative().AtParent().AtName("outbound"),
								}...),
							},
						},
						"inbound": schema.SingleNestedAttribute{
							Optional: true,
							Attributes: map[string]schema.Attribute{
								"change_description": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Optional description of this change (like a commit message)`,
									Validators: []validator.String{
										stringvalidator.UTF8LengthAtMost(2000),
									},
								},
								"configuration": schema.SingleNestedAttribute{
									Computed: true,
									Optional: true,
									Attributes: map[string]schema.Attribute{
										"entities": schema.ListNestedAttribute{
											Computed: true,
											Optional: true,
											NestedObject: schema.NestedAttributeObject{
												Validators: []validator.Object{
													speakeasy_objectvalidators.NotNull(),
												},
												Attributes: map[string]schema.Attribute{
													"enabled": schema.SingleNestedAttribute{
														Computed: true,
														Optional: true,
														Attributes: map[string]schema.Attribute{
															"boolean": schema.BoolAttribute{
																Optional: true,
																Validators: []validator.Bool{
																	boolvalidator.ConflictsWith(path.Expressions{
																		path.MatchRelative().AtParent().AtName("str"),
																	}...),
																},
															},
															"str": schema.StringAttribute{
																Optional: true,
																Validators: []validator.String{
																	stringvalidator.ConflictsWith(path.Expressions{
																		path.MatchRelative().AtParent().AtName("boolean"),
																	}...),
																},
															},
														},
														Description: `Controls whether this entity mapping should be processed. Can be a boolean or a JSONata expression (string) that evaluates to a boolean.`,
													},
													"entity_schema": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Target entity schema (e.g., 'contact', 'contract'). Not Null`,
														Validators: []validator.String{
															speakeasy_stringvalidators.NotNull(),
														},
													},
													"fields": schema.ListNestedAttribute{
														Computed: true,
														Optional: true,
														NestedObject: schema.NestedAttributeObject{
															Validators: []validator.Object{
																speakeasy_objectvalidators.NotNull(),
															},
															Attributes: map[string]schema.Attribute{
																"attribute": schema.StringAttribute{
																	Computed:    true,
																	Optional:    true,
																	Description: `Target attribute name. Not Null`,
																	Validators: []validator.String{
																		speakeasy_stringvalidators.NotNull(),
																	},
																},
																"constant": schema.StringAttribute{
																	CustomType:  jsontypes.NormalizedType{},
																	Computed:    true,
																	Optional:    true,
																	Description: `Constant value to assign (any type). Parsed as JSON.`,
																},
																"enabled": schema.SingleNestedAttribute{
																	Computed: true,
																	Optional: true,
																	Attributes: map[string]schema.Attribute{
																		"boolean": schema.BoolAttribute{
																			Optional: true,
																			Validators: []validator.Bool{
																				boolvalidator.ConflictsWith(path.Expressions{
																					path.MatchRelative().AtParent().AtName("str"),
																				}...),
																			},
																		},
																		"str": schema.StringAttribute{
																			Optional: true,
																			Validators: []validator.String{
																				stringvalidator.ConflictsWith(path.Expressions{
																					path.MatchRelative().AtParent().AtName("boolean"),
																				}...),
																			},
																		},
																	},
																	Description: `Controls whether this field mapping should be processed. Can be a boolean or a JSONata expression (string) that evaluates to a boolean. Defaults to true if omitted.`,
																},
																"field": schema.StringAttribute{
																	Computed:    true,
																	Optional:    true,
																	Description: `Source field name or JSONPath expression (if starts with $)`,
																},
																"file_proxy_url": schema.SingleNestedAttribute{
																	Computed: true,
																	Optional: true,
																	Attributes: map[string]schema.Attribute{
																		"params": schema.MapNestedAttribute{
																			Computed: true,
																			Optional: true,
																			NestedObject: schema.NestedAttributeObject{
																				Validators: []validator.Object{
																					speakeasy_objectvalidators.NotNull(),
																				},
																				Attributes: map[string]schema.Attribute{
																					"one": schema.SingleNestedAttribute{
																						Optional: true,
																						Attributes: map[string]schema.Attribute{
																							"field": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `Source field name or JSONPath expression (if starts with $). Not Null`,
																								Validators: []validator.String{
																									speakeasy_stringvalidators.NotNull(),
																								},
																							},
																						},
																						Validators: []validator.Object{
																							objectvalidator.ConflictsWith(path.Expressions{
																								path.MatchRelative().AtParent().AtName("two"),
																								path.MatchRelative().AtParent().AtName("three"),
																							}...),
																						},
																					},
																					"three": schema.SingleNestedAttribute{
																						Optional: true,
																						Attributes: map[string]schema.Attribute{
																							"jsonata_expression": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `JSONata expression for transformation. Not Null`,
																								Validators: []validator.String{
																									speakeasy_stringvalidators.NotNull(),
																								},
																							},
																						},
																						Validators: []validator.Object{
																							objectvalidator.ConflictsWith(path.Expressions{
																								path.MatchRelative().AtParent().AtName("one"),
																								path.MatchRelative().AtParent().AtName("two"),
																							}...),
																						},
																					},
																					"two": schema.SingleNestedAttribute{
																						Optional: true,
																						Attributes: map[string]schema.Attribute{
																							"constant": schema.StringAttribute{
																								CustomType:  jsontypes.NormalizedType{},
																								Computed:    true,
																								Optional:    true,
																								Description: `Constant value (any type, stringified for URL). Not Null; Parsed as JSON.`,
																								Validators: []validator.String{
																									speakeasy_stringvalidators.NotNull(),
																								},
																							},
																						},
																						Validators: []validator.Object{
																							objectvalidator.ConflictsWith(path.Expressions{
																								path.MatchRelative().AtParent().AtName("one"),
																								path.MatchRelative().AtParent().AtName("three"),
																							}...),
																						},
																					},
																				},
																			},
																			Description: `Custom query parameters. Keys become URL param names, values resolved from payload.`,
																		},
																		"use_case_id": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `UUID of the file_proxy use case. Maps to useCaseId query parameter. Not Null`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																			},
																		},
																	},
																	Description: `Auto-constructs a file proxy download URL. orgId and integrationId are injected from context.`,
																},
																"jsonata_expression": schema.StringAttribute{
																	Computed:    true,
																	Optional:    true,
																	Description: `JSONata expression for transformation`,
																},
																"relation_refs": schema.SingleNestedAttribute{
																	Computed: true,
																	Optional: true,
																	Attributes: map[string]schema.Attribute{
																		"items": schema.ListNestedAttribute{
																			Computed: true,
																			Optional: true,
																			NestedObject: schema.NestedAttributeObject{
																				Validators: []validator.Object{
																					speakeasy_objectvalidators.NotNull(),
																				},
																				Attributes: map[string]schema.Attribute{
																					"entity_schema": schema.StringAttribute{
																						Computed:    true,
																						Optional:    true,
																						Description: `Schema of the related entity (e.g., "contact"). Not Null`,
																						Validators: []validator.String{
																							speakeasy_stringvalidators.NotNull(),
																						},
																					},
																					"path": schema.StringAttribute{
																						Computed:    true,
																						Optional:    true,
																						Description: `Attribute path on the related entity (e.g., "address"). Not Null`,
																						Validators: []validator.String{
																							speakeasy_stringvalidators.NotNull(),
																						},
																					},
																					"unique_ids": schema.ListNestedAttribute{
																						Computed: true,
																						Optional: true,
																						NestedObject: schema.NestedAttributeObject{
																							Validators: []validator.Object{
																								speakeasy_objectvalidators.NotNull(),
																							},
																							Attributes: map[string]schema.Attribute{
																								"attribute": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `Target attribute name in the related entity. Not Null`,
																									Validators: []validator.String{
																										speakeasy_stringvalidators.NotNull(),
																									},
																								},
																								"constant": schema.StringAttribute{
																									CustomType:  jsontypes.NormalizedType{},
																									Computed:    true,
																									Optional:    true,
																									Description: `Constant value (any type). Parsed as JSON.`,
																								},
																								"field": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `Source field name from the event data`,
																								},
																								"jsonata_expression": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `JSONata expression to compute the value`,
																								},
																								"type": schema.StringAttribute{
																									Computed: true,
																									Optional: true,
																									MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																										`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																										`must be one of ["email", "phone"]`,
																									Validators: []validator.String{
																										stringvalidator.OneOf(
																											"email",
																											"phone",
																										),
																									},
																								},
																							},
																						},
																						Description: `Unique identifier mappings for the related entity. Not Null`,
																						Validators: []validator.List{
																							speakeasy_listvalidators.NotNull(),
																						},
																					},
																					"value": schema.SingleNestedAttribute{
																						Computed: true,
																						Optional: true,
																						Attributes: map[string]schema.Attribute{
																							"attribute": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `Target attribute name on the related entity. Not Null`,
																								Validators: []validator.String{
																									speakeasy_stringvalidators.NotNull(),
																								},
																							},
																							"constant": schema.StringAttribute{
																								CustomType:  jsontypes.NormalizedType{},
																								Computed:    true,
																								Optional:    true,
																								Description: `Constant value (any type). Parsed as JSON.`,
																							},
																							"field": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `Source field name from the event data`,
																							},
																							"jsonata_expression": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `JSONata expression to compute the value`,
																							},
																							"operation": schema.StringAttribute{
																								Computed: true,
																								Optional: true,
																								MarkdownDescription: `Operation for the attribute value:` + "\n" +
																									`- '_set': Replace the attribute value` + "\n" +
																									`- '_append': Add new unique items (deduplicates)` + "\n" +
																									`- '_append_all': Add all items (no deduplication)` + "\n" +
																									`must be one of ["_set", "_append", "_append_all"]`,
																								Validators: []validator.String{
																									stringvalidator.OneOf(
																										"_set",
																										"_append",
																										"_append_all",
																									),
																								},
																							},
																						},
																						Description: `Configuration for the value to set on the related entity's attribute. Not Null`,
																						Validators: []validator.Object{
																							speakeasy_objectvalidators.NotNull(),
																						},
																					},
																				},
																			},
																			Description: `Array of relation reference item configurations`,
																		},
																		"jsonata_expression": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `JSONata expression that returns relation_ref items array (alternative to 'items')`,
																		},
																		"operation": schema.StringAttribute{
																			Computed: true,
																			Optional: true,
																			MarkdownDescription: `Relation reference operation:` + "\n" +
																				`- '_set': Replace all existing relation_refs with the specified items` + "\n" +
																				`- '_append': Add new unique items to existing relation_refs (deduplicates by entity_id + _id)` + "\n" +
																				`- '_append_all': Add all items to existing relation_refs (no deduplication, allows duplicates)` + "\n" +
																				`Not Null; must be one of ["_set", "_append", "_append_all"]`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																				stringvalidator.OneOf(
																					"_set",
																					"_append",
																					"_append_all",
																				),
																			},
																		},
																	},
																	MarkdownDescription: `Configuration for relation references ($relation_ref).` + "\n" +
																		`Relation references link to a specific item within a repeatable attribute on a related entity.` + "\n" +
																		`Common use case: referencing a specific address within a contact's address list.`,
																},
																"relations": schema.SingleNestedAttribute{
																	Computed: true,
																	Optional: true,
																	Attributes: map[string]schema.Attribute{
																		"items": schema.ListNestedAttribute{
																			Computed: true,
																			Optional: true,
																			NestedObject: schema.NestedAttributeObject{
																				Validators: []validator.Object{
																					speakeasy_objectvalidators.NotNull(),
																				},
																				Attributes: map[string]schema.Attribute{
																					"entity_schema": schema.StringAttribute{
																						Computed:    true,
																						Optional:    true,
																						Description: `Related entity schema. Not Null`,
																						Validators: []validator.String{
																							speakeasy_stringvalidators.NotNull(),
																						},
																					},
																					"tags": schema.ListAttribute{
																						Computed:    true,
																						Optional:    true,
																						ElementType: types.StringType,
																						Description: `Optional tags for this relation`,
																					},
																					"unique_ids": schema.ListNestedAttribute{
																						Computed: true,
																						Optional: true,
																						NestedObject: schema.NestedAttributeObject{
																							Validators: []validator.Object{
																								speakeasy_objectvalidators.NotNull(),
																							},
																							Attributes: map[string]schema.Attribute{
																								"attribute": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `Target attribute name in the related entity. Not Null`,
																									Validators: []validator.String{
																										speakeasy_stringvalidators.NotNull(),
																									},
																								},
																								"constant": schema.StringAttribute{
																									CustomType:  jsontypes.NormalizedType{},
																									Computed:    true,
																									Optional:    true,
																									Description: `Constant value (any type). Parsed as JSON.`,
																								},
																								"field": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `Source field name from the event data`,
																								},
																								"jsonata_expression": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `JSONata expression to compute the value`,
																								},
																								"type": schema.StringAttribute{
																									Computed: true,
																									Optional: true,
																									MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																										`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																										`must be one of ["email", "phone"]`,
																									Validators: []validator.String{
																										stringvalidator.OneOf(
																											"email",
																											"phone",
																										),
																									},
																								},
																							},
																						},
																						Description: `Unique identifier mappings for the related entity. Not Null`,
																						Validators: []validator.List{
																							speakeasy_listvalidators.NotNull(),
																						},
																					},
																				},
																			},
																			Description: `Array of relation item configurations`,
																		},
																		"jsonata_expression": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `JSONata expression that returns relation items array (alternative to 'items')`,
																		},
																		"operation": schema.StringAttribute{
																			Computed: true,
																			Optional: true,
																			MarkdownDescription: `Relation operation:` + "\n" +
																				`- '_set': Replace all existing relations with the specified items` + "\n" +
																				`- '_append': Add new unique items to existing relations (deduplicates by entity_id)` + "\n" +
																				`- '_append_all': Add all items to existing relations (no deduplication, allows duplicates)` + "\n" +
																				`Not Null; must be one of ["_set", "_append", "_append_all"]`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																				stringvalidator.OneOf(
																					"_set",
																					"_append",
																					"_append_all",
																				),
																			},
																		},
																	},
																},
																"type": schema.StringAttribute{
																	Computed: true,
																	Optional: true,
																	MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																		`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																		`must be one of ["email", "phone"]`,
																	Validators: []validator.String{
																		stringvalidator.OneOf(
																			"email",
																			"phone",
																		),
																	},
																},
															},
														},
														Description: `Field mapping definitions. Not Null`,
														Validators: []validator.List{
															speakeasy_listvalidators.NotNull(),
														},
													},
													"jsonata_expression": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Optional JSONata expression to pre-process the event data before field mapping`,
													},
													"mode": schema.StringAttribute{
														Computed: true,
														Optional: true,
														Default:  stringdefault.StaticString(`upsert`),
														MarkdownDescription: `Operation mode for entity mapping:` + "\n" +
															`- 'upsert': Create or update the entity (default)` + "\n" +
															`- 'delete': Soft delete the entity (marks as deleted)` + "\n" +
															`- 'purge': Hard delete the entity (permanent removal)` + "\n" +
															`- 'upsert-prune-scope-purge': Upsert entities from array, then purge entities in scope that weren't upserted` + "\n" +
															`- 'upsert-prune-scope-delete': Upsert entities from array, then soft delete entities in scope that weren't upserted` + "\n" +
															`Default: "upsert"; must be one of ["upsert", "delete", "purge", "upsert-prune-scope-purge", "upsert-prune-scope-delete"]`,
														Validators: []validator.String{
															stringvalidator.OneOf(
																"upsert",
																"delete",
																"purge",
																"upsert-prune-scope-purge",
																"upsert-prune-scope-delete",
															),
														},
													},
													"scope": schema.SingleNestedAttribute{
														Computed: true,
														Optional: true,
														Attributes: map[string]schema.Attribute{
															"query": schema.ListNestedAttribute{
																Computed: true,
																Optional: true,
																NestedObject: schema.NestedAttributeObject{
																	Validators: []validator.Object{
																		speakeasy_objectvalidators.NotNull(),
																	},
																	Attributes: map[string]schema.Attribute{
																		"attribute": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `Target attribute name in the related entity. Not Null`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																			},
																		},
																		"constant": schema.StringAttribute{
																			CustomType:  jsontypes.NormalizedType{},
																			Computed:    true,
																			Optional:    true,
																			Description: `Constant value (any type). Parsed as JSON.`,
																		},
																		"field": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `Source field name from the event data`,
																		},
																		"jsonata_expression": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `JSONata expression to compute the value`,
																		},
																		"type": schema.StringAttribute{
																			Computed: true,
																			Optional: true,
																			MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																				`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																				`must be one of ["email", "phone"]`,
																			Validators: []validator.String{
																				stringvalidator.OneOf(
																					"email",
																					"phone",
																				),
																			},
																		},
																	},
																},
																MarkdownDescription: `For 'query' mode: Direct query parameters to find scope entities.` + "\n" +
																	`Not used for 'relations' or 'reverse-relations' modes.`,
															},
															"schema": schema.StringAttribute{
																Computed: true,
																Optional: true,
																MarkdownDescription: `For 'relations' mode: The schema of the entity to find (e.g., 'billing_account').` + "\n" +
																	`Not used for 'query' mode.`,
															},
															"scope_mode": schema.StringAttribute{
																Computed: true,
																Optional: true,
																MarkdownDescription: `Scope mode for finding entities to prune:` + "\n" +
																	`- 'relations': Find scope by looking at all entities related to a specific entity (both direct and reverse relations)` + "\n" +
																	`- 'query': Find scope entities directly via query parameters` + "\n" +
																	`Not Null; must be one of ["relations", "query"]`,
																Validators: []validator.String{
																	speakeasy_stringvalidators.NotNull(),
																	stringvalidator.OneOf(
																		"relations",
																		"query",
																	),
																},
															},
															"unique_ids": schema.ListNestedAttribute{
																Computed: true,
																Optional: true,
																NestedObject: schema.NestedAttributeObject{
																	Validators: []validator.Object{
																		speakeasy_objectvalidators.NotNull(),
																	},
																	Attributes: map[string]schema.Attribute{
																		"attribute": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `Target attribute name in the related entity. Not Null`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																			},
																		},
																		"constant": schema.StringAttribute{
																			CustomType:  jsontypes.NormalizedType{},
																			Computed:    true,
																			Optional:    true,
																			Description: `Constant value (any type). Parsed as JSON.`,
																		},
																		"field": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `Source field name from the event data`,
																		},
																		"jsonata_expression": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `JSONata expression to compute the value`,
																		},
																		"type": schema.StringAttribute{
																			Computed: true,
																			Optional: true,
																			MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																				`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																				`must be one of ["email", "phone"]`,
																			Validators: []validator.String{
																				stringvalidator.OneOf(
																					"email",
																					"phone",
																				),
																			},
																		},
																	},
																},
																MarkdownDescription: `For 'relations' mode: How to identify the scope entity from the payload.` + "\n" +
																	`Not used for 'query' mode.`,
															},
														},
														MarkdownDescription: `Scope configuration for upsert-prune-scope modes.` + "\n" +
															`Defines how to find entities that should be pruned if not in the upsert payload.` + "\n" +
															`The scope is resolved against the original event payload (not individual array items).`,
													},
													"unique_ids": schema.ListAttribute{
														Computed:    true,
														Optional:    true,
														ElementType: types.StringType,
														MarkdownDescription: `Array of attribute names that uniquely identify this entity.` + "\n" +
															`The _type hint for repeatable fields (e.g., email, phone) should be specified` + "\n" +
															`on the corresponding field definition in the fields array.` + "\n" +
															`Not Null`,
														Validators: []validator.List{
															speakeasy_listvalidators.NotNull(),
														},
													},
												},
											},
											Description: `Array of entity configurations for this event`,
										},
										"meter_readings": schema.ListNestedAttribute{
											Computed: true,
											Optional: true,
											NestedObject: schema.NestedAttributeObject{
												Validators: []validator.Object{
													speakeasy_objectvalidators.NotNull(),
												},
												Attributes: map[string]schema.Attribute{
													"fields": schema.ListNestedAttribute{
														Computed: true,
														Optional: true,
														NestedObject: schema.NestedAttributeObject{
															Validators: []validator.Object{
																speakeasy_objectvalidators.NotNull(),
															},
															Attributes: map[string]schema.Attribute{
																"attribute": schema.StringAttribute{
																	Computed:    true,
																	Optional:    true,
																	Description: `Target attribute name. Not Null`,
																	Validators: []validator.String{
																		speakeasy_stringvalidators.NotNull(),
																	},
																},
																"constant": schema.StringAttribute{
																	CustomType:  jsontypes.NormalizedType{},
																	Computed:    true,
																	Optional:    true,
																	Description: `Constant value to assign (any type). Parsed as JSON.`,
																},
																"enabled": schema.SingleNestedAttribute{
																	Computed: true,
																	Optional: true,
																	Attributes: map[string]schema.Attribute{
																		"boolean": schema.BoolAttribute{
																			Optional: true,
																			Validators: []validator.Bool{
																				boolvalidator.ConflictsWith(path.Expressions{
																					path.MatchRelative().AtParent().AtName("str"),
																				}...),
																			},
																		},
																		"str": schema.StringAttribute{
																			Optional: true,
																			Validators: []validator.String{
																				stringvalidator.ConflictsWith(path.Expressions{
																					path.MatchRelative().AtParent().AtName("boolean"),
																				}...),
																			},
																		},
																	},
																	Description: `Controls whether this field mapping should be processed. Can be a boolean or a JSONata expression (string) that evaluates to a boolean. Defaults to true if omitted.`,
																},
																"field": schema.StringAttribute{
																	Computed:    true,
																	Optional:    true,
																	Description: `Source field name or JSONPath expression (if starts with $)`,
																},
																"file_proxy_url": schema.SingleNestedAttribute{
																	Computed: true,
																	Optional: true,
																	Attributes: map[string]schema.Attribute{
																		"params": schema.MapNestedAttribute{
																			Computed: true,
																			Optional: true,
																			NestedObject: schema.NestedAttributeObject{
																				Validators: []validator.Object{
																					speakeasy_objectvalidators.NotNull(),
																				},
																				Attributes: map[string]schema.Attribute{
																					"one": schema.SingleNestedAttribute{
																						Optional: true,
																						Attributes: map[string]schema.Attribute{
																							"field": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `Source field name or JSONPath expression (if starts with $). Not Null`,
																								Validators: []validator.String{
																									speakeasy_stringvalidators.NotNull(),
																								},
																							},
																						},
																						Validators: []validator.Object{
																							objectvalidator.ConflictsWith(path.Expressions{
																								path.MatchRelative().AtParent().AtName("two"),
																								path.MatchRelative().AtParent().AtName("three"),
																							}...),
																						},
																					},
																					"three": schema.SingleNestedAttribute{
																						Optional: true,
																						Attributes: map[string]schema.Attribute{
																							"jsonata_expression": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `JSONata expression for transformation. Not Null`,
																								Validators: []validator.String{
																									speakeasy_stringvalidators.NotNull(),
																								},
																							},
																						},
																						Validators: []validator.Object{
																							objectvalidator.ConflictsWith(path.Expressions{
																								path.MatchRelative().AtParent().AtName("one"),
																								path.MatchRelative().AtParent().AtName("two"),
																							}...),
																						},
																					},
																					"two": schema.SingleNestedAttribute{
																						Optional: true,
																						Attributes: map[string]schema.Attribute{
																							"constant": schema.StringAttribute{
																								CustomType:  jsontypes.NormalizedType{},
																								Computed:    true,
																								Optional:    true,
																								Description: `Constant value (any type, stringified for URL). Not Null; Parsed as JSON.`,
																								Validators: []validator.String{
																									speakeasy_stringvalidators.NotNull(),
																								},
																							},
																						},
																						Validators: []validator.Object{
																							objectvalidator.ConflictsWith(path.Expressions{
																								path.MatchRelative().AtParent().AtName("one"),
																								path.MatchRelative().AtParent().AtName("three"),
																							}...),
																						},
																					},
																				},
																			},
																			Description: `Custom query parameters. Keys become URL param names, values resolved from payload.`,
																		},
																		"use_case_id": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `UUID of the file_proxy use case. Maps to useCaseId query parameter. Not Null`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																			},
																		},
																	},
																	Description: `Auto-constructs a file proxy download URL. orgId and integrationId are injected from context.`,
																},
																"jsonata_expression": schema.StringAttribute{
																	Computed:    true,
																	Optional:    true,
																	Description: `JSONata expression for transformation`,
																},
																"relation_refs": schema.SingleNestedAttribute{
																	Computed: true,
																	Optional: true,
																	Attributes: map[string]schema.Attribute{
																		"items": schema.ListNestedAttribute{
																			Computed: true,
																			Optional: true,
																			NestedObject: schema.NestedAttributeObject{
																				Validators: []validator.Object{
																					speakeasy_objectvalidators.NotNull(),
																				},
																				Attributes: map[string]schema.Attribute{
																					"entity_schema": schema.StringAttribute{
																						Computed:    true,
																						Optional:    true,
																						Description: `Schema of the related entity (e.g., "contact"). Not Null`,
																						Validators: []validator.String{
																							speakeasy_stringvalidators.NotNull(),
																						},
																					},
																					"path": schema.StringAttribute{
																						Computed:    true,
																						Optional:    true,
																						Description: `Attribute path on the related entity (e.g., "address"). Not Null`,
																						Validators: []validator.String{
																							speakeasy_stringvalidators.NotNull(),
																						},
																					},
																					"unique_ids": schema.ListNestedAttribute{
																						Computed: true,
																						Optional: true,
																						NestedObject: schema.NestedAttributeObject{
																							Validators: []validator.Object{
																								speakeasy_objectvalidators.NotNull(),
																							},
																							Attributes: map[string]schema.Attribute{
																								"attribute": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `Target attribute name in the related entity. Not Null`,
																									Validators: []validator.String{
																										speakeasy_stringvalidators.NotNull(),
																									},
																								},
																								"constant": schema.StringAttribute{
																									CustomType:  jsontypes.NormalizedType{},
																									Computed:    true,
																									Optional:    true,
																									Description: `Constant value (any type). Parsed as JSON.`,
																								},
																								"field": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `Source field name from the event data`,
																								},
																								"jsonata_expression": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `JSONata expression to compute the value`,
																								},
																								"type": schema.StringAttribute{
																									Computed: true,
																									Optional: true,
																									MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																										`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																										`must be one of ["email", "phone"]`,
																									Validators: []validator.String{
																										stringvalidator.OneOf(
																											"email",
																											"phone",
																										),
																									},
																								},
																							},
																						},
																						Description: `Unique identifier mappings for the related entity. Not Null`,
																						Validators: []validator.List{
																							speakeasy_listvalidators.NotNull(),
																						},
																					},
																					"value": schema.SingleNestedAttribute{
																						Computed: true,
																						Optional: true,
																						Attributes: map[string]schema.Attribute{
																							"attribute": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `Target attribute name on the related entity. Not Null`,
																								Validators: []validator.String{
																									speakeasy_stringvalidators.NotNull(),
																								},
																							},
																							"constant": schema.StringAttribute{
																								CustomType:  jsontypes.NormalizedType{},
																								Computed:    true,
																								Optional:    true,
																								Description: `Constant value (any type). Parsed as JSON.`,
																							},
																							"field": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `Source field name from the event data`,
																							},
																							"jsonata_expression": schema.StringAttribute{
																								Computed:    true,
																								Optional:    true,
																								Description: `JSONata expression to compute the value`,
																							},
																							"operation": schema.StringAttribute{
																								Computed: true,
																								Optional: true,
																								MarkdownDescription: `Operation for the attribute value:` + "\n" +
																									`- '_set': Replace the attribute value` + "\n" +
																									`- '_append': Add new unique items (deduplicates)` + "\n" +
																									`- '_append_all': Add all items (no deduplication)` + "\n" +
																									`must be one of ["_set", "_append", "_append_all"]`,
																								Validators: []validator.String{
																									stringvalidator.OneOf(
																										"_set",
																										"_append",
																										"_append_all",
																									),
																								},
																							},
																						},
																						Description: `Configuration for the value to set on the related entity's attribute. Not Null`,
																						Validators: []validator.Object{
																							speakeasy_objectvalidators.NotNull(),
																						},
																					},
																				},
																			},
																			Description: `Array of relation reference item configurations`,
																		},
																		"jsonata_expression": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `JSONata expression that returns relation_ref items array (alternative to 'items')`,
																		},
																		"operation": schema.StringAttribute{
																			Computed: true,
																			Optional: true,
																			MarkdownDescription: `Relation reference operation:` + "\n" +
																				`- '_set': Replace all existing relation_refs with the specified items` + "\n" +
																				`- '_append': Add new unique items to existing relation_refs (deduplicates by entity_id + _id)` + "\n" +
																				`- '_append_all': Add all items to existing relation_refs (no deduplication, allows duplicates)` + "\n" +
																				`Not Null; must be one of ["_set", "_append", "_append_all"]`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																				stringvalidator.OneOf(
																					"_set",
																					"_append",
																					"_append_all",
																				),
																			},
																		},
																	},
																	MarkdownDescription: `Configuration for relation references ($relation_ref).` + "\n" +
																		`Relation references link to a specific item within a repeatable attribute on a related entity.` + "\n" +
																		`Common use case: referencing a specific address within a contact's address list.`,
																},
																"relations": schema.SingleNestedAttribute{
																	Computed: true,
																	Optional: true,
																	Attributes: map[string]schema.Attribute{
																		"items": schema.ListNestedAttribute{
																			Computed: true,
																			Optional: true,
																			NestedObject: schema.NestedAttributeObject{
																				Validators: []validator.Object{
																					speakeasy_objectvalidators.NotNull(),
																				},
																				Attributes: map[string]schema.Attribute{
																					"entity_schema": schema.StringAttribute{
																						Computed:    true,
																						Optional:    true,
																						Description: `Related entity schema. Not Null`,
																						Validators: []validator.String{
																							speakeasy_stringvalidators.NotNull(),
																						},
																					},
																					"tags": schema.ListAttribute{
																						Computed:    true,
																						Optional:    true,
																						ElementType: types.StringType,
																						Description: `Optional tags for this relation`,
																					},
																					"unique_ids": schema.ListNestedAttribute{
																						Computed: true,
																						Optional: true,
																						NestedObject: schema.NestedAttributeObject{
																							Validators: []validator.Object{
																								speakeasy_objectvalidators.NotNull(),
																							},
																							Attributes: map[string]schema.Attribute{
																								"attribute": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `Target attribute name in the related entity. Not Null`,
																									Validators: []validator.String{
																										speakeasy_stringvalidators.NotNull(),
																									},
																								},
																								"constant": schema.StringAttribute{
																									CustomType:  jsontypes.NormalizedType{},
																									Computed:    true,
																									Optional:    true,
																									Description: `Constant value (any type). Parsed as JSON.`,
																								},
																								"field": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `Source field name from the event data`,
																								},
																								"jsonata_expression": schema.StringAttribute{
																									Computed:    true,
																									Optional:    true,
																									Description: `JSONata expression to compute the value`,
																								},
																								"type": schema.StringAttribute{
																									Computed: true,
																									Optional: true,
																									MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																										`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																										`must be one of ["email", "phone"]`,
																									Validators: []validator.String{
																										stringvalidator.OneOf(
																											"email",
																											"phone",
																										),
																									},
																								},
																							},
																						},
																						Description: `Unique identifier mappings for the related entity. Not Null`,
																						Validators: []validator.List{
																							speakeasy_listvalidators.NotNull(),
																						},
																					},
																				},
																			},
																			Description: `Array of relation item configurations`,
																		},
																		"jsonata_expression": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `JSONata expression that returns relation items array (alternative to 'items')`,
																		},
																		"operation": schema.StringAttribute{
																			Computed: true,
																			Optional: true,
																			MarkdownDescription: `Relation operation:` + "\n" +
																				`- '_set': Replace all existing relations with the specified items` + "\n" +
																				`- '_append': Add new unique items to existing relations (deduplicates by entity_id)` + "\n" +
																				`- '_append_all': Add all items to existing relations (no deduplication, allows duplicates)` + "\n" +
																				`Not Null; must be one of ["_set", "_append", "_append_all"]`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																				stringvalidator.OneOf(
																					"_set",
																					"_append",
																					"_append_all",
																				),
																			},
																		},
																	},
																},
																"type": schema.StringAttribute{
																	Computed: true,
																	Optional: true,
																	MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																		`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																		`must be one of ["email", "phone"]`,
																	Validators: []validator.String{
																		stringvalidator.OneOf(
																			"email",
																			"phone",
																		),
																	},
																},
															},
														},
														Description: `Field mapping definitions for meter reading attributes. Not Null`,
														Validators: []validator.List{
															speakeasy_listvalidators.NotNull(),
														},
													},
													"jsonata_expression": schema.StringAttribute{
														Computed: true,
														Optional: true,
														MarkdownDescription: `Optional JSONata expression to extract meter reading items from the event data.` + "\n" +
															`If not provided, the entire payload is used as the reading data.` + "\n" +
															`Useful when you need to extract an array of readings from a nested structure (e.g., "$.readings").`,
													},
													"meter": schema.SingleNestedAttribute{
														Computed: true,
														Optional: true,
														Attributes: map[string]schema.Attribute{
															"unique_ids": schema.ListNestedAttribute{
																Computed: true,
																Optional: true,
																NestedObject: schema.NestedAttributeObject{
																	Validators: []validator.Object{
																		speakeasy_objectvalidators.NotNull(),
																	},
																	Attributes: map[string]schema.Attribute{
																		"attribute": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `Target attribute name in the related entity. Not Null`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																			},
																		},
																		"constant": schema.StringAttribute{
																			CustomType:  jsontypes.NormalizedType{},
																			Computed:    true,
																			Optional:    true,
																			Description: `Constant value (any type). Parsed as JSON.`,
																		},
																		"field": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `Source field name from the event data`,
																		},
																		"jsonata_expression": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `JSONata expression to compute the value`,
																		},
																		"type": schema.StringAttribute{
																			Computed: true,
																			Optional: true,
																			MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																				`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																				`must be one of ["email", "phone"]`,
																			Validators: []validator.String{
																				stringvalidator.OneOf(
																					"email",
																					"phone",
																				),
																			},
																		},
																	},
																},
																Description: `Array of unique identifier field mappings. Not Null`,
																Validators: []validator.List{
																	speakeasy_listvalidators.NotNull(),
																	listvalidator.SizeAtLeast(1),
																},
															},
														},
														Description: `Not Null`,
														Validators: []validator.Object{
															speakeasy_objectvalidators.NotNull(),
														},
													},
													"meter_counter": schema.SingleNestedAttribute{
														Computed: true,
														Optional: true,
														Attributes: map[string]schema.Attribute{
															"unique_ids": schema.ListNestedAttribute{
																Computed: true,
																Optional: true,
																NestedObject: schema.NestedAttributeObject{
																	Validators: []validator.Object{
																		speakeasy_objectvalidators.NotNull(),
																	},
																	Attributes: map[string]schema.Attribute{
																		"attribute": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `Target attribute name in the related entity. Not Null`,
																			Validators: []validator.String{
																				speakeasy_stringvalidators.NotNull(),
																			},
																		},
																		"constant": schema.StringAttribute{
																			CustomType:  jsontypes.NormalizedType{},
																			Computed:    true,
																			Optional:    true,
																			Description: `Constant value (any type). Parsed as JSON.`,
																		},
																		"field": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `Source field name from the event data`,
																		},
																		"jsonata_expression": schema.StringAttribute{
																			Computed:    true,
																			Optional:    true,
																			Description: `JSONata expression to compute the value`,
																		},
																		"type": schema.StringAttribute{
																			Computed: true,
																			Optional: true,
																			MarkdownDescription: `Type hint for repeatable fields that require special search handling.` + "\n" +
																				`These fields are stored as arrays of objects (e.g., email: [{ email: "value" }]).` + "\n" +
																				`must be one of ["email", "phone"]`,
																			Validators: []validator.String{
																				stringvalidator.OneOf(
																					"email",
																					"phone",
																				),
																			},
																		},
																	},
																},
																Description: `Array of unique identifier field mappings. Not Null`,
																Validators: []validator.List{
																	speakeasy_listvalidators.NotNull(),
																	listvalidator.SizeAtLeast(1),
																},
															},
														},
													},
													"mode": schema.StringAttribute{
														Computed: true,
														Optional: true,
														Default:  stringdefault.StaticString(`upsert`),
														MarkdownDescription: `Operation mode for meter reading mapping:` + "\n" +
															`- 'upsert': Create or update meter readings (default)` + "\n" +
															`- 'delete': Delete the meter reading` + "\n" +
															`- 'upsert-prune-scope': Upsert readings from array, then delete all other readings for the same meter+counter that weren't upserted` + "\n" +
															`Default: "upsert"; must be one of ["upsert", "delete", "upsert-prune-scope"]`,
														Validators: []validator.String{
															stringvalidator.OneOf(
																"upsert",
																"delete",
																"upsert-prune-scope",
															),
														},
													},
													"reading_matching": schema.StringAttribute{
														Computed: true,
														Optional: true,
														Default:  stringdefault.StaticString(`external_id`),
														MarkdownDescription: `Strategy for matching incoming readings against existing readings.` + "\n" +
															`- 'external_id': Match readings by external_id attribute (default behavior)` + "\n" +
															`- 'strict-date': Match by meter_id + counter_id + direction + date (German timezone).` + "\n" +
															`  Useful when readings originate from ECP and are echoed back by the ERP with truncated timestamps.` + "\n" +
															`Default: "external_id"; must be one of ["external_id", "strict-date"]`,
														Validators: []validator.String{
															stringvalidator.OneOf(
																"external_id",
																"strict-date",
															),
														},
													},
													"scope": schema.SingleNestedAttribute{
														Computed: true,
														Optional: true,
														Attributes: map[string]schema.Attribute{
															"source": schema.StringAttribute{
																Computed: true,
																Optional: true,
																MarkdownDescription: `Optional source filter. When set, only readings with this source` + "\n" +
																	`are eligible for pruning (e.g., 'ERP' to only prune ERP-synced readings).`,
															},
														},
														MarkdownDescription: `Scope configuration for meter reading upsert-prune-scope mode.` + "\n" +
															`The scope is all readings for the same meter + counter.`,
													},
												},
											},
											Description: `Array of meter reading configurations for this event`,
										},
									},
									Description: `Configuration for inbound use cases (ERP to epilot)`,
								},
								"created_at": schema.StringAttribute{
									Computed:    true,
									Description: `ISO-8601 timestamp when the use case was created`,
								},
								"enabled": schema.BoolAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Whether the use case is enabled. Not Null`,
									Validators: []validator.Bool{
										speakeasy_boolvalidators.NotNull(),
									},
								},
								"id": schema.StringAttribute{
									Computed: true,
									Optional: true,
									MarkdownDescription: `Optional use case ID for update matching.` + "\n" +
										`- If provided and matches an existing use case, that use case is updated` + "\n" +
										`- If provided but no match, a new use case with this ID is created` + "\n" +
										`- If omitted, a new use case with auto-generated ID is created`,
								},
								"integration_id": schema.StringAttribute{
									Computed:    true,
									Description: `Parent integration ID`,
								},
								"name": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Use case name. Not Null`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
										stringvalidator.UTF8LengthBetween(1, 255),
									},
								},
								"type": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Use case type. Not Null; must be "inbound"`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
										stringvalidator.OneOf("inbound"),
									},
								},
								"updated_at": schema.StringAttribute{
									Computed:    true,
									Description: `ISO-8601 timestamp when the use case was last updated`,
								},
							},
							Validators: []validator.Object{
								objectvalidator.ConflictsWith(path.Expressions{
									path.MatchRelative().AtParent().AtName("outbound"),
									path.MatchRelative().AtParent().AtName("file_proxy_use_case"),
								}...),
							},
						},
						"outbound": schema.SingleNestedAttribute{
							Optional: true,
							Attributes: map[string]schema.Attribute{
								"change_description": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Optional description of this change (like a commit message)`,
									Validators: []validator.String{
										stringvalidator.UTF8LengthAtMost(2000),
									},
								},
								"configuration": schema.SingleNestedAttribute{
									Computed: true,
									Optional: true,
									Attributes: map[string]schema.Attribute{
										"event_catalog_event": schema.StringAttribute{
											Computed:    true,
											Optional:    true,
											Description: `The Event Catalog event name that triggers this outbound flow. Not Null`,
											Validators: []validator.String{
												speakeasy_stringvalidators.NotNull(),
											},
										},
										"mappings": schema.ListNestedAttribute{
											Computed: true,
											Optional: true,
											NestedObject: schema.NestedAttributeObject{
												Validators: []validator.Object{
													speakeasy_objectvalidators.NotNull(),
												},
												Attributes: map[string]schema.Attribute{
													"created_at": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Timestamp when the mapping was created`,
														Validators: []validator.String{
															validators.IsRFC3339(),
														},
													},
													"delivery": schema.SingleNestedAttribute{
														Computed: true,
														Optional: true,
														Attributes: map[string]schema.Attribute{
															"type": schema.StringAttribute{
																Computed:    true,
																Optional:    true,
																Description: `Delivery mechanism type (currently only webhook is supported). Not Null; must be "webhook"`,
																Validators: []validator.String{
																	speakeasy_stringvalidators.NotNull(),
																	stringvalidator.OneOf("webhook"),
																},
															},
															"webhook_id": schema.StringAttribute{
																Computed:    true,
																Optional:    true,
																Description: `Reference to the webhook configuration in svc-webhooks. Not Null`,
																Validators: []validator.String{
																	speakeasy_stringvalidators.NotNull(),
																},
															},
															"webhook_name": schema.StringAttribute{
																Computed:    true,
																Optional:    true,
																Description: `Cached webhook name for display purposes`,
															},
															"webhook_url": schema.StringAttribute{
																Computed:    true,
																Optional:    true,
																Description: `Cached webhook URL for display purposes`,
															},
														},
														Description: `Configuration for how the transformed event should be delivered. Not Null`,
														Validators: []validator.Object{
															speakeasy_objectvalidators.NotNull(),
														},
													},
													"enabled": schema.BoolAttribute{
														Computed:    true,
														Optional:    true,
														Default:     booldefault.StaticBool(true),
														Description: `Whether this mapping is active. Default: true`,
													},
													"id": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Unique identifier for this mapping. Not Null`,
														Validators: []validator.String{
															speakeasy_stringvalidators.NotNull(),
														},
													},
													"jsonata_expression": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `JSONata expression to transform the event payload. Not Null`,
														Validators: []validator.String{
															speakeasy_stringvalidators.NotNull(),
														},
													},
													"name": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Human-readable name for this mapping. Not Null`,
														Validators: []validator.String{
															speakeasy_stringvalidators.NotNull(),
														},
													},
													"updated_at": schema.StringAttribute{
														Computed:    true,
														Optional:    true,
														Description: `Timestamp when the mapping was last updated`,
														Validators: []validator.String{
															validators.IsRFC3339(),
														},
													},
												},
											},
											Description: `List of mappings that transform and deliver the event. Not Null`,
											Validators: []validator.List{
												speakeasy_listvalidators.NotNull(),
												listvalidator.SizeAtLeast(1),
											},
										},
									},
									Description: `Configuration for outbound use cases. Defines the event that triggers the flow and the webhook mappings.`,
								},
								"created_at": schema.StringAttribute{
									Computed:    true,
									Description: `ISO-8601 timestamp when the use case was created`,
								},
								"enabled": schema.BoolAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Whether the use case is enabled. Not Null`,
									Validators: []validator.Bool{
										speakeasy_boolvalidators.NotNull(),
									},
								},
								"id": schema.StringAttribute{
									Computed: true,
									Optional: true,
									MarkdownDescription: `Optional use case ID for update matching.` + "\n" +
										`- If provided and matches an existing use case, that use case is updated` + "\n" +
										`- If provided but no match, a new use case with this ID is created` + "\n" +
										`- If omitted, a new use case with auto-generated ID is created`,
								},
								"integration_id": schema.StringAttribute{
									Computed:    true,
									Description: `Parent integration ID`,
								},
								"name": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Use case name. Not Null`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
										stringvalidator.UTF8LengthBetween(1, 255),
									},
								},
								"type": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Use case type. Not Null; must be "outbound"`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
										stringvalidator.OneOf("outbound"),
									},
								},
								"updated_at": schema.StringAttribute{
									Computed:    true,
									Description: `ISO-8601 timestamp when the use case was last updated`,
								},
							},
							Validators: []validator.Object{
								objectvalidator.ConflictsWith(path.Expressions{
									path.MatchRelative().AtParent().AtName("inbound"),
									path.MatchRelative().AtParent().AtName("file_proxy_use_case"),
								}...),
							},
						},
					},
				},
				MarkdownDescription: `Full list of use cases (declarative). This replaces ALL existing use cases.` + "\n" +
					`- Use cases with an ` + "`" + `id` + "`" + ` field matching an existing use case will be updated` + "\n" +
					`- Use cases without an ` + "`" + `id` + "`" + ` or with a non-matching ` + "`" + `id` + "`" + ` will be created` + "\n" +
					`- Existing use cases not in this list will be deleted`,
			},
		},
	}
}

func (r *IntegrationResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *IntegrationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *IntegrationResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToSharedUpsertIntegrationWithUseCasesRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Integrations.CreateIntegrationV2(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 201 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.IntegrationWithUseCases != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedIntegrationWithUseCases(ctx, res.IntegrationWithUseCases)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IntegrationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *IntegrationResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetIntegrationV2Request(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Integrations.GetIntegrationV2(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.IntegrationWithUseCases != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedIntegrationWithUseCases(ctx, res.IntegrationWithUseCases)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IntegrationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *IntegrationResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsUpdateIntegrationV2Request(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Integrations.UpdateIntegrationV2(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.IntegrationWithUseCases != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedIntegrationWithUseCases(ctx, res.IntegrationWithUseCases)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IntegrationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *IntegrationResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsDeleteIntegrationV2Request(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Integrations.DeleteIntegrationV2(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 200, 404:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *IntegrationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
