// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &IntegrationDataSource{}
var _ datasource.DataSourceWithConfigure = &IntegrationDataSource{}

func NewIntegrationDataSource() datasource.DataSource {
	return &IntegrationDataSource{}
}

// IntegrationDataSource is the data source implementation.
type IntegrationDataSource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// IntegrationDataSourceModel describes the data model.
type IntegrationDataSourceModel struct {
	AccessTokenIds    []types.String               `tfsdk:"access_token_ids"`
	AppIds            []types.String               `tfsdk:"app_ids"`
	CreatedAt         types.String                 `tfsdk:"created_at"`
	Description       types.String                 `tfsdk:"description"`
	EnvironmentConfig jsontypes.Normalized         `tfsdk:"environment_config"`
	ID                types.String                 `tfsdk:"id"`
	Name              types.String                 `tfsdk:"name"`
	OrgID             types.String                 `tfsdk:"org_id"`
	Settings          *tfTypes.IntegrationSettings `tfsdk:"settings"`
	UpdatedAt         types.String                 `tfsdk:"updated_at"`
	UseCases          jsontypes.Normalized         `tfsdk:"use_cases"`
}

// Metadata returns the data source type name.
func (r *IntegrationDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_integration"
}

// Schema defines the schema for the data source.
func (r *IntegrationDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Integration DataSource",

		Attributes: map[string]schema.Attribute{
			"access_token_ids": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `List of access token IDs associated with this integration`,
			},
			"app_ids": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `List of app IDs associated with this integration`,
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `ISO-8601 timestamp when the integration was created`,
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: `Optional description of the integration`,
			},
			"environment_config": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `Unique identifier for the integration`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Integration name`,
			},
			"org_id": schema.StringAttribute{
				Computed:    true,
				Description: `Organization ID`,
			},
			"settings": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"auto_refresh": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Computed:    true,
								Description: `Whether auto-refresh is enabled`,
							},
							"freshness_threshold_minutes": schema.Int64Attribute{
								Computed:    true,
								Description: `Maximum age (in minutes) of data before it is considered stale and eligible for refresh`,
							},
						},
						Description: `Auto-refresh settings for keeping integration data fresh`,
					},
				},
				Description: `Settings for the integration`,
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `ISO-8601 timestamp when the integration was last updated`,
			},
			"use_cases": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
		},
	}
}

func (r *IntegrationDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *IntegrationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *IntegrationDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetIntegrationV2Request(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Integrations.GetIntegrationV2(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.IntegrationWithUseCases != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedIntegrationWithUseCases(ctx, res.IntegrationWithUseCases)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
