// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *IntegrationDataSourceModel) RefreshFromSharedIntegrationWithUseCases(ctx context.Context, resp *shared.IntegrationWithUseCases) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AccessTokenIds = make([]types.String, 0, len(resp.AccessTokenIds))
		for _, v := range resp.AccessTokenIds {
			r.AccessTokenIds = append(r.AccessTokenIds, types.StringValue(v))
		}
		r.AppIds = make([]types.String, 0, len(resp.AppIds))
		for _, v := range resp.AppIds {
			r.AppIds = append(r.AppIds, types.StringValue(v))
		}
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.Description = types.StringPointerValue(resp.Description)
		if resp.EnvironmentConfig == nil {
			r.EnvironmentConfig = jsontypes.NewNormalizedNull()
		} else {
			environmentConfigResult, _ := json.Marshal(resp.EnvironmentConfig)
			r.EnvironmentConfig = jsontypes.NewNormalizedValue(string(environmentConfigResult))
		}
		r.ID = types.StringValue(resp.ID)
		r.Name = types.StringValue(resp.Name)
		r.OrgID = types.StringValue(resp.OrgID)
		if resp.Settings == nil {
			r.Settings = nil
		} else {
			r.Settings = &tfTypes.IntegrationSettings{}
			if resp.Settings.AutoRefresh == nil {
				r.Settings.AutoRefresh = nil
			} else {
				r.Settings.AutoRefresh = &tfTypes.AutoRefreshSettings{}
				r.Settings.AutoRefresh.Enabled = types.BoolPointerValue(resp.Settings.AutoRefresh.Enabled)
				r.Settings.AutoRefresh.FreshnessThresholdMinutes = types.Int64PointerValue(resp.Settings.AutoRefresh.FreshnessThresholdMinutes)
			}
		}
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
		useCasesResult, _ := json.Marshal(resp.UseCases)
		r.UseCases = jsontypes.NewNormalizedValue(string(useCasesResult))
	}

	return diags
}

func (r *IntegrationDataSourceModel) ToOperationsGetIntegrationV2Request(ctx context.Context) (*operations.GetIntegrationV2Request, diag.Diagnostics) {
	var diags diag.Diagnostics

	var integrationID string
	integrationID = r.ID.ValueString()

	out := operations.GetIntegrationV2Request{
		IntegrationID: integrationID,
	}

	return &out, diags
}
