// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-erp-integration/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *IntegrationResourceModel) RefreshFromSharedIntegrationWithUseCases(ctx context.Context, resp *shared.IntegrationWithUseCases) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Manifest = make([]types.String, 0, len(resp.Manifest))
		for _, v := range resp.Manifest {
			r.Manifest = append(r.Manifest, types.StringValue(v))
		}
		r.AccessTokenIds = make([]types.String, 0, len(resp.AccessTokenIds))
		for _, v := range resp.AccessTokenIds {
			r.AccessTokenIds = append(r.AccessTokenIds, types.StringValue(v))
		}
		r.AppIds = make([]types.String, 0, len(resp.AppIds))
		for _, v := range resp.AppIds {
			r.AppIds = append(r.AppIds, types.StringValue(v))
		}
		if resp.ConnectorConfig == nil {
			r.ConnectorConfig = nil
		} else {
			r.ConnectorConfig = &tfTypes.ConnectorConfig{}
			if resp.ConnectorConfig.Auth == nil {
				r.ConnectorConfig.Auth = nil
			} else {
				r.ConnectorConfig.Auth = &tfTypes.ManagedCallAuth{}
				r.ConnectorConfig.Auth.APIKey = types.StringPointerValue(resp.ConnectorConfig.Auth.APIKey)
				r.ConnectorConfig.Auth.APIKeyHeader = types.StringPointerValue(resp.ConnectorConfig.Auth.APIKeyHeader)
				r.ConnectorConfig.Auth.Audience = types.StringPointerValue(resp.ConnectorConfig.Auth.Audience)
				if len(resp.ConnectorConfig.Auth.BodyParams) > 0 {
					r.ConnectorConfig.Auth.BodyParams = make(map[string]types.String, len(resp.ConnectorConfig.Auth.BodyParams))
					for key, value := range resp.ConnectorConfig.Auth.BodyParams {
						r.ConnectorConfig.Auth.BodyParams[key] = types.StringValue(value)
					}
				}
				r.ConnectorConfig.Auth.ClientID = types.StringPointerValue(resp.ConnectorConfig.Auth.ClientID)
				r.ConnectorConfig.Auth.ClientSecret = types.StringPointerValue(resp.ConnectorConfig.Auth.ClientSecret)
				if len(resp.ConnectorConfig.Auth.Headers) > 0 {
					r.ConnectorConfig.Auth.Headers = make(map[string]types.String, len(resp.ConnectorConfig.Auth.Headers))
					for key1, value1 := range resp.ConnectorConfig.Auth.Headers {
						r.ConnectorConfig.Auth.Headers[key1] = types.StringValue(value1)
					}
				}
				if len(resp.ConnectorConfig.Auth.QueryParams) > 0 {
					r.ConnectorConfig.Auth.QueryParams = make(map[string]types.String, len(resp.ConnectorConfig.Auth.QueryParams))
					for key2, value2 := range resp.ConnectorConfig.Auth.QueryParams {
						r.ConnectorConfig.Auth.QueryParams[key2] = types.StringValue(value2)
					}
				}
				r.ConnectorConfig.Auth.Resource = types.StringPointerValue(resp.ConnectorConfig.Auth.Resource)
				r.ConnectorConfig.Auth.Scope = types.StringPointerValue(resp.ConnectorConfig.Auth.Scope)
				r.ConnectorConfig.Auth.Token = types.StringPointerValue(resp.ConnectorConfig.Auth.Token)
				r.ConnectorConfig.Auth.TokenURL = types.StringPointerValue(resp.ConnectorConfig.Auth.TokenURL)
				if resp.ConnectorConfig.Auth.Type != nil {
					r.ConnectorConfig.Auth.Type = types.StringValue(string(*resp.ConnectorConfig.Auth.Type))
				} else {
					r.ConnectorConfig.Auth.Type = types.StringNull()
				}
			}
			r.ConnectorConfig.BaseURL = types.StringPointerValue(resp.ConnectorConfig.BaseURL)
			r.ConnectorConfig.LatestTypesPackageName = types.StringPointerValue(resp.ConnectorConfig.LatestTypesPackageName)
			r.ConnectorConfig.LatestTypesVersion = types.StringPointerValue(resp.ConnectorConfig.LatestTypesVersion)
			r.ConnectorConfig.TypesVersions = []tfTypes.TypesVersions{}

			for _, typesVersionsItem := range resp.ConnectorConfig.TypesVersions {
				var typesVersions tfTypes.TypesVersions

				typesVersions.GeneratedAt = types.StringValue(typeconvert.TimeToString(typesVersionsItem.GeneratedAt))
				typesVersions.GeneratedBy = types.StringValue(typesVersionsItem.GeneratedBy)
				typesVersions.PackageName = types.StringValue(typesVersionsItem.PackageName)
				typesVersions.Status = types.StringValue(string(typesVersionsItem.Status))
				typesVersions.Version = types.StringValue(typesVersionsItem.Version)

				r.ConnectorConfig.TypesVersions = append(r.ConnectorConfig.TypesVersions, typesVersions)
			}
		}
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.Description = types.StringPointerValue(resp.Description)
		if resp.EnvironmentConfig == nil {
			r.EnvironmentConfig = jsontypes.NewNormalizedNull()
		} else {
			environmentConfigResult, _ := json.Marshal(resp.EnvironmentConfig)
			r.EnvironmentConfig = jsontypes.NewNormalizedValue(string(environmentConfigResult))
		}
		r.ID = types.StringValue(resp.ID)
		if resp.IntegrationType != nil {
			r.IntegrationType = types.StringValue(string(*resp.IntegrationType))
		} else {
			r.IntegrationType = types.StringNull()
		}
		r.Name = types.StringValue(resp.Name)
		r.OrgID = types.StringValue(resp.OrgID)
		r.Protected = types.BoolPointerValue(resp.Protected)
		if resp.Settings == nil {
			r.Settings = nil
		} else {
			r.Settings = &tfTypes.IntegrationSettings{}
			if resp.Settings.AutoRefresh == nil {
				r.Settings.AutoRefresh = nil
			} else {
				r.Settings.AutoRefresh = &tfTypes.AutoRefreshSettings{}
				r.Settings.AutoRefresh.Enabled = types.BoolPointerValue(resp.Settings.AutoRefresh.Enabled)
				r.Settings.AutoRefresh.FreshnessThresholdMinutes = types.Int64PointerValue(resp.Settings.AutoRefresh.FreshnessThresholdMinutes)
			}
			if resp.Settings.Notifications == nil {
				r.Settings.Notifications = nil
			} else {
				r.Settings.Notifications = &tfTypes.IntegrationNotificationConfig{}
				r.Settings.Notifications.DefaultChannels = &tfTypes.NotificationChannelSet{}
				r.Settings.Notifications.DefaultChannels.Email = types.BoolValue(resp.Settings.Notifications.DefaultChannels.Email)
				r.Settings.Notifications.DefaultChannels.InApp = types.BoolValue(resp.Settings.Notifications.DefaultChannels.InApp)
				r.Settings.Notifications.Digest = &tfTypes.NotificationDigestConfig{}
				r.Settings.Notifications.Digest.Channels = &tfTypes.NotificationChannelSet{}
				r.Settings.Notifications.Digest.Channels.Email = types.BoolValue(resp.Settings.Notifications.Digest.Channels.Email)
				r.Settings.Notifications.Digest.Channels.InApp = types.BoolValue(resp.Settings.Notifications.Digest.Channels.InApp)
				if resp.Settings.Notifications.Digest.DayOfWeek != nil {
					r.Settings.Notifications.Digest.DayOfWeek = types.Int64Value(int64(*resp.Settings.Notifications.Digest.DayOfWeek))
				} else {
					r.Settings.Notifications.Digest.DayOfWeek = types.Int64Null()
				}
				r.Settings.Notifications.Digest.Enabled = types.BoolValue(resp.Settings.Notifications.Digest.Enabled)
				r.Settings.Notifications.Digest.Frequency = types.StringValue(string(resp.Settings.Notifications.Digest.Frequency))
				r.Settings.Notifications.Digest.IncludeHealthy = types.BoolValue(resp.Settings.Notifications.Digest.IncludeHealthy)
				r.Settings.Notifications.Digest.SkipIfEmpty = types.BoolValue(resp.Settings.Notifications.Digest.SkipIfEmpty)
				r.Settings.Notifications.Digest.TimeOfDay = types.StringValue(resp.Settings.Notifications.Digest.TimeOfDay)
				r.Settings.Notifications.Digest.Timezone = types.StringValue(resp.Settings.Notifications.Digest.Timezone)
				r.Settings.Notifications.Enabled = types.BoolValue(resp.Settings.Notifications.Enabled)
				r.Settings.Notifications.MonitoredCodes = make([]types.String, 0, len(resp.Settings.Notifications.MonitoredCodes))
				for _, v := range resp.Settings.Notifications.MonitoredCodes {
					r.Settings.Notifications.MonitoredCodes = append(r.Settings.Notifications.MonitoredCodes, types.StringValue(v))
				}
				r.Settings.Notifications.MonitoredUseCases = make([]types.String, 0, len(resp.Settings.Notifications.MonitoredUseCases))
				for _, v := range resp.Settings.Notifications.MonitoredUseCases {
					r.Settings.Notifications.MonitoredUseCases = append(r.Settings.Notifications.MonitoredUseCases, types.StringValue(v))
				}
				r.Settings.Notifications.MuteUntil = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.Settings.Notifications.MuteUntil))
				r.Settings.Notifications.Recipients = []tfTypes.NotificationRecipient{}

				for _, recipientsItem := range resp.Settings.Notifications.Recipients {
					var recipients tfTypes.NotificationRecipient

					recipients.UserID = types.StringValue(recipientsItem.UserID)

					r.Settings.Notifications.Recipients = append(r.Settings.Notifications.Recipients, recipients)
				}
				r.Settings.Notifications.Rules = []tfTypes.NotificationRule{}

				for _, rulesItem := range resp.Settings.Notifications.Rules {
					var rules tfTypes.NotificationRule

					if rulesItem.Channels == nil {
						rules.Channels = nil
					} else {
						rules.Channels = &tfTypes.NotificationChannelSet{}
						rules.Channels.Email = types.BoolValue(rulesItem.Channels.Email)
						rules.Channels.InApp = types.BoolValue(rulesItem.Channels.InApp)
					}
					rules.Codes = make([]types.String, 0, len(rulesItem.Codes))
					for _, v := range rulesItem.Codes {
						rules.Codes = append(rules.Codes, types.StringValue(v))
					}
					rules.Enabled = types.BoolValue(rulesItem.Enabled)
					rules.FallbackThreshold = types.Float64PointerValue(rulesItem.FallbackThreshold)
					rules.ID = types.StringPointerValue(rulesItem.ID)
					rules.MinSampleSize = types.Int64PointerValue(rulesItem.MinSampleSize)
					rules.Name = types.StringPointerValue(rulesItem.Name)
					rules.QuietPeriod = types.StringPointerValue(rulesItem.QuietPeriod)
					if rulesItem.Sensitivity != nil {
						rules.Sensitivity = types.StringValue(string(*rulesItem.Sensitivity))
					} else {
						rules.Sensitivity = types.StringNull()
					}
					if rulesItem.Threshold != nil {
						rules.Threshold = &tfTypes.Threshold{}
						if rulesItem.Threshold.Number != nil {
							rules.Threshold.Number = types.Float64PointerValue(rulesItem.Threshold.Number)
						}
						if rulesItem.Threshold.NotificationRule2 != nil {
							if rulesItem.Threshold.NotificationRule2 != nil {
								rules.Threshold.Two = types.StringValue(string(*rulesItem.Threshold.NotificationRule2))
							} else {
								rules.Threshold.Two = types.StringNull()
							}
						}
					}
					rules.Type = types.StringValue(string(rulesItem.Type))
					rules.Window = types.StringPointerValue(rulesItem.Window)

					r.Settings.Notifications.Rules = append(r.Settings.Notifications.Rules, rules)
				}
			}
		}
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
		useCasesResult, _ := json.Marshal(resp.UseCases)
		r.UseCases = jsontypes.NewNormalizedValue(string(useCasesResult))
	}

	return diags
}

func (r *IntegrationResourceModel) ToOperationsDeleteIntegrationV2Request(ctx context.Context) (*operations.DeleteIntegrationV2Request, diag.Diagnostics) {
	var diags diag.Diagnostics

	var integrationID string
	integrationID = r.ID.ValueString()

	out := operations.DeleteIntegrationV2Request{
		IntegrationID: integrationID,
	}

	return &out, diags
}

func (r *IntegrationResourceModel) ToOperationsGetIntegrationV2Request(ctx context.Context) (*operations.GetIntegrationV2Request, diag.Diagnostics) {
	var diags diag.Diagnostics

	var integrationID string
	integrationID = r.ID.ValueString()

	out := operations.GetIntegrationV2Request{
		IntegrationID: integrationID,
	}

	return &out, diags
}

func (r *IntegrationResourceModel) ToOperationsUpdateIntegrationV2Request(ctx context.Context) (*operations.UpdateIntegrationV2Request, diag.Diagnostics) {
	var diags diag.Diagnostics

	var integrationID string
	integrationID = r.ID.ValueString()

	upsertIntegrationWithUseCasesRequest, upsertIntegrationWithUseCasesRequestDiags := r.ToSharedUpsertIntegrationWithUseCasesRequest(ctx)
	diags.Append(upsertIntegrationWithUseCasesRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateIntegrationV2Request{
		IntegrationID:                        integrationID,
		UpsertIntegrationWithUseCasesRequest: *upsertIntegrationWithUseCasesRequest,
	}

	return &out, diags
}

func (r *IntegrationResourceModel) ToSharedUpsertIntegrationWithUseCasesRequest(ctx context.Context) (*shared.UpsertIntegrationWithUseCasesRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	accessTokenIds := make([]string, 0, len(r.AccessTokenIds))
	for accessTokenIdsIndex := range r.AccessTokenIds {
		accessTokenIds = append(accessTokenIds, r.AccessTokenIds[accessTokenIdsIndex].ValueString())
	}
	appIds := make([]string, 0, len(r.AppIds))
	for appIdsIndex := range r.AppIds {
		appIds = append(appIds, r.AppIds[appIdsIndex].ValueString())
	}
	var settings *shared.IntegrationSettings
	if r.Settings != nil {
		var autoRefresh *shared.AutoRefreshSettings
		if r.Settings.AutoRefresh != nil {
			enabled := new(bool)
			if !r.Settings.AutoRefresh.Enabled.IsUnknown() && !r.Settings.AutoRefresh.Enabled.IsNull() {
				*enabled = r.Settings.AutoRefresh.Enabled.ValueBool()
			} else {
				enabled = nil
			}
			freshnessThresholdMinutes := new(int64)
			if !r.Settings.AutoRefresh.FreshnessThresholdMinutes.IsUnknown() && !r.Settings.AutoRefresh.FreshnessThresholdMinutes.IsNull() {
				*freshnessThresholdMinutes = r.Settings.AutoRefresh.FreshnessThresholdMinutes.ValueInt64()
			} else {
				freshnessThresholdMinutes = nil
			}
			autoRefresh = &shared.AutoRefreshSettings{
				Enabled:                   enabled,
				FreshnessThresholdMinutes: freshnessThresholdMinutes,
			}
		}
		var notifications *shared.IntegrationNotificationConfig
		if r.Settings.Notifications != nil {
			var enabled1 bool
			enabled1 = r.Settings.Notifications.Enabled.ValueBool()

			recipients := make([]shared.NotificationRecipient, 0, len(r.Settings.Notifications.Recipients))
			for recipientsIndex := range r.Settings.Notifications.Recipients {
				var userID string
				userID = r.Settings.Notifications.Recipients[recipientsIndex].UserID.ValueString()

				recipients = append(recipients, shared.NotificationRecipient{
					UserID: userID,
				})
			}
			var email bool
			email = r.Settings.Notifications.DefaultChannels.Email.ValueBool()

			var inApp bool
			inApp = r.Settings.Notifications.DefaultChannels.InApp.ValueBool()

			defaultChannels := shared.NotificationChannelSet{
				Email: email,
				InApp: inApp,
			}
			monitoredUseCases := make([]string, 0, len(r.Settings.Notifications.MonitoredUseCases))
			for monitoredUseCasesIndex := range r.Settings.Notifications.MonitoredUseCases {
				monitoredUseCases = append(monitoredUseCases, r.Settings.Notifications.MonitoredUseCases[monitoredUseCasesIndex].ValueString())
			}
			monitoredCodes := make([]string, 0, len(r.Settings.Notifications.MonitoredCodes))
			for monitoredCodesIndex := range r.Settings.Notifications.MonitoredCodes {
				monitoredCodes = append(monitoredCodes, r.Settings.Notifications.MonitoredCodes[monitoredCodesIndex].ValueString())
			}
			rules := make([]shared.NotificationRule, 0, len(r.Settings.Notifications.Rules))
			for rulesIndex := range r.Settings.Notifications.Rules {
				id := new(string)
				if !r.Settings.Notifications.Rules[rulesIndex].ID.IsUnknown() && !r.Settings.Notifications.Rules[rulesIndex].ID.IsNull() {
					*id = r.Settings.Notifications.Rules[rulesIndex].ID.ValueString()
				} else {
					id = nil
				}
				name1 := new(string)
				if !r.Settings.Notifications.Rules[rulesIndex].Name.IsUnknown() && !r.Settings.Notifications.Rules[rulesIndex].Name.IsNull() {
					*name1 = r.Settings.Notifications.Rules[rulesIndex].Name.ValueString()
				} else {
					name1 = nil
				}
				typeVar := shared.Type(r.Settings.Notifications.Rules[rulesIndex].Type.ValueString())
				var enabled2 bool
				enabled2 = r.Settings.Notifications.Rules[rulesIndex].Enabled.ValueBool()

				var channels *shared.NotificationChannelSet
				if r.Settings.Notifications.Rules[rulesIndex].Channels != nil {
					var email1 bool
					email1 = r.Settings.Notifications.Rules[rulesIndex].Channels.Email.ValueBool()

					var inApp1 bool
					inApp1 = r.Settings.Notifications.Rules[rulesIndex].Channels.InApp.ValueBool()

					channels = &shared.NotificationChannelSet{
						Email: email1,
						InApp: inApp1,
					}
				}
				codes := make([]string, 0, len(r.Settings.Notifications.Rules[rulesIndex].Codes))
				for codesIndex := range r.Settings.Notifications.Rules[rulesIndex].Codes {
					codes = append(codes, r.Settings.Notifications.Rules[rulesIndex].Codes[codesIndex].ValueString())
				}
				var threshold *shared.Threshold
				if r.Settings.Notifications.Rules[rulesIndex].Threshold != nil {
					number := new(float64)
					if !r.Settings.Notifications.Rules[rulesIndex].Threshold.Number.IsUnknown() && !r.Settings.Notifications.Rules[rulesIndex].Threshold.Number.IsNull() {
						*number = r.Settings.Notifications.Rules[rulesIndex].Threshold.Number.ValueFloat64()
					} else {
						number = nil
					}
					if number != nil {
						threshold = &shared.Threshold{
							Number: number,
						}
					}
					notificationRule2 := new(shared.NotificationRule2)
					if !r.Settings.Notifications.Rules[rulesIndex].Threshold.Two.IsUnknown() && !r.Settings.Notifications.Rules[rulesIndex].Threshold.Two.IsNull() {
						*notificationRule2 = shared.NotificationRule2(r.Settings.Notifications.Rules[rulesIndex].Threshold.Two.ValueString())
					} else {
						notificationRule2 = nil
					}
					if notificationRule2 != nil {
						threshold = &shared.Threshold{
							NotificationRule2: notificationRule2,
						}
					}
				}
				sensitivity := new(shared.Sensitivity)
				if !r.Settings.Notifications.Rules[rulesIndex].Sensitivity.IsUnknown() && !r.Settings.Notifications.Rules[rulesIndex].Sensitivity.IsNull() {
					*sensitivity = shared.Sensitivity(r.Settings.Notifications.Rules[rulesIndex].Sensitivity.ValueString())
				} else {
					sensitivity = nil
				}
				fallbackThreshold := new(float64)
				if !r.Settings.Notifications.Rules[rulesIndex].FallbackThreshold.IsUnknown() && !r.Settings.Notifications.Rules[rulesIndex].FallbackThreshold.IsNull() {
					*fallbackThreshold = r.Settings.Notifications.Rules[rulesIndex].FallbackThreshold.ValueFloat64()
				} else {
					fallbackThreshold = nil
				}
				window := new(string)
				if !r.Settings.Notifications.Rules[rulesIndex].Window.IsUnknown() && !r.Settings.Notifications.Rules[rulesIndex].Window.IsNull() {
					*window = r.Settings.Notifications.Rules[rulesIndex].Window.ValueString()
				} else {
					window = nil
				}
				minSampleSize := new(int64)
				if !r.Settings.Notifications.Rules[rulesIndex].MinSampleSize.IsUnknown() && !r.Settings.Notifications.Rules[rulesIndex].MinSampleSize.IsNull() {
					*minSampleSize = r.Settings.Notifications.Rules[rulesIndex].MinSampleSize.ValueInt64()
				} else {
					minSampleSize = nil
				}
				quietPeriod := new(string)
				if !r.Settings.Notifications.Rules[rulesIndex].QuietPeriod.IsUnknown() && !r.Settings.Notifications.Rules[rulesIndex].QuietPeriod.IsNull() {
					*quietPeriod = r.Settings.Notifications.Rules[rulesIndex].QuietPeriod.ValueString()
				} else {
					quietPeriod = nil
				}
				rules = append(rules, shared.NotificationRule{
					ID:                id,
					Name:              name1,
					Type:              typeVar,
					Enabled:           enabled2,
					Channels:          channels,
					Codes:             codes,
					Threshold:         threshold,
					Sensitivity:       sensitivity,
					FallbackThreshold: fallbackThreshold,
					Window:            window,
					MinSampleSize:     minSampleSize,
					QuietPeriod:       quietPeriod,
				})
			}
			var enabled3 bool
			enabled3 = r.Settings.Notifications.Digest.Enabled.ValueBool()

			frequency := shared.Frequency(r.Settings.Notifications.Digest.Frequency.ValueString())
			dayOfWeek := new(shared.DayOfWeek)
			if !r.Settings.Notifications.Digest.DayOfWeek.IsUnknown() && !r.Settings.Notifications.Digest.DayOfWeek.IsNull() {
				*dayOfWeek = shared.DayOfWeek(r.Settings.Notifications.Digest.DayOfWeek.ValueInt64())
			} else {
				dayOfWeek = nil
			}
			var timeOfDay string
			timeOfDay = r.Settings.Notifications.Digest.TimeOfDay.ValueString()

			var timezone string
			timezone = r.Settings.Notifications.Digest.Timezone.ValueString()

			var email2 bool
			email2 = r.Settings.Notifications.Digest.Channels.Email.ValueBool()

			var inApp2 bool
			inApp2 = r.Settings.Notifications.Digest.Channels.InApp.ValueBool()

			channels1 := shared.NotificationChannelSet{
				Email: email2,
				InApp: inApp2,
			}
			var includeHealthy bool
			includeHealthy = r.Settings.Notifications.Digest.IncludeHealthy.ValueBool()

			var skipIfEmpty bool
			skipIfEmpty = r.Settings.Notifications.Digest.SkipIfEmpty.ValueBool()

			digest := shared.NotificationDigestConfig{
				Enabled:        enabled3,
				Frequency:      frequency,
				DayOfWeek:      dayOfWeek,
				TimeOfDay:      timeOfDay,
				Timezone:       timezone,
				Channels:       channels1,
				IncludeHealthy: includeHealthy,
				SkipIfEmpty:    skipIfEmpty,
			}
			muteUntil := new(time.Time)
			if !r.Settings.Notifications.MuteUntil.IsUnknown() && !r.Settings.Notifications.MuteUntil.IsNull() {
				*muteUntil, _ = time.Parse(time.RFC3339Nano, r.Settings.Notifications.MuteUntil.ValueString())
			} else {
				muteUntil = nil
			}
			notifications = &shared.IntegrationNotificationConfig{
				Enabled:           enabled1,
				Recipients:        recipients,
				DefaultChannels:   defaultChannels,
				MonitoredUseCases: monitoredUseCases,
				MonitoredCodes:    monitoredCodes,
				Rules:             rules,
				Digest:            digest,
				MuteUntil:         muteUntil,
			}
		}
		settings = &shared.IntegrationSettings{
			AutoRefresh:   autoRefresh,
			Notifications: notifications,
		}
	}
	integrationType := new(shared.UpsertIntegrationWithUseCasesRequestIntegrationType)
	if !r.IntegrationType.IsUnknown() && !r.IntegrationType.IsNull() {
		*integrationType = shared.UpsertIntegrationWithUseCasesRequestIntegrationType(r.IntegrationType.ValueString())
	} else {
		integrationType = nil
	}
	var connectorConfig *shared.ConnectorConfig
	if r.ConnectorConfig != nil {
		baseURL := new(string)
		if !r.ConnectorConfig.BaseURL.IsUnknown() && !r.ConnectorConfig.BaseURL.IsNull() {
			*baseURL = r.ConnectorConfig.BaseURL.ValueString()
		} else {
			baseURL = nil
		}
		var auth *shared.ManagedCallAuth
		if r.ConnectorConfig.Auth != nil {
			typeVar1 := new(shared.ManagedCallAuthType)
			if !r.ConnectorConfig.Auth.Type.IsUnknown() && !r.ConnectorConfig.Auth.Type.IsNull() {
				*typeVar1 = shared.ManagedCallAuthType(r.ConnectorConfig.Auth.Type.ValueString())
			} else {
				typeVar1 = nil
			}
			tokenURL := new(string)
			if !r.ConnectorConfig.Auth.TokenURL.IsUnknown() && !r.ConnectorConfig.Auth.TokenURL.IsNull() {
				*tokenURL = r.ConnectorConfig.Auth.TokenURL.ValueString()
			} else {
				tokenURL = nil
			}
			clientID := new(string)
			if !r.ConnectorConfig.Auth.ClientID.IsUnknown() && !r.ConnectorConfig.Auth.ClientID.IsNull() {
				*clientID = r.ConnectorConfig.Auth.ClientID.ValueString()
			} else {
				clientID = nil
			}
			clientSecret := new(string)
			if !r.ConnectorConfig.Auth.ClientSecret.IsUnknown() && !r.ConnectorConfig.Auth.ClientSecret.IsNull() {
				*clientSecret = r.ConnectorConfig.Auth.ClientSecret.ValueString()
			} else {
				clientSecret = nil
			}
			scope := new(string)
			if !r.ConnectorConfig.Auth.Scope.IsUnknown() && !r.ConnectorConfig.Auth.Scope.IsNull() {
				*scope = r.ConnectorConfig.Auth.Scope.ValueString()
			} else {
				scope = nil
			}
			audience := new(string)
			if !r.ConnectorConfig.Auth.Audience.IsUnknown() && !r.ConnectorConfig.Auth.Audience.IsNull() {
				*audience = r.ConnectorConfig.Auth.Audience.ValueString()
			} else {
				audience = nil
			}
			resource := new(string)
			if !r.ConnectorConfig.Auth.Resource.IsUnknown() && !r.ConnectorConfig.Auth.Resource.IsNull() {
				*resource = r.ConnectorConfig.Auth.Resource.ValueString()
			} else {
				resource = nil
			}
			bodyParams := make(map[string]string)
			for bodyParamsKey := range r.ConnectorConfig.Auth.BodyParams {
				var bodyParamsInst string
				bodyParamsInst = r.ConnectorConfig.Auth.BodyParams[bodyParamsKey].ValueString()

				bodyParams[bodyParamsKey] = bodyParamsInst
			}
			headers := make(map[string]string)
			for headersKey := range r.ConnectorConfig.Auth.Headers {
				var headersInst string
				headersInst = r.ConnectorConfig.Auth.Headers[headersKey].ValueString()

				headers[headersKey] = headersInst
			}
			queryParams := make(map[string]string)
			for queryParamsKey := range r.ConnectorConfig.Auth.QueryParams {
				var queryParamsInst string
				queryParamsInst = r.ConnectorConfig.Auth.QueryParams[queryParamsKey].ValueString()

				queryParams[queryParamsKey] = queryParamsInst
			}
			apiKeyHeader := new(string)
			if !r.ConnectorConfig.Auth.APIKeyHeader.IsUnknown() && !r.ConnectorConfig.Auth.APIKeyHeader.IsNull() {
				*apiKeyHeader = r.ConnectorConfig.Auth.APIKeyHeader.ValueString()
			} else {
				apiKeyHeader = nil
			}
			apiKey := new(string)
			if !r.ConnectorConfig.Auth.APIKey.IsUnknown() && !r.ConnectorConfig.Auth.APIKey.IsNull() {
				*apiKey = r.ConnectorConfig.Auth.APIKey.ValueString()
			} else {
				apiKey = nil
			}
			token := new(string)
			if !r.ConnectorConfig.Auth.Token.IsUnknown() && !r.ConnectorConfig.Auth.Token.IsNull() {
				*token = r.ConnectorConfig.Auth.Token.ValueString()
			} else {
				token = nil
			}
			auth = &shared.ManagedCallAuth{
				Type:         typeVar1,
				TokenURL:     tokenURL,
				ClientID:     clientID,
				ClientSecret: clientSecret,
				Scope:        scope,
				Audience:     audience,
				Resource:     resource,
				BodyParams:   bodyParams,
				Headers:      headers,
				QueryParams:  queryParams,
				APIKeyHeader: apiKeyHeader,
				APIKey:       apiKey,
				Token:        token,
			}
		}
		typesVersions := make([]shared.TypesVersions, 0, len(r.ConnectorConfig.TypesVersions))
		for typesVersionsIndex := range r.ConnectorConfig.TypesVersions {
			var version string
			version = r.ConnectorConfig.TypesVersions[typesVersionsIndex].Version.ValueString()

			var packageName string
			packageName = r.ConnectorConfig.TypesVersions[typesVersionsIndex].PackageName.ValueString()

			generatedAt, _ := time.Parse(time.RFC3339Nano, r.ConnectorConfig.TypesVersions[typesVersionsIndex].GeneratedAt.ValueString())
			var generatedBy string
			generatedBy = r.ConnectorConfig.TypesVersions[typesVersionsIndex].GeneratedBy.ValueString()

			status := shared.ConnectorConfigStatus(r.ConnectorConfig.TypesVersions[typesVersionsIndex].Status.ValueString())
			typesVersions = append(typesVersions, shared.TypesVersions{
				Version:     version,
				PackageName: packageName,
				GeneratedAt: generatedAt,
				GeneratedBy: generatedBy,
				Status:      status,
			})
		}
		latestTypesVersion := new(string)
		if !r.ConnectorConfig.LatestTypesVersion.IsUnknown() && !r.ConnectorConfig.LatestTypesVersion.IsNull() {
			*latestTypesVersion = r.ConnectorConfig.LatestTypesVersion.ValueString()
		} else {
			latestTypesVersion = nil
		}
		latestTypesPackageName := new(string)
		if !r.ConnectorConfig.LatestTypesPackageName.IsUnknown() && !r.ConnectorConfig.LatestTypesPackageName.IsNull() {
			*latestTypesPackageName = r.ConnectorConfig.LatestTypesPackageName.ValueString()
		} else {
			latestTypesPackageName = nil
		}
		connectorConfig = &shared.ConnectorConfig{
			BaseURL:                baseURL,
			Auth:                   auth,
			TypesVersions:          typesVersions,
			LatestTypesVersion:     latestTypesVersion,
			LatestTypesPackageName: latestTypesPackageName,
		}
	}
	protected := new(bool)
	if !r.Protected.IsUnknown() && !r.Protected.IsNull() {
		*protected = r.Protected.ValueBool()
	} else {
		protected = nil
	}
	manifest := make([]string, 0, len(r.Manifest))
	for manifestIndex := range r.Manifest {
		manifest = append(manifest, r.Manifest[manifestIndex].ValueString())
	}
	var environmentConfig interface{}
	if !r.EnvironmentConfig.IsUnknown() && !r.EnvironmentConfig.IsNull() {
		_ = json.Unmarshal([]byte(r.EnvironmentConfig.ValueString()), &environmentConfig)
	}
	var useCases interface{}
	if !r.UseCases.IsUnknown() && !r.UseCases.IsNull() {
		_ = json.Unmarshal([]byte(r.UseCases.ValueString()), &useCases)
	}
	out := shared.UpsertIntegrationWithUseCasesRequest{
		Name:              name,
		Description:       description,
		AccessTokenIds:    accessTokenIds,
		AppIds:            appIds,
		Settings:          settings,
		IntegrationType:   integrationType,
		ConnectorConfig:   connectorConfig,
		Protected:         protected,
		Manifest:          manifest,
		EnvironmentConfig: environmentConfig,
		UseCases:          useCases,
	}

	return &out, diags
}
