// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DeliveryConfig struct {
	Type        types.String `tfsdk:"type"`
	WebhookID   types.String `tfsdk:"webhook_id"`
	WebhookName types.String `tfsdk:"webhook_name"`
	WebhookURL  types.String `tfsdk:"webhook_url"`
}
