// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Enabled struct {
	Boolean types.Bool   `queryParam:"inline" tfsdk:"boolean"`
	Str     types.String `queryParam:"inline" tfsdk:"str"`
}
