// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type FileProxyUseCaseConfiguration struct {
	Auth        *FileProxyAuth           `tfsdk:"auth"`
	Params      []FileProxyParam         `tfsdk:"params"`
	RequiresVpc types.Bool               `tfsdk:"requires_vpc"`
	Response    *FileProxyResponseConfig `tfsdk:"response"`
	Steps       []FileProxyStep          `tfsdk:"steps"`
}
