// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type FileProxyURLParam struct {
	One   *One   `queryParam:"inline" tfsdk:"one"`
	Two   *Two   `queryParam:"inline" tfsdk:"two"`
	Three *Three `queryParam:"inline" tfsdk:"three"`
}
