// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type IntegrationEntityField struct {
	Type              types.String         `tfsdk:"type"`
	Attribute         types.String         `tfsdk:"attribute"`
	Constant          jsontypes.Normalized `tfsdk:"constant"`
	Enabled           *Enabled             `tfsdk:"enabled"`
	Field             types.String         `tfsdk:"field"`
	JsonataExpression types.String         `tfsdk:"jsonata_expression"`
	RelationRefs      *RelationRefsConfig  `tfsdk:"relation_refs"`
	Relations         *RelationConfig      `tfsdk:"relations"`
}
