// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type IntegrationSettings struct {
	AutoRefresh   *AutoRefreshSettings           `tfsdk:"auto_refresh"`
	Notifications *IntegrationNotificationConfig `tfsdk:"notifications"`
}
