// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type IntegrationEntity struct {
	Enabled           *Enabled                 `tfsdk:"enabled"`
	EntitySchema      types.String             `tfsdk:"entity_schema"`
	Fields            []IntegrationEntityField `tfsdk:"fields"`
	JsonataExpression types.String             `tfsdk:"jsonata_expression"`
	Mode              types.String             `tfsdk:"mode"`
	Scope             *PruneScopeConfig        `tfsdk:"scope"`
	UniqueIds         []types.String           `tfsdk:"unique_ids"`
}
