// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type IntegrationMeterReading struct {
	Fields            []IntegrationEntityField      `tfsdk:"fields"`
	JsonataExpression types.String                  `tfsdk:"jsonata_expression"`
	Meter             *MeterUniqueIdsConfig         `tfsdk:"meter"`
	MeterCounter      *MeterUniqueIdsConfig         `tfsdk:"meter_counter"`
	Mode              types.String                  `tfsdk:"mode"`
	ReadingMatching   types.String                  `tfsdk:"reading_matching"`
	Scope             *MeterReadingPruneScopeConfig `tfsdk:"scope"`
}
