// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type IntegrationNotificationConfig struct {
	DefaultChannels   *NotificationChannelSet   `tfsdk:"default_channels"`
	Digest            *NotificationDigestConfig `tfsdk:"digest"`
	Enabled           types.Bool                `tfsdk:"enabled"`
	MonitoredCodes    []types.String            `tfsdk:"monitored_codes"`
	MonitoredUseCases []types.String            `tfsdk:"monitored_use_cases"`
	MuteUntil         types.String              `tfsdk:"mute_until"`
	Recipients        []NotificationRecipient   `tfsdk:"recipients"`
	Rules             []NotificationRule        `tfsdk:"rules"`
}
