// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ManagedCallAuth struct {
	APIKey       types.String            `tfsdk:"api_key"`
	APIKeyHeader types.String            `tfsdk:"api_key_header"`
	Audience     types.String            `tfsdk:"audience"`
	BodyParams   map[string]types.String `tfsdk:"body_params"`
	ClientID     types.String            `tfsdk:"client_id"`
	ClientSecret types.String            `tfsdk:"client_secret"`
	Headers      map[string]types.String `tfsdk:"headers"`
	QueryParams  map[string]types.String `tfsdk:"query_params"`
	Resource     types.String            `tfsdk:"resource"`
	Scope        types.String            `tfsdk:"scope"`
	Token        types.String            `tfsdk:"token"`
	TokenURL     types.String            `tfsdk:"token_url"`
	Type         types.String            `tfsdk:"type"`
}
