// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type RelationRefsConfig struct {
	Items             []RelationRefItemConfig `tfsdk:"items"`
	JsonataExpression types.String            `tfsdk:"jsonata_expression"`
	Operation         types.String            `tfsdk:"operation"`
}
