// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type UseCase struct {
	Inbound  *InboundUseCase  `queryParam:"inline" tfsdk:"inbound"`
	Outbound *OutboundUseCase `queryParam:"inline" tfsdk:"outbound"`
}
